OpenCog Framework: graphEdge Class Reference
graphEdge Class Reference
Base class type for edges of non-oriented graphs.
#include <graph.h>
Public Member Functions
graphEdge (graphNode *, graphNode *)
Constructor.
virtual ~graphEdge ()
graphNode * oppositeNode (graphNode *n)
Returns the node oppsite to 'n'. O(1).
bool isUnlinked ()
Returns TRUE if this edge does not connect points. O(1).
bool hasNode (graphNode *n)
Returns TRUE if 'n' is a node of this edge. O(1).
void makeUnlinked ()
Makes this edge as 'unlinked' from the graph. O(1).
void collapse ()
Edge collapse. O(degree of neighbors).
Public Attributes
graphNode * n1
Edge's end-points.
graphNode * n2
unsigned char mask
Generic 8-bit mask for marking purposes.
Detailed Description
Base class type for edges of non-oriented graphs.
Definition at line 59 of file graph.h.
Constructor & Destructor Documentation
graphEdge::graphEdge (graphNode * a, graphNode * b)
Constructor.
Definition at line 38 of file graph.cpp.
References List::appendHead(), graphNode::edges, n1, and n2.
{
 n1=a; n2=b;
 n1->edges.appendHead(this);
 n2->edges.appendHead(this);
}
virtual graphEdge::~graphEdge () [inline, virtual]
Definition at line 71 of file graph.h.
{}
Member Function Documentation
void graphEdge::collapse ()
Edge collapse. O(degree of neighbors).
After one (or a series of) collapse, remember to call Graph::deleteUnlinkedElements() to make the graph coherent with its node and edge lists.
Definition at line 58 of file graph.cpp.
References List::appendHead(), Node::data, graphNode::edges, FOREACHNODE, List::head(), isUnlinked(), makeUnlinked(), graphNode::mask, n1, n2, Node::next(), oppositeNode(), List::popHead(), Node::prev(), List::removeCell(), List::removeNode(), and List::tail().
{
 Node *n;
 graphEdge *e;
 graphNode *nx;
 while ((e = (graphEdge *)n2->edges.popHead()) != NULL)
  if (e != this)
  {
   ((e->n1 == n2)?(e->n1):(e->n2)) = n1;
   n1->edges.appendHead(e);
  }
 FOREACHNODE(n1->edges, n)
 {
  e = (graphEdge *)n->data;
  if (!e->isUnlinked()) e->oppositeNode(n1)->mask = 0;
 }
 n2->mask = 1;
 FOREACHNODE(n1->edges, n)
 {
  e = (graphEdge *)n->data;
  if (e != this)
  {
   nx = e->oppositeNode(n1);
   if (nx->mask) {nx->edges.removeNode(e); e->makeUnlinked();}
   nx->mask = 1;
  }
 }
 n = n1->edges.head();
 while (n != NULL)
 {
  e = (graphEdge *)n->data;
  n = n->next();
  if (e->isUnlinked()) n1->edges.removeCell((n!=NULL)?(n->prev()):n1->edges.tail());
 }
 FOREACHNODE(n1->edges, n)
   ((graphEdge *)n->data)->oppositeNode(n1)->mask = 0;
 n1->edges.removeNode(this);
 makeUnlinked();
}
bool graphEdge::hasNode (graphNode * n) [inline]
Returns TRUE if 'n' is a node of this edge. O(1).
Definition at line 80 of file graph.h.
References n1, and n2.
{return (n1==n || n2==n);}
bool graphEdge::isUnlinked () [inline]
Returns TRUE if this edge does not connect points. O(1).
Definition at line 77 of file graph.h.
References n1.
{return (n1==NULL);}
void graphEdge::makeUnlinked () [inline]
Makes this edge as 'unlinked' from the graph. O(1).
Definition at line 83 of file graph.h.
References n1, and n2.
{n1=NULL; n2=NULL;}
graphNode* graphEdge::oppositeNode (graphNode * n) [inline]
Returns the node oppsite to 'n'. O(1).
Definition at line 74 of file graph.h.
References n1, and n2.
{return (n1==n)?(n2):((n2==n)?(n1):(NULL));}
Member Data Documentation
unsigned char graphEdge::mask
Generic 8-bit mask for marking purposes.
Definition at line 67 of file graph.h.
graphNode* graphEdge::n1
Edge's end-points.
Definition at line 64 of file graph.h.
graphNode * graphEdge::n2
Definition at line 64 of file graph.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/graph.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/graph.cpp