OpenCog Framework: Triangulation Class Reference
Triangulation Class Reference
Triangulation.
#include <tin.h>
Public Member Functions
Triangulation ()
Empty triangulation. Should be used only prior to a call to load().
Triangulation (const char *)
Pre-defined triangulation. Currently, only "tetrahedron" is recognized.
Triangulation (const Triangulation *, const bool clone_info=false)
Clones an existing Trianglation.
Triangulation (const Triangle *t, const bool keep_ref=false)
Clones an existing connected component.
~Triangulation ()
int boundaries ()
Get the number of boundary loops of the triangle mesh. O(1) or O(N).
int handles ()
Get the number of handles of the triangle mesh. O(1) or O(N).
int shells ()
Get the number of connected components of the triangle mesh. O(1) or O(N).
int load (const char *filename, const bool update=1)
Initialize the triangle mesh from the file 'filename'.
int cutAndStitch ()
Convert to manifold.
bool CreateIndexedTriangle (ExtVertex **, int, int, int)
int loadIV (const char *)
Loads IV.
int loadVRML1 (const char *)
Loads VRML 1.0.
int loadOFF (const char *)
Loads OFF.
int loadPLY (const char *)
Loads PLY.
int loadVerTri (const char *)
Loads VER-TRI.
int loadVRML2 (const char *)
Loads VRML 2.0.
int loadOBJ (const char *)
Loads OBJ.
int loadSTL (const char *)
Loads STL.
int save (const char *filename, bool back_approx=0)
Save the triangle mesh to file 'filename'.
int saveIV (const char *)
Saves IV.
int saveOFF (const char *)
Saves OFF 1.0.
int saveOBJ (const char *)
Saves OBJ.
int saveSTL (const char *)
Saves STL.
int savePLY (const char *, bool ascii=1)
Saves PLY 1.0 (ascii or binary)
int saveVerTri (const char *)
Saves Ver-Tri.
int saveVRML1 (const char *, const int mode=0)
int append (const char *filename, const bool doupdate=1)
Append another triangle mesh to the existing one.
Edge * CreateEdge (Vertex *v1, Vertex *v2)
Creates an Edge connecting two existing mesh vertices.
Edge * CreateEdge (ExtVertex *v1, ExtVertex *v2, const bool check=1)
Creates an Edge connecting two existing mesh Extended vertices.
Triangle * CreateTriangle (Edge *e1, Edge *e2, Edge *e3)
Creates a properly oriented Triangle bounded by three existing mesh edges.
Triangle * CreateUnorientedTriangle (Edge *, Edge *, Edge *)
Creates an arbitrarily oriented Triangle bounded by three existing mesh edges.
Triangle * EulerEdgeTriangle (Edge *e1, Edge *e2)
Creates a new Edge 'e' and an oriented Triangle bounded by 'e', 'e1' and 'e2'.
void unlinkTriangle (Triangle *)
Unlinks a triangle from the mesh. O(1).
void unlinkTriangleNoManifold (Triangle *)
Unlinks a triangle from the mesh. O(1).
void removeTriangle (Triangle *t)
Removes a triangle from the mesh. O(N).
int removeTriangles ()
Removes all the unlinked triangles from List T. Returns the number of removed triangles. O(N).
int removeEdges ()
Removes all the unlinked edges from List E. Returns the number of removed edges. O(N).
int removeVertices ()
Removes all the unlinked vertices from List V. Returns the number of removed vertices. O(N).
int removeUnlinkedElements ()
Removes all the unlinked elements from the lists. Returns the number of removed elements. O(N).
void deselectTriangles ()
Deselects all the triangles. O(N).
void removeSelectedTriangles ()
Removes all the selected triangles. O(N).
int selectBoundaryTriangles ()
int growSelection ()
Enlarges the current selection of one triangle in width. O(N).
void shrinkSelection ()
Shrinks the current selection of one triangle in width. O(N).
void invertSelection (Triangle *t0=NULL)
Inverts the selection status of all the triangles. O(N).
void reselectSelection (Triangle *t0)
If 't0' is selected, deselect everything but the selected triangles connected to 't0'.
Triangulation * createSubMeshFromSelection (Triangle *t0=NULL, bool keep_ref=0)
Creates a new Triangulation out of an existing selection containing 't0'. O(output).
int selectSphericalRegion (Triangle *t0, const double L, const Point *p)
Marks all the triangles within distance L from 'p' as selected. O(output).
int deselectSphericalRegion (Triangle *t0, const double L, const Point *p)
Marks all the triangles within distance L from 'p' as deselected. O(output).
void reselectSphericalRegion (Triangle *t0, const double L, const Point *p)
Deselects all the triangles farther than L from 'p'. O(N).
bool retriangulateSelectedRegion ()
Re-triangulates the currently selected region using a Delaunay-like approach. O(SlogS).
bool isSelectionSimple (List *l)
TRUE iff the set of selected triangles in 'l' is simply connected. O(l->numels()).
void unmarkEverythingButSelections ()
Unmarks all the elements but leaves the selection status of triangles as is. O(N).
int selectConnectedComponent (Triangle *t0, bool stop_on_sharp=0)
Selects all the triangles of the connected component containing t0. O(N).
int deselectConnectedComponent (Triangle *t0, bool stop_on_sharp=0)
Deselects all the triangles of the connected component containing t0. O(N).
void append (Triangulation *t)
Append to the current mesh a copy of all the elements of 't'.
List * getRegion (Triangle *t0, const double L, const Point *p)
Make a list of triangles within distance L from 'p'. O(output).
void removeRegion (Triangle *t0, const double L, const Point *p)
Removes triangles within distance L from 'p'. O(N).
Vertex * nextVertexOnRegionBoundary (Vertex *v) const
Get the vertex next to 'v' on the boundary of the region. O(1).
List * getRegionInternalVertices (List *l)
Retrieve internal vertices of a region. O(l->numels()).
void transformShell (Triangle *t0, const Matrix4x4 &m)
Transform the vertices of the shell containing 't0' using the matrix m. O(S).
void removeShell (Triangle *t0)
Remove all the triangles belonging to the shell containing 't0'. O(N).
void sharpEdgeTagging (const double t)
Tag sharp edges based on threshold angle. O(N).
void unmarkEverything ()
Unmark all the elements. O(N).
double getBoundingBox (Point &b, Point &t) const
Bounding box longest edge. 'b' and 't' are set as the longest diagonal end-points. O(N).
double bboxLongestDiagonal ()
Bounding box longest diagonal. O(N).
double getBoundingBallRadius () const
Approximate bounding ball radius. O(N).
double area () const
Total area of the mesh. O(N).
double volume () const
Total volume of the mesh assuming that boundaries() = 0. O(N).
void normalize (const double s=1.0)
Scale the mesh to make it fit within a cube [0,0,0]-[s,s,s]. O(N).
void transform (const Matrix4x4 &m)
Transform the mesh geometry using the transformation matrix m. O(N).
void addNormalNoise (const double p)
Randomly move vertices along their normals. O(N).
bool iterativeEdgeSwaps ()
Iteratively swaps edges to minimize the Delaunay minimum angle. O(N).
void flipNormals ()
Invert all the triangle and edge orientations. O(N).
void flipNormals (Triangle *t0)
Invert the orientation of triangles and edges belonging to the shell containing 't0'. O(S).
Triangle * topTriangle (Triangle *t0)
Return the triangle with the maximum 'z' coordinate in the shell containing 't0'. O(N).
void eulerUpdate ()
Updates the values of n_boundaries, n_handles and n_shells. O(N).
void openToDisk ()
Duplicates edges and vertices to make the mesh homeomorphic to a disk. O(N).
int removeSmallestComponents ()
int forceNormalConsistence ()
int forceNormalConsistence (Triangle *)
int duplicateNonManifoldVertices ()
const char * checkConnectivity ()
int removeDuplicatedTriangles ()
int checkAndRepair ()
int mergeCoincidentEdges ()
int removeDegenerateTriangles ()
int removeOverlappingTriangles ()
int selectTinyHandles (double)
Vertex * checkGeometry ()
int StarTriangulateHole (Edge *)
int TriangulateHole (Edge *, Point *)
int TriangulateHole (Edge *, List *)
Vertex * watsonInsert (Point *, List *, int)
int retriangulateVT (Vertex *)
Vertex * splitEdge (Edge *, Point *, bool=0)
Vertex * splitTriangle (Triangle *, Point *, bool=0)
void printReport ()
Public Attributes
List V
Vertex set.
List E
Edge set.
List T
Triangle set.
Protected Member Functions
void closeLoadingSession (FILE *, int, ExtVertex **, bool)
void coordBackApproximation ()
Protected Attributes
int n_boundaries
Number of boundary loops.
int n_handles
Number of handles.
int n_shells
Number of connected components.
bool d_boundaries
Dirty bit for n_boundaries.
bool d_handles
Dirty bit for n_handles.
bool d_shells
Dirty bit for n_shells.
Detailed Description
Triangulation.
This class represents a manifold and oriented triangle mesh. Vertices, Edges and Triangles are stored in the Lists V, E and T respectively. Methods boundaries(), handles() and shells() may be used to retrieve the respective topological entities. Navigation of the mesh is based on the topological relationships stored in each Vertex, Edge and Triangle. Some methods would require a global update only to maintain consistent values of the protected fields n_boundaries, n_handles and n_shells. On the other hand, the same methods would work in constant time if these values would not need to be updated. To keep complexity as low as possible, we make use of the 'dirty bits' d_boundaries, d_handles and d_shells to mark that the respective entities must be updated. The access functions boundaries(), handles() and shells() check the status of the respective dirty bit and do a global update (i.e., eulerUpdate()) only if necessary. The complexity of the methods is provided as a function of a generic 'N', which is O(V.numels()) = O(E.numels()) = O(T.numels()).
Definition at line 54 of file tin.h.
Constructor & Destructor Documentation
Triangulation::Triangulation ()
Empty triangulation. Should be used only prior to a call to load().
Definition at line 42 of file tin.cpp.
References d_boundaries, d_handles, d_shells, n_boundaries, n_handles, and n_shells.
{
 n_boundaries = n_handles = n_shells = 0;
 d_boundaries = d_handles = d_shells = 0;
}
Triangulation::Triangulation (const char * tin_definition)
Pre-defined triangulation. Currently, only "tetrahedron" is recognized.
Definition at line 51 of file tin.cpp.
References List::appendHead(), d_boundaries, d_handles, d_shells, E, Vertex::e0, JMesh::error(), n_boundaries, n_handles, n_shells, T, Edge::t1, Edge::t2, and V.
{
 if (!strcmp(tin_definition, "tetrahedron"))
 {
  Vertex *v1 = new Vertex(-1,-1.4142136,0);
  Vertex *v2 = new Vertex(-1,1.4142136,0);
  Vertex *v3 = new Vertex(1,0,-1.4142136);
  Vertex *v4 = new Vertex(1,0,1.4142136);
  Edge   *e1 = new Edge(v1,v2); v1->e0 = e1;
  Edge   *e2 = new Edge(v2,v3); v2->e0 = e2;
  Edge   *e3 = new Edge(v3,v1); v3->e0 = e3;
  Edge   *e4 = new Edge(v1,v4); v4->e0 = e4;
  Edge   *e5 = new Edge(v2,v4);
  Edge   *e6 = new Edge(v3,v4);
  Triangle *t1 = new Triangle(e1,e2,e3);
  Triangle *t2 = new Triangle(e1,e4,e5);
  Triangle *t3 = new Triangle(e2,e5,e6);
  Triangle *t4 = new Triangle(e3,e6,e4);
  e1->t1 = t1; e1->t2 = t2;
  e2->t1 = t1; e2->t2 = t3;
  e3->t1 = t1; e3->t2 = t4;
  e4->t1 = t2; e4->t2 = t4;
  e5->t1 = t3; e5->t2 = t2;
  e6->t1 = t4; e6->t2 = t3;
  V.appendHead(v1); V.appendHead(v2); V.appendHead(v3); V.appendHead(v4);
  T.appendHead(t1); T.appendHead(t2); T.appendHead(t3); T.appendHead(t4);
  E.appendHead(e1); E.appendHead(e2); E.appendHead(e3);
  E.appendHead(e4); E.appendHead(e5); E.appendHead(e6);
  n_boundaries = 0;
  n_handles = 0;
  n_shells = 1;
  d_boundaries = d_handles = d_shells = 0;
 }
 else JMesh::error("Unknown triangulation type '%s'\n",tin_definition);
}
Triangulation::Triangulation (const Triangulation * tin, const bool clone_info = false)
Clones an existing Trianglation.
Definition at line 91 of file tin.cpp.
References List::appendTail(), d_boundaries, d_handles, d_shells, E, Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHEDGE, FOREACHTRIANGLE, FOREACHVEEDGE, FOREACHVERTEX, FOREACHVTTRIANGLE, FOREACHVVVERTEX, Point::info, Edge::info, Triangle::info, List::numels(), T, Edge::t1, Edge::t2, V, Edge::v1, and Edge::v2.
{
 Node *n;
 Vertex *v, *nv;
 Edge *e, *ne;
 Triangle *t, *nt;
 int i;
 void **t_info = new void *[tin->T.numels()];
 i=0; FOREACHVTTRIANGLE((&(tin->T)), t, n) t_info[i++]=t->info;
 void **e_info = new void *[tin->E.numels()];
 i=0; FOREACHVEEDGE((&(tin->E)), e, n) e_info[i++]=e->info;
 void **v_info = new void *[tin->V.numels()];
 i=0; FOREACHVVVERTEX((&(tin->V)), v, n) v_info[i++]=v->info;
 FOREACHVVVERTEX((&(tin->V)), v, n)
  {nv=new Vertex(v); V.appendTail(nv); v->info = nv;}
 FOREACHVEEDGE((&(tin->E)), e, n)
  {ne=new Edge((Vertex *)e->v1->info, (Vertex *)e->v2->info); E.appendTail(ne); e->info = ne;}
 FOREACHVTTRIANGLE((&(tin->T)), t, n)
  {nt=new Triangle((Edge *)t->e1->info,(Edge *)t->e2->info,(Edge *)t->e3->info); T.appendTail(nt); t->info = nt;}
 FOREACHVVVERTEX((&(tin->V)), v, n) {((Vertex *)v->info)->e0 = (Edge *)v->e0->info; v->info = NULL;}
 FOREACHVEEDGE((&(tin->E)), e, n)
  {((Edge *)e->info)->t1 = (e->t1)?((Triangle *)e->t1->info):(NULL); ((Edge *)e->info)->t2 = (e->t2)?((Triangle *)e->t2->info):(NULL); e->info = NULL;}
 i=0; FOREACHVTTRIANGLE((&(tin->T)), t, n) t->info=t_info[i++];
 i=0; FOREACHVEEDGE((&(tin->E)), e, n) e->info=e_info[i++];
 i=0; FOREACHVVVERTEX((&(tin->V)), v, n) v->info=v_info[i++];
 if (clone_info)
 {
  i=0; FOREACHTRIANGLE(t, n) t->info=t_info[i++];
  i=0; FOREACHEDGE(e, n) e->info=e_info[i++];
  i=0; FOREACHVERTEX(v, n) v->info=v_info[i++];
 }
 delete [] t_info; delete [] e_info; delete [] v_info;
 d_boundaries = d_handles = d_shells = 1;
}
Triangulation::Triangulation (const Triangle * t, const bool keep_ref = false)
Clones an existing connected component.
Creates a new Triangulation out of a connected component of an existing Triangulation. 't' is a triangle of the connected component that must be copied. If 'keep_ref' is TRUE, each element of the existing mesh keeps a pointer to the corresponding new element in the 'info' field.
Definition at line 140 of file tin.cpp.
References List::appendHead(), List::appendTail(), E, Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, eulerUpdate(), FOREACHVEEDGE, FOREACHVTTRIANGLE, FOREACHVVVERTEX, Triangle::info, Edge::info, Point::info, IS_VISITED2, MARK_VISIT2, T, Edge::t1, Triangle::t1(), Edge::t2, Triangle::t2(), Triangle::t3(), UNMARK_VISIT2, V, Edge::v1, Triangle::v1(), Edge::v2, Triangle::v2(), and Triangle::v3().
{
 List todo(t0), st, sv, se;
 Node *n;
 Triangle *t, *nt;
 Vertex *v, *nv;
 Edge *e, *ne;
 while (todo.numels())
 {
  t = (Triangle *)todo.popHead();
  st.appendHead(t);
  nt=t->t1(); if (nt != NULL && !IS_VISITED2(nt)) {MARK_VISIT2(nt); todo.appendHead(nt);}
  nt=t->t2(); if (nt != NULL && !IS_VISITED2(nt)) {MARK_VISIT2(nt); todo.appendHead(nt);}
  nt=t->t3(); if (nt != NULL && !IS_VISITED2(nt)) {MARK_VISIT2(nt); todo.appendHead(nt);}
 }
 FOREACHVTTRIANGLE((&st), t, n)
 {
  UNMARK_VISIT2(t);
  e = t->e1; if (!IS_VISITED2(e)) {MARK_VISIT2(e); se.appendHead(e);}
  e = t->e2; if (!IS_VISITED2(e)) {MARK_VISIT2(e); se.appendHead(e);}
  e = t->e3; if (!IS_VISITED2(e)) {MARK_VISIT2(e); se.appendHead(e);}
  v = t->v1(); if (!IS_VISITED2(v)) {MARK_VISIT2(v); sv.appendHead(v);}
  v = t->v2(); if (!IS_VISITED2(v)) {MARK_VISIT2(v); sv.appendHead(v);}
  v = t->v3(); if (!IS_VISITED2(v)) {MARK_VISIT2(v); sv.appendHead(v);}
 }
 FOREACHVVVERTEX((&sv), v, n)
  {UNMARK_VISIT2(v); nv=new Vertex(v); V.appendTail(nv); v->info = nv;}
 FOREACHVEEDGE((&se), e, n)
  {UNMARK_VISIT2(e); ne=new Edge((Vertex *)e->v1->info, (Vertex *)e->v2->info); E.appendTail(ne); e->info = ne;}
 FOREACHVTTRIANGLE((&st), t, n)
  {nt=new Triangle((Edge *)t->e1->info,(Edge *)t->e2->info,(Edge *)t->e3->info); T.appendTail(nt); t->info = nt;}
 FOREACHVVVERTEX((&sv), v, n) ((Vertex *)v->info)->e0 = (Edge *)v->e0->info;
 FOREACHVEEDGE((&se), e, n)
  {((Edge *)e->info)->t1 = (e->t1)?((Triangle *)e->t1->info):(NULL); ((Edge *)e->info)->t2 = (e->t2)?((Triangle *)e->t2->info):(NULL);}
 if (!keep_reference)
 {
  FOREACHVVVERTEX((&sv), v, n) v->info = NULL;
  FOREACHVEEDGE((&se), e, n) e->info = NULL;
  FOREACHVTTRIANGLE((&st), t, n) t->info = NULL;
 }
 eulerUpdate();
}
Triangulation::~Triangulation ()
Destructor. Frees the memory allocated for all the mesh elements. Warning! This method uses the freeNodes() method of the class List, which is not guaranteed to work correctly on systems other than Linux (see the documentation of List for details). Assuming that the method works correctly, however, the calling function is responsible of freeing the memory that was possibly allocated for objects pointed to by the 'info' field of mesh elements. Clearly, this must be done before calling the destructor.
Definition at line 195 of file tin.cpp.
References E, List::freeNodes(), T, and V.
{
 T.freeNodes();
 V.freeNodes();
 E.freeNodes();
}
Member Function Documentation
void Triangulation::addNormalNoise (const double p)
Randomly move vertices along their normals. O(N).
Displacement is bounded by 'p'% of the bounding ball radius.
Definition at line 1302 of file tin.cpp.
References FOREACHVERTEX, getBoundingBallRadius(), Vertex::getNormal(), List::numels(), V, Point::x, Point::y, and Point::z.
{
 Vertex *v;
 Node *n;
 Point np;
 int i;
 double noise;
 coord *xyz = (coord *)malloc(sizeof(coord)*V.numels()*3);
 ns *= (getBoundingBallRadius()/100.0);
 i=0; FOREACHVERTEX(v, n)
 {
  noise = ns*(((((double)rand()))-(((double)RAND_MAX)/2.0))/((double)RAND_MAX));
  np = (*v)+((v->getNormal())*noise);
  xyz[i++]=np.x; xyz[i++]=np.y; xyz[i++]=np.z;
 }
 i=0; FOREACHVERTEX(v, n) {v->x=xyz[i++]; v->y=xyz[i++]; v->z=xyz[i++];}
 free(xyz);
}
int Triangulation::append (const char * filename, const bool doupdate = 1)
Append another triangle mesh to the existing one.
This method works exactly as the 'load()' method, except for the fact that it does not assume that the mesh is empty.
Definition at line 183 of file io.cpp.
References d_boundaries, d_handles, d_shells, E, eulerUpdate(), List::joinTailList(), load(), List::numels(), T, and V.
{
 if (!T.numels()) return load(filename, doupdate);
 Triangulation ntin;
 int err = ntin.load(filename, 0);
 if (err) return err;
 V.joinTailList(&(ntin.V));
 E.joinTailList(&(ntin.E));
 T.joinTailList(&(ntin.T));
 if (doupdate) eulerUpdate();
 else d_boundaries = d_handles = d_shells = 1;
 return 0;
}
void Triangulation::append (Triangulation * t)
Append to the current mesh a copy of all the elements of 't'.
The newly created elements form a new selection.
Definition at line 946 of file tin.cpp.
References d_boundaries, d_handles, d_shells, deselectTriangles(), E, invertSelection(), List::joinTailList(), T, and V.
{
 deselectTriangles();
 Triangulation cb(src);
 cb.invertSelection();
 V.joinTailList(&(cb.V));
 E.joinTailList(&(cb.E));
 T.joinTailList(&(cb.T));
 d_boundaries = d_handles = d_shells = 1;
}
double Triangulation::area () const
Total area of the mesh. O(N).
Definition at line 1242 of file tin.cpp.
References Triangle::area(), and FOREACHTRIANGLE.
{
 Triangle *t;
 Node *n;
 double a=0.0;
 FOREACHTRIANGLE(t, n) a += t->area();
 return a;
}
double Triangulation::bboxLongestDiagonal () [inline]
Bounding box longest diagonal. O(N).
Definition at line 449 of file tin.h.
References Point::distance(), and getBoundingBox().
{Point a, b; getBoundingBox(a, b); return a.distance(b);}
int Triangulation::boundaries () [inline]
Get the number of boundary loops of the triangle mesh. O(1) or O(N).
Definition at line 104 of file tin.h.
References d_boundaries, eulerUpdate(), and n_boundaries.
{if (d_boundaries) eulerUpdate(); return n_boundaries;}
int Triangulation::checkAndRepair ()
Definition at line 36 of file checkAndRepair.cpp.
References mergeCoincidentEdges(), printReport(), removeDegenerateTriangles(), and JMesh::warning().
{
 if (mergeCoincidentEdges()) JMesh::warning("Some coincident edges have been merged.\n");
 if (removeDegenerateTriangles()) JMesh::warning("Some edges have been swapped or collapsed to eliminate degenerate triangles.\n");
 printReport();
 return 1;
}
const char * Triangulation::checkConnectivity ()
Definition at line 57 of file checkAndRepair.cpp.
References Edge::commonVertex(), List::containsNode(), Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHEDGE, FOREACHTRIANGLE, FOREACHVEEDGE, FOREACHVERTEX, Triangle::hasEdge(), Edge::hasVertex(), Triangle::nextEdge(), Edge::oppositeVertex(), Edge::t1, Edge::t2, Triangle::v1(), Edge::v1, Triangle::v2(), Edge::v2, Triangle::v3(), and Vertex::VE().
{
 Vertex *v;
 Edge *e,*e2;
 Triangle *t;
 Node *n,*m;
 List *ve;
 FOREACHVERTEX(v, n)
 {
  if (v == NULL) return "checkConnectivity: detected NULL element in V list!";
  if (v->e0 == NULL) return "checkConnectivity: detected NULL e0 pointer for a vertex!";
  if (!v->e0->hasVertex(v)) return "checkConnectivity: detected wrong e0 pointer for a vertex!";
 }
 FOREACHEDGE(e, n)
 {
  if (e == NULL) return "checkConnectivity: detected NULL element in E list!";
  if (e->v1 == NULL || e->v2 == NULL) return "checkConnectivity: detected edge with one or two NULL end-points!";
  if (e->v1 == e->v2) return "checkConnectivity: detected edge with two coincident end-points!";
  if (e->t1 == NULL && e->t2 == NULL) return "checkConnectivity: detected edge with no incident triangles!";
  if (e->t1 != NULL)
  {
   if (!e->t1->hasEdge(e)) return "checkConnectivity: detected wrong t1 triangle at an edge";
   if (e->commonVertex(e->t1->nextEdge(e)) == e->v1)
    return "checkConnectivity: Edge orientation does not match t1 normal";
  }
  if (e->t2 != NULL)
  {
   if (!e->t2->hasEdge(e)) return "checkConnectivity: detected wrong t2 triangle at an edge";
   if (e->commonVertex(e->t2->nextEdge(e)) == e->v2)
    return "checkConnectivity: Edge orientation does not match t2 normal";
  }
 }
 FOREACHTRIANGLE(t, n)
 {
  if (t == NULL) return "checkConnectivity: detected NULL element in T list!";
  if (t->e1 == NULL || t->e2 == NULL || t->e3 == NULL) return "checkConnectivity: detected NULL as a triangle edge!";
  if (t->e1 == t->e2 || t->e1 == t->e3 || t->e2 == t->e3) return "checkConnectivity: detected triangle with two coincident edges!";
  if (t->v1() == NULL || t->v2() == NULL || t->v3() == NULL) return "checkConnectivity: triangle edges do not share vertices!";
  if (t->e1->t1 != t && t->e1->t2 != t) return "checkConnectivity: detected triangle with 1st edge not pointing to the triangle itself!";
  if (t->e2->t1 != t && t->e2->t2 != t) return "checkConnectivity: detected triangle with 2nd edge not pointing to the triangle itself!";
  if (t->e3->t1 != t && t->e3->t2 != t) return "checkConnectivity: detected triangle with 3rd edge not pointing to the triangle itself!";
 }
 FOREACHEDGE(e, n)
 {
  ve = e->v1->VE();
  FOREACHVEEDGE(ve, e2, m)
  {
   if (e2 != e && e2->oppositeVertex(e->v1) == e->v2) return "checkConnectivity: detected duplicate edge!";
  }
  if (ve->containsNode(e) == NULL) return "checkConnectivity: detected non manifold vertex!";
  delete(ve);
  ve = e->v2->VE();
  FOREACHVEEDGE(ve, e2, m)
  {
   if (e2 != e && e2->oppositeVertex(e->v2) == e->v1) return "checkConnectivity: detected duplicate edge!";
  }
  if (ve->containsNode(e) == NULL) return "checkConnectivity: detected non manifold vertex!";
  delete(ve);
 }
 return NULL;
}
Vertex * Triangulation::checkGeometry ()
Definition at line 183 of file checkAndRepair.cpp.
References E, FOREACHEDGE, FOREACHTRIANGLE, Triangle::getAngle(), Triangle::getDAngle(), Vertex::getEdge(), JMesh::info(), jqsort(), lexEdgeCompare(), M_PI, MAX, List::numels(), Edge::t1, Edge::t2, List::toArray(), V, Edge::v1, Triangle::v1(), Triangle::v2(), Triangle::v3(), JMesh::warning(), and xyzCompare().
{
 int i;
 Vertex *ret = NULL;
 double ang, minda = 0;
 Triangle *t;
 Edge *e;
 Vertex **varr = (Vertex **)V.toArray();
 Edge **evarr;
 Vertex *v1, *v2;
 Node *n;
 if (varr == NULL) JMesh::warning("checkGeometry: Not enough memory. Can't check for coincident vertices.\n");
 else
 {
  jqsort((void **)varr, V.numels(), xyzCompare);
  for (i=0; i<(V.numels()-1); i++)
  {
   v1 = ((Vertex *)varr[i]);
   v2 = ((Vertex *)varr[i+1]);
   if ((*v1)==(*v2))
   {
    ret = v1;
    JMesh::warning("checkGeometry: detected coincident vertices.\n");
    if (v1->getEdge(v2))
    {
     JMesh::warning("               and there is an edge connecting them!\n");
     free(varr);
     return v1;
    }
   }
  }
  free(varr);
 }
 evarr = (Edge **)E.toArray();
 if (evarr == NULL) JMesh::warning("checkGeometry: Not enough memory. Can't check for coincident edges.\n");
 else
 {
  jqsort((void **)evarr, E.numels(), lexEdgeCompare);
  for (i=0; i<(E.numels()-1); i++)
  {
   if (!lexEdgeCompare(evarr[i], evarr[i+1]))
   {
    ret = ((Edge *)evarr[i])->v1;
    JMesh::warning("checkGeometry: detected coincident edges.\n");
   }
  }
  free(evarr);
 }
 FOREACHTRIANGLE(t, n)
 {
  ang = t->getAngle(t->v1());
  if (ang == 0 || ang == M_PI) {JMesh::warning("checkGeometry: degenerate triangle detected.\n"); return t->v1();}
  ang = t->getAngle(t->v2());
  if (ang == 0 || ang == M_PI) {JMesh::warning("checkGeometry: degenerate triangle detected.\n"); return t->v2();}
  ang = t->getAngle(t->v3());
  if (ang == 0 || ang == M_PI) {JMesh::warning("checkGeometry: degenerate triangle detected.\n"); return t->v3();}
 }
 ang = minda = 0;
 FOREACHEDGE(e, n)
  if (e->t1 != NULL && e->t2 != NULL && (ang = e->t1->getDAngle(e->t2)) == M_PI)
   {JMesh::warning("checkGeometry: overlapping triangles detected.\n"); return e->v1;}
  else minda = MAX(minda,ang);
 JMesh::info("checkGeometry: minimum dihedral angle = %f (%f DEGs)\n", M_PI-minda, ((M_PI-minda)*360)/(2*M_PI));
 return ret;
}
void Triangulation::closeLoadingSession (FILE * fp, int loaded_faces, ExtVertex ** var, bool triangulate) [protected]
Definition at line 284 of file io.cpp.
References cutAndStitch(), d_boundaries, d_handles, d_shells, duplicateNonManifoldVertices(), forceNormalConsistence(), JMesh::info(), List::numels(), removeDuplicatedTriangles(), removeVertices(), V, and JMesh::warning().
{
 int i, nv = V.numels();
 fclose(fp);
 if (var != NULL)
 {
  for (i=0; i<nv; i++) delete(var[i]);
  free(var);
 }
 if (loaded_faces)
 {
  JMesh::info("Loaded %d vertices and %d faces.\n",nv,loaded_faces);
  if (triangulate) JMesh::warning("Some polygonal faces needed to be triangulated.\n");
  if ((i=removeVertices())) JMesh::warning("%d isolated vertices have been removed.\n",i);
  if (cutAndStitch()) JMesh::warning("Some cuts were necessary to load non manifold configuration.\n");
  if (forceNormalConsistence()) JMesh::warning("Some triangles have been reversed to achieve orientation.\n");
  if ((i=duplicateNonManifoldVertices())) JMesh::warning("%d non-manifold vertices have been duplicated.\n",i);
  if ((i=removeDuplicatedTriangles())) JMesh::warning("%d vertices have been added to split double-triangles.\n",i);
 }
 d_boundaries = d_handles = d_shells = 1;
}
void Triangulation::coordBackApproximation () [protected]
Definition at line 314 of file io.cpp.
References FOREACHVERTEX, Point::x, Point::y, and Point::z.
{
 Node *n;
 Vertex *v;
 char floatver[32];
 float x;
 FOREACHVERTEX(v, n)
 {
  sprintf(floatver,"%f",v->x); sscanf(floatver,"%f",&x); v->x = x;
  sprintf(floatver,"%f",v->y); sscanf(floatver,"%f",&x); v->y = x;
  sprintf(floatver,"%f",v->z); sscanf(floatver,"%f",&x); v->z = x;
 }
}
Edge * Triangulation::CreateEdge (Vertex * v1, Vertex * v2)
Creates an Edge connecting two existing mesh vertices.
Returns the newly created edge. If an edge connecting the two vertices already exists in the mesh, then no new edge is created and the old one is returned.
Definition at line 212 of file tin.cpp.
References List::appendHead(), E, Vertex::e0, and Vertex::getEdge().
{
 Edge *e;
 if ((e = v1->getEdge(v2)) != NULL) return e;
 e = new Edge(v1,v2);
 v1->e0 = e;
 v2->e0 = e;
 E.appendHead(e);
 return e;
}
Edge * Triangulation::CreateEdge (ExtVertex * v1, ExtVertex * v2, const bool check = 1)
Creates an Edge connecting two existing mesh Extended vertices.
Returns the newly created edge. If an edge connecting the two vertices already exists in the mesh, then no new edge is created and the old one is returned. If 'check' is FALSE, the check for previously existing edges is skipped.
Definition at line 229 of file tin.cpp.
References List::appendHead(), E, Vertex::e0, FOREACHVEEDGE, Edge::oppositeVertex(), ExtVertex::v, and ExtVertex::VE.
{
 Edge *e;
 Node *n;
 if (check)
  FOREACHVEEDGE((&(v1->VE)), e, n)
   if (e->oppositeVertex(v1->v) == v2->v) return e;
 e = new Edge(v1->v,v2->v);
 if (v1->v->e0 == NULL) v1->v->e0 = e;
 if (v2->v->e0 == NULL) v2->v->e0 = e;
 v1->VE.appendHead(e);
 v2->VE.appendHead(e);
 E.appendHead(e);
 return e;
}
bool Triangulation::CreateIndexedTriangle (ExtVertex ** var, int i1, int i2, int i3)
Definition at line 241 of file io.cpp.
References CreateEdge(), CreateUnorientedTriangle(), E, Vertex::e0, List::freeNode(), IS_VISITED, MARK_VISIT, List::removeNode(), Edge::t1, Edge::t2, ExtVertex::v, and ExtVertex::VE.
{
 Edge *e1, *e2, *e3;
 e1 = CreateEdge(var[i1],var[i2]); if (IS_VISITED(e1) || (e1->t1 != NULL && e1->t2 != NULL)) MARK_VISIT(e1);
 e2 = CreateEdge(var[i2],var[i3]); if (IS_VISITED(e2) || (e2->t1 != NULL && e2->t2 != NULL)) MARK_VISIT(e2);
 e3 = CreateEdge(var[i3],var[i1]); if (IS_VISITED(e3) || (e3->t1 != NULL && e3->t2 != NULL)) MARK_VISIT(e3);
 if (IS_VISITED(e1)) {e1 = CreateEdge(var[i1],var[i2],0); MARK_VISIT(e1);}
 if (IS_VISITED(e2)) {e2 = CreateEdge(var[i2],var[i3],0); MARK_VISIT(e2);}
 if (IS_VISITED(e3)) {e3 = CreateEdge(var[i3],var[i1],0); MARK_VISIT(e3);}
 if (CreateUnorientedTriangle(e1,e2,e3) == NULL)
 {
  if (e3->t1 == NULL && e3->t2 == NULL)
  {
   E.freeNode(e3);
   var[i3]->VE.removeNode(e3); var[i1]->VE.removeNode(e3);
   if (var[i3]->v->e0 == e3) var[i3]->v->e0 = NULL;
   if (var[i1]->v->e0 == e3) var[i1]->v->e0 = NULL;
  }
  if (e2->t1 == NULL && e2->t2 == NULL)
  {
   E.freeNode(e2);
   var[i2]->VE.removeNode(e2); var[i3]->VE.removeNode(e2);
   if (var[i2]->v->e0 == e2) var[i2]->v->e0 = NULL;
   if (var[i3]->v->e0 == e2) var[i3]->v->e0 = NULL;
  }
  if (e1->t1 == NULL && e1->t2 == NULL)
  {
   E.freeNode(e1);
   var[i1]->VE.removeNode(e1); var[i2]->VE.removeNode(e1);
   if (var[i1]->v->e0 == e1) var[i1]->v->e0 = NULL;
   if (var[i2]->v->e0 == e1) var[i2]->v->e0 = NULL;
  }
  return 0;
 }
 return 1;
}
Triangulation * Triangulation::createSubMeshFromSelection (Triangle * t0 = NULL, bool keep_ref = 0)
Creates a new Triangulation out of an existing selection containing 't0'. O(output).
If necessary, non-manifold vertices are properly duplicated. If 'keep_ref' is set to TRUE, then elements of the original mesh point (through their info field) to corresponding elements of the newly created copy.
Definition at line 638 of file tin.cpp.
References List::appendHead(), List::appendTail(), duplicateNonManifoldVertices(), E, Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, eulerUpdate(), FOREACHEDGE, FOREACHTRIANGLE, FOREACHVEEDGE, FOREACHVERTEX, FOREACHVTTRIANGLE, FOREACHVVVERTEX, Triangle::info, Edge::info, Point::info, IS_BIT, IS_VISITED, MARK_BIT, List::numels(), List::popHead(), T, Edge::t1, Triangle::t1(), Edge::t2, Triangle::t2(), Triangle::t3(), Triangulation(), UNMARK_BIT, V, Edge::v1, Triangle::v1(), Edge::v2, Triangle::v2(), and Triangle::v3().
{
 Triangle *t,*s, *nt;
 Node *n;
 if (t0 != NULL && !IS_VISITED(t0)) return NULL;
 Triangulation *tin = new Triangulation;
 Vertex *v,*nv;
 Edge *e, *ne;
 List triList, sT, sE, sV;
 if (t0 != NULL)
 {
  triList.appendHead(t0); MARK_BIT(t0,3);
  while(triList.numels())
  {
   t = (Triangle *)triList.popHead();
   sT.appendHead(t);
   if (!IS_BIT(t->e1, 3)) {sE.appendHead(t->e1); MARK_BIT(t->e1, 3);}
   if (!IS_BIT(t->e2, 3)) {sE.appendHead(t->e2); MARK_BIT(t->e2, 3);}
   if (!IS_BIT(t->e3, 3)) {sE.appendHead(t->e3); MARK_BIT(t->e3, 3);}
   if ((v=t->v1()) && !IS_BIT(v, 3)) {sV.appendHead(v); MARK_BIT(v, 3);}
   if ((v=t->v2()) && !IS_BIT(v, 3)) {sV.appendHead(v); MARK_BIT(v, 3);}
   if ((v=t->v3()) && !IS_BIT(v, 3)) {sV.appendHead(v); MARK_BIT(v, 3);}
   if ((s = t->t1()) != NULL && !IS_BIT(s,3) && IS_VISITED(s)) {triList.appendHead(s); MARK_BIT(s,3);}
   if ((s = t->t2()) != NULL && !IS_BIT(s,3) && IS_VISITED(s)) {triList.appendHead(s); MARK_BIT(s,3);}
   if ((s = t->t3()) != NULL && !IS_BIT(s,3) && IS_VISITED(s)) {triList.appendHead(s); MARK_BIT(s,3);}
  }
 }
 else
 {
  FOREACHTRIANGLE(t, n) if (IS_VISITED(t))
   {sT.appendHead(t); MARK_BIT(t->e1, 3); MARK_BIT(t->e2, 3); MARK_BIT(t->e3, 3);}
  FOREACHEDGE(e, n) if (IS_BIT(e,3))
   {sE.appendHead(e); MARK_BIT(e->v1, 3); MARK_BIT(e->v2, 3);}
  FOREACHVERTEX(v, n) if (IS_BIT(v,3)) sV.appendHead(v);
 }
 FOREACHVEEDGE((&sE), e, n) e->v1->e0 = e->v2->e0 = e;
 int i;
 void **v_info = NULL, **e_info = NULL, **t_info = NULL;
 if (!keep_ref)
 {
  v_info = new void *[sV.numels()];
  i=0; FOREACHVVVERTEX((&sV), v, n) v_info[i++] = v->info;
  e_info = new void *[sE.numels()];
  i=0; FOREACHVEEDGE((&sE), e, n) e_info[i++] = e->info;
  t_info = new void *[sT.numels()];
  i=0; FOREACHVTTRIANGLE((&sT), t, n) t_info[i++] = t->info;
 }
 FOREACHVVVERTEX((&sV), v, n)
  {nv=new Vertex(v); tin->V.appendTail(nv); v->info = nv;}
 FOREACHVEEDGE((&sE), e, n)
  {ne=new Edge((Vertex *)e->v1->info, (Vertex *)e->v2->info); tin->E.appendTail(ne); e->info = ne;}
 FOREACHVTTRIANGLE((&sT), t, n)
  {nt=new Triangle((Edge *)t->e1->info,(Edge *)t->e2->info,(Edge *)t->e3->info); tin->T.appendTail(nt); t->info = nt; nt->info = t;}
 FOREACHVVVERTEX((&sV), v, n) ((Vertex *)v->info)->e0 = (Edge *)v->e0->info;
 FOREACHVEEDGE((&sE), e, n)
 {
  ((Edge *)e->info)->t1 = (e->t1 && IS_VISITED(e->t1))?((Triangle *)e->t1->info):(NULL);
  ((Edge *)e->info)->t2 = (e->t2 && IS_VISITED(e->t2))?((Triangle *)e->t2->info):(NULL);
 }
 i=0; if (!keep_ref) FOREACHVVVERTEX((&sV), v, n) v->info = v_info[i++];
 i=0; if (!keep_ref) FOREACHVEEDGE((&sE), e, n) e->info = e_info[i++];
 i=0; if (!keep_ref) FOREACHVTTRIANGLE((&sT), t, n) t->info = t_info[i++];
 FOREACHVTTRIANGLE((&sT), t, n) UNMARK_BIT(t, 3);
 FOREACHVEEDGE((&sE), e, n) UNMARK_BIT(e, 3);
 FOREACHVVVERTEX((&sV), v, n) UNMARK_BIT(v, 3);
 if (!sT.numels()) {delete(tin); return NULL;}
 tin->duplicateNonManifoldVertices();
 tin->eulerUpdate();
 return tin;
}
Triangle * Triangulation::CreateTriangle (Edge * e1, Edge * e2, Edge * e3)
Creates a properly oriented Triangle bounded by three existing mesh edges.
Returns the newly created Triangle. If e1, e2 and e3 are not suitable for creating a properly oriented and manifold triangle, the creation fails and NULL is returned.
Definition at line 251 of file tin.cpp.
References List::appendHead(), Edge::commonVertex(), d_boundaries, d_handles, d_shells, T, Edge::t1, Edge::t2, Edge::v1, and Edge::v2.
{
 Triangle *tt, **at1, **at2, **at3;
 if (e1->commonVertex(e2) == e1->v2 && e1->t1 == NULL) at1 = &(e1->t1);
 else if (e1->commonVertex(e2) == e1->v1 && e1->t2 == NULL) at1 = &(e1->t2);
 else return NULL;
 if (e2->commonVertex(e3) == e2->v2 && e2->t1 == NULL) at2 = &(e2->t1);
 else if (e2->commonVertex(e3) == e2->v1 && e2->t2 == NULL) at2 = &(e2->t2);
 else return NULL;
 if (e3->commonVertex(e1) == e3->v2 && e3->t1 == NULL) at3 = &(e3->t1);
 else if (e3->commonVertex(e1) == e3->v1 && e3->t2 == NULL) at3 = &(e3->t2);
 else return NULL;
 tt = new Triangle(e1,e2,e3);
 *at1 = *at2 = *at3 = tt;
 T.appendHead(tt);
 d_boundaries = d_handles = d_shells = 1;
 return tt;
}
Triangle * Triangulation::CreateUnorientedTriangle (Edge * e1, Edge * e2, Edge * e3)
Creates an arbitrarily oriented Triangle bounded by three existing mesh edges.
Returns the newly created Triangle. If either e1, e2 or e3 has already two incident triangles, the creation fails and NULL is returned. This method assumes that e1, e2 and e3 are incident to exactly three vertices.
Definition at line 277 of file tin.cpp.
References List::appendHead(), T, Edge::t1, and Edge::t2.
{
 Triangle *tt, **at1, **at2, **at3;
 if (e1->t1 == NULL) at1 = &(e1->t1);
 else if (e1->t2 == NULL) at1 = &(e1->t2);
 else return NULL;
 if (e2->t1 == NULL) at2 = &(e2->t1);
 else if (e2->t2 == NULL) at2 = &(e2->t2);
 else return NULL;
 if (e3->t1 == NULL) at3 = &(e3->t1);
 else if (e3->t2 == NULL) at3 = &(e3->t2);
 else return NULL;
 tt = new Triangle(e1,e2,e3);
 *at1 = *at2 = *at3 = tt;
 T.appendHead(tt);
 return tt;
}
int Triangulation::cutAndStitch ()
Convert to manifold.
Definition at line 830 of file io.cpp.
References List::appendHead(), d_boundaries, d_handles, d_shells, E, FOREACHEDGE, FOREACHVEEDGE, IS_VISITED, List::numels(), removeEdges(), Triangle::replaceEdge(), Edge::stitch(), Edge::t1, Edge::t2, UNMARK_VISIT, Edge::v1, and Edge::v2.
{
 Edge *e1, *e2;
 Node *n;
 List cut;
 int i;
 FOREACHEDGE(e1, n) if (IS_VISITED(e1))
 {
  if (e1->t1 != NULL && e1->t2 != NULL)
  {
   e2 = new Edge(e1->v2, e1->v1);
   E.appendHead(e2);
   e1->t2->replaceEdge(e1, e2);
   e2->t2 = e1->t2; e1->t2 = NULL;
  }
  cut.appendHead(e1);
  UNMARK_VISIT(e1);
 }
 do
 {
  i=0;
  FOREACHVEEDGE((&cut), e1, n) if (e1->v1!=NULL) i += e1->stitch();
 } while (i);
 removeEdges();
 d_boundaries = d_handles = d_shells = 1;
 return cut.numels();
}
int Triangulation::deselectConnectedComponent (Triangle * t0, bool stop_on_sharp = 0)
Deselects all the triangles of the connected component containing t0. O(N).
If 'stop_on_sharp', expansion from 't0' brakes at tagged sharp edges. Returns the number of deselected triangles.
Definition at line 917 of file tin.cpp.
References List::appendHead(), Triangle::e1, Triangle::e2, Triangle::e3, IS_SHARPEDGE, IS_VISITED, List::numels(), List::popHead(), Triangle::t1(), Triangle::t2(), Triangle::t3(), and UNMARK_VISIT.
{
 List todo;
 Triangle *t, *t1, *t2, *t3;
 int ns = 0;
 todo.appendHead(t0);
 while (todo.numels())
 {
  t = (Triangle *)todo.popHead();
  if (IS_VISITED(t))
  {
   t1 = t->t1(); t2 = t->t2(); t3 = t->t3();
   if (t1 != NULL && IS_VISITED(t1) && (!(sos && IS_SHARPEDGE(t->e1)))) todo.appendHead(t1);
   if (t2 != NULL && IS_VISITED(t2) && (!(sos && IS_SHARPEDGE(t->e2)))) todo.appendHead(t2);
   if (t3 != NULL && IS_VISITED(t3) && (!(sos && IS_SHARPEDGE(t->e3)))) todo.appendHead(t3);
   UNMARK_VISIT(t); ns++;
  }
 }
 return ns;
}
int Triangulation::deselectSphericalRegion (Triangle * t0, const double L, const Point * p)
Marks all the triangles within distance L from 'p' as deselected. O(output).
A triangle is considered to be within distance L from 'p' only if all its three vertices are so. Point 'p' is assumed to belong to triangle 't0', which is required to limit the complexity to the size of the selected region. Returns the number of deselected triangles.
Definition at line 743 of file tin.cpp.
References FOREACHVTTRIANGLE, getRegion(), and UNMARK_VISIT.
{
 List *reg = getRegion(t, L, center);
 Node *n;
 Triangle *s;
 int nt=0;
 FOREACHVTTRIANGLE(reg, s, n) {UNMARK_VISIT(s); nt++;}
 delete(reg);
 return nt;
}
void Triangulation::deselectTriangles ()
Deselects all the triangles. O(N).
Definition at line 494 of file tin.cpp.
References FOREACHTRIANGLE, and UNMARK_VISIT.
{
 Triangle *t;
 Node *n;
 FOREACHTRIANGLE(t, n) UNMARK_VISIT(t);
}
int Triangulation::duplicateNonManifoldVertices ()
Definition at line 135 of file checkAndRepair.cpp.
References List::appendHead(), List::containsNode(), d_boundaries, d_handles, d_shells, Vertex::e0, FOREACHEDGE, FOREACHVEEDGE, Edge::replaceVertex(), V, Edge::v1, Edge::v2, and Vertex::VE().
{
 Vertex *v;
 Edge *e, *f;
 Node *n, *m;
 List *ve;
 int dv = 0;
 FOREACHEDGE(e, n)
 {
  ve = e->v1->VE();
  if (ve->containsNode(e) == NULL)
  {
   V.appendHead(v = new Vertex(e->v1));
   FOREACHVEEDGE(ve, f, m) f->replaceVertex(e->v1, v);
   v->e0 = e->v1->e0;
   e->v1->e0 = e;
   dv++;
  }
  delete(ve);
 }
 FOREACHEDGE(e, n)
 {
  ve = e->v2->VE();
  if (ve->containsNode(e) == NULL)
  {
   V.appendHead(v = new Vertex(e->v2));
   FOREACHVEEDGE(ve, f, m) f->replaceVertex(e->v2, v);
   v->e0 = e->v2->e0;
   e->v2->e0 = e;
   dv++;
  }
  delete(ve);
 }
 if (dv) d_boundaries = d_handles = d_shells = 1;
 return dv;
}
Triangle * Triangulation::EulerEdgeTriangle (Edge * e1, Edge * e2)
Creates a new Edge 'e' and an oriented Triangle bounded by 'e', 'e1' and 'e2'.
The newly created triangle is returned, unless 'e1' and 'e2' do not share a vertex or they are not boundary edges. In this cases, NULL is returned.
Definition at line 301 of file tin.cpp.
References Edge::commonVertex(), CreateEdge(), CreateTriangle(), Edge::hasVertex(), Edge::isOnBoundary(), Triangle::nextEdge(), Edge::oppositeVertex(), Edge::t1, and Edge::t2.
{
 Vertex *cv = e2->commonVertex(e3);
 Triangle *adj = (e2->t1 == NULL)?(e2->t2):(e2->t1);
 if (cv == NULL || !e2->isOnBoundary() || !e3->isOnBoundary()) return NULL;
 Edge *e1 = CreateEdge(e2->oppositeVertex(cv), e3->oppositeVertex(cv));
 if (adj->nextEdge(e2)->hasVertex(cv)) return CreateTriangle(e1,e3,e2);
 return CreateTriangle(e1,e2,e3);
}
void Triangulation::eulerUpdate ()
Updates the values of n_boundaries, n_handles and n_shells. O(N).
The relative dirty bits are set to zero.
Definition at line 1509 of file tin.cpp.
References List::appendHead(), d_boundaries, d_handles, d_shells, E, FOREACHEDGE, FOREACHTRIANGLE, FOREACHVERTEX, IS_BIT, Edge::isOnBoundary(), MARK_BIT, n_boundaries, n_handles, n_shells, Vertex::nextOnBoundary(), List::numels(), List::popHead(), T, Triangle::t1(), Triangle::t2(), Triangle::t3(), UNMARK_BIT, V, Edge::v1, and Edge::v2.
{
 Vertex *v,*w;
 Edge *e;
 Triangle *t,*s;
 List triList;
 Node *n;
 n_boundaries = n_shells = n_handles = 0;
 FOREACHTRIANGLE(t, n) if (!IS_BIT(t, 3))
 {
  n_shells++;
  triList.appendHead(t);
  MARK_BIT(t,3);
  while(triList.numels())
  {
   t = (Triangle *)triList.popHead();
   if ((s = t->t1()) != NULL && !IS_BIT(s,3)) {triList.appendHead(s); MARK_BIT(s,3);}
   if ((s = t->t2()) != NULL && !IS_BIT(s,3)) {triList.appendHead(s); MARK_BIT(s,3);}
   if ((s = t->t3()) != NULL && !IS_BIT(s,3)) {triList.appendHead(s); MARK_BIT(s,3);}
  }
 }
 FOREACHTRIANGLE(t, n) UNMARK_BIT(t, 3);
 FOREACHEDGE(e, n) if (e->isOnBoundary())
  {MARK_BIT(e->v1, 3); MARK_BIT(e->v2, 3);}
 FOREACHVERTEX(v, n) if (IS_BIT(v,3))
 {
  n_boundaries++;
  for (w=v; IS_BIT(w, 3); w = w->nextOnBoundary()) UNMARK_BIT(w, 3);
 }
 n_handles = (E.numels() - V.numels() - T.numels() + 2*n_shells - n_boundaries)/2;
 d_boundaries = d_handles = d_shells = 0;
}
void Triangulation::flipNormals (Triangle * t0)
Invert the orientation of triangles and edges belonging to the shell containing 't0'. O(S).
Definition at line 1413 of file tin.cpp.
References List::appendHead(), Triangle::e1, Triangle::e2, Triangle::e3, Triangle::invert(), IS_BIT, MARK_BIT, List::numels(), p_swap(), List::popHead(), Triangle::t1(), Triangle::t2(), Triangle::t3(), UNMARK_BIT, Edge::v1, and Edge::v2.
{
 List todo;
 Triangle *t, *t1, *t2, *t3;
 todo.appendHead(t0);
 while (todo.numels())
 {
  t = (Triangle *)todo.popHead();
  if (!IS_BIT(t,2))
  {
   t1 = t->t1(); t2 = t->t2(); t3 = t->t3();
   if (t1 != NULL && !IS_BIT(t1,2)) todo.appendHead(t1);
   if (t2 != NULL && !IS_BIT(t2,2)) todo.appendHead(t2);
   if (t3 != NULL && !IS_BIT(t3,2)) todo.appendHead(t3);
   t->invert();
   if (!IS_BIT(t->e1,2)) p_swap((void **)(&(t->e1->v1)), (void **)(&(t->e1->v2)));
   if (!IS_BIT(t->e2,2)) p_swap((void **)(&(t->e2->v1)), (void **)(&(t->e2->v2)));
   if (!IS_BIT(t->e3,2)) p_swap((void **)(&(t->e3->v1)), (void **)(&(t->e3->v2)));
   MARK_BIT(t->e1,2); MARK_BIT(t->e2,2); MARK_BIT(t->e3,2);
   MARK_BIT(t,2);
  }
 }
 todo.appendHead(t0);
 while (todo.numels())
 {
  t = (Triangle *)todo.popHead();
  if (IS_BIT(t,2))
  {
   t1 = t->t1(); t2 = t->t2(); t3 = t->t3();
   if (t1 != NULL && IS_BIT(t1,2)) todo.appendHead(t1);
   if (t2 != NULL && IS_BIT(t2,2)) todo.appendHead(t2);
   if (t3 != NULL && IS_BIT(t3,2)) todo.appendHead(t3);
   UNMARK_BIT(t->e1,2); UNMARK_BIT(t->e2,2); UNMARK_BIT(t->e3,2);
   UNMARK_BIT(t,2);
  }
 }
}
void Triangulation::flipNormals ()
Invert all the triangle and edge orientations. O(N).
Definition at line 1400 of file tin.cpp.
References FOREACHEDGE, FOREACHTRIANGLE, Triangle::invert(), p_swap(), Edge::v1, and Edge::v2.
{
 Node *n;
 Edge *e;
 Triangle *t;
 FOREACHTRIANGLE(t, n) t->invert();
 FOREACHEDGE(e, n) p_swap((void **)(&(e->v1)), (void **)(&(e->v2)));
}
int Triangulation::forceNormalConsistence ()
Definition at line 488 of file checkAndRepair.cpp.
References FOREACHTRIANGLE, IS_VISITED2, and UNMARK_VISIT2.
{
 int ret = 0;
 Node *n;
 Triangle *t;
 FOREACHTRIANGLE(t, n) if (!IS_VISITED2(t))
  ret |= forceNormalConsistence(t);
 FOREACHTRIANGLE(t, n) UNMARK_VISIT2(t);
 return ret;
}
int Triangulation::forceNormalConsistence (Triangle * t0)
Definition at line 500 of file checkAndRepair.cpp.
References List::appendHead(), Triangle::checkAdjNor(), Edge::commonVertex(), d_boundaries, d_handles, d_shells, Node::data, E, Triangle::e1, Triangle::e2, Triangle::e3, flipNormals(), FOREACHVEEDGE, Triangle::getNormal(), List::head(), Triangle::invert(), IS_VISITED2, Edge::isOnBoundary(), MARK_VISIT2, Triangle::nextEdge(), List::numels(), p_swap(), List::removeCell(), Triangle::replaceEdge(), Edge::t1, Triangle::t1(), Edge::t2, Triangle::t2(), Triangle::t3(), topTriangle(), UNMARK_VISIT2, Edge::v1, Edge::v2, JMesh::warning(), and Point::z.
{
 Node *n;
 Edge *e;
 List todo, elist;
 Triangle *t, *t1, *t2, *t3;
 int tmp1, tmp2, r=0, wrn = 0, isclosed = 1;
 todo.appendHead(t0);
 while (todo.numels())
 {
  t = (Triangle *)todo.head()->data;
  todo.removeCell(todo.head());
  if (!IS_VISITED2(t))
  {
   t1 = t->t1(); t2 = t->t2(); t3 = t->t3();
   if (!IS_VISITED2(t->e1)) {MARK_VISIT2(t->e1); elist.appendHead(t->e1);}
   if (!IS_VISITED2(t->e2)) {MARK_VISIT2(t->e2); elist.appendHead(t->e2);}
   if (!IS_VISITED2(t->e3)) {MARK_VISIT2(t->e3); elist.appendHead(t->e3);}
   if (t1 != NULL && !IS_VISITED2(t1)) {todo.appendHead(t1); if (!t->checkAdjNor(t1)) {t1->invert(); r=1;}}
   if (t2 != NULL && !IS_VISITED2(t2)) {todo.appendHead(t2); if (!t->checkAdjNor(t2)) {t2->invert(); r=1;}}
   if (t3 != NULL && !IS_VISITED2(t3)) {todo.appendHead(t3); if (!t->checkAdjNor(t3)) {t3->invert(); r=1;}}
   MARK_VISIT2(t);
  }
 }
 FOREACHVEEDGE((&(elist)), e, n)
 {
  UNMARK_VISIT2(e);
  if (isclosed && e->isOnBoundary()) isclosed = 0;
  tmp1 = (e->t1 != NULL)?((e->commonVertex(e->t1->nextEdge(e)) == e->v1)?(-1):(1)):(0);
  tmp2 = (e->t2 != NULL)?((e->commonVertex(e->t2->nextEdge(e)) == e->v2)?(-1):(1)):(0);
  if (tmp1*tmp2 < 0)
  {
   wrn++;
   if (tmp1 == -1) p_swap((void **)(&(e->v1)), (void **)(&(e->v2)));
   Edge *ne = new Edge(e->v2, e->v1);
   E.appendHead(ne);
   e->t2->replaceEdge(e, ne);
   ne->t2 = e->t2; e->t2 = NULL;
  } else if (tmp1 == -1 || tmp2 == -1) p_swap((void **)(&(e->v1)), (void **)(&(e->v2)));
 }
 if (wrn)
 {
  d_boundaries = d_handles = d_shells = 1;
  JMesh::warning("forceNormalConsistence: Triangulation was not orientable. Cut performed.\n");
 }
 if (isclosed)
 {
  t = topTriangle(t0);
  if (t->getNormal().z < 0) {flipNormals(t0); r=1;}
 }
 return r;
}
double Triangulation::getBoundingBallRadius () const
Approximate bounding ball radius. O(N).
Definition at line 1220 of file tin.cpp.
References FOREACHVERTEX, getBoundingBox(), and Point::normalize().
{
 Vertex *v; Node *n;
 Point tc, mp, Mp;
 double tb, bsr = getBoundingBox(mp, Mp)/2;
 Point bsc = (Mp+mp)/2;
 FOREACHVERTEX(v, n)
  if ((tb = ((*v)-bsc).length()) > bsr)
  {
   tc = ((*v)-bsc); tc.normalize();
   tb = ((tb-bsr)/2);
   bsc = bsc+(tc*tb);
   bsr += tb;
  }
 return bsr;
}
double Triangulation::getBoundingBox (Point & b, Point & t) const
Bounding box longest edge. 'b' and 't' are set as the longest diagonal end-points. O(N).
Definition at line 1198 of file tin.cpp.
References FOREACHVERTEX, MAX, Point::x, Point::y, and Point::z.
{
 Vertex *v; Node *n;
 Mp.x = -DBL_MAX, mp.x = DBL_MAX;
 Mp.y = -DBL_MAX, mp.y = DBL_MAX;
 Mp.z = -DBL_MAX, mp.z = DBL_MAX;
 FOREACHVERTEX(v, n)
 {
  if (v->x < mp.x) mp.x = v->x;
  if (v->x > Mp.x) Mp.x = v->x;
  if (v->y < mp.y) mp.y = v->y;
  if (v->y > Mp.y) Mp.y = v->y;
  if (v->z < mp.z) mp.z = v->z;
  if (v->z > Mp.z) Mp.z = v->z;
 }
 return MAX(Mp.x-mp.x,MAX(Mp.y-mp.y,Mp.z-mp.z));
}
List * Triangulation::getRegion (Triangle * t0, const double L, const Point * p)
Make a list of triangles within distance L from 'p'. O(output).
Starting from 't0', which is assumed to contain 'p', add a triangle at a time to the list as long as all the vertices stay within distance L from 'p'.
Definition at line 965 of file tin.cpp.
References List::appendHead(), Node::data, Point::distance(), Triangle::e1, Triangle::e2, Triangle::e3, FOREACHVTTRIANGLE, List::head(), IS_BIT, MARK_BIT, List::numels(), Triangle::oppositeVertex(), List::removeCell(), Triangle::t1(), Triangle::t2(), Triangle::t3(), UNMARK_BIT, Triangle::v1(), Triangle::v2(), and Triangle::v3().
{
 List triList, *toRemove = new List;
 if (t->v1()->distance(center) > L) return toRemove;
 if (t->v2()->distance(center) > L) return toRemove;
 if (t->v3()->distance(center) > L) return toRemove;
 Triangle *s;
 Node *n;
 triList.appendHead(t);
 MARK_BIT(t,3);
 while(triList.numels() > 0)
 {
  t = (Triangle *)triList.head()->data;
  triList.removeCell(triList.head());
  toRemove->appendHead(t);
  if ((s = t->t1()) != NULL && !IS_BIT(s,3) && s->oppositeVertex(t->e1)->distance(center) <= L)
   {triList.appendHead(s); MARK_BIT(s,3);}
  if ((s = t->t2()) != NULL && !IS_BIT(s,3) && s->oppositeVertex(t->e2)->distance(center) <= L)
   {triList.appendHead(s); MARK_BIT(s,3);}
  if ((s = t->t3()) != NULL && !IS_BIT(s,3) && s->oppositeVertex(t->e3)->distance(center) <= L)
   {triList.appendHead(s); MARK_BIT(s,3);}
 }
 FOREACHVTTRIANGLE(toRemove, s, n) UNMARK_BIT(s, 3);
 return toRemove;
}
List * Triangulation::getRegionInternalVertices (List * l)
Retrieve internal vertices of a region. O(l->numels()).
This method returns a list containing an edge of the region's boundary as its first element, and all the internal vertices as the remaining elements.
Definition at line 1058 of file tin.cpp.
References List::appendHead(), Triangle::e1, Triangle::e2, Triangle::e3, FOREACHVTTRIANGLE, IS_BIT, IS_VISITED, MARK_BIT, MARK_VISIT, Triangle::t1(), Triangle::t2(), Triangle::t3(), UNMARK_BIT, Triangle::v1(), Edge::v1, Triangle::v2(), Edge::v2, and Triangle::v3().
{
 List *iVertices = new List;
 List *outList = new List;
 Edge *bEdge = NULL;
 Triangle *s, *t;
 Node *n;
 Vertex *v1, *v2, *v3;
 FOREACHVTTRIANGLE(reg, t, n) {MARK_VISIT(t); MARK_BIT(t, 3);}
 FOREACHVTTRIANGLE(reg, t, n)
 {
  if (IS_BIT(t,3))
  {
   UNMARK_BIT(t,3);
   if ((s = t->t1()) != NULL && !IS_VISITED(s)) {bEdge = t->e1; MARK_BIT(t->e1->v1, 3); MARK_BIT(t->e1->v2, 3);}
   if ((s = t->t2()) != NULL && !IS_VISITED(s)) {bEdge = t->e2; MARK_BIT(t->e2->v1, 3); MARK_BIT(t->e2->v2, 3);}
   if ((s = t->t3()) != NULL && !IS_VISITED(s)) {bEdge = t->e3; MARK_BIT(t->e3->v1, 3); MARK_BIT(t->e3->v2, 3);}
  }
 }
 FOREACHVTTRIANGLE(reg, s, n)
 {
  v1 = s->v1(); v2 = s->v2(); v3 = s->v3();
  if (!IS_BIT(v1, 3)) {iVertices->appendHead(v1); MARK_BIT(v1, 3);}
  if (!IS_BIT(v2, 3)) {iVertices->appendHead(v2); MARK_BIT(v2, 3);}
  if (!IS_BIT(v3, 3)) {iVertices->appendHead(v3); MARK_BIT(v3, 3);}
 }
 FOREACHVTTRIANGLE(reg, s, n)
 {
  v1 = s->v1(); v2 = s->v2(); v3 = s->v3();
  UNMARK_BIT(v1, 3); UNMARK_BIT(v2, 3); UNMARK_BIT(v3, 3);
 }
 outList->appendHead(iVertices);
 outList->appendHead(bEdge);
 return outList;
}
int Triangulation::growSelection ()
Enlarges the current selection of one triangle in width. O(N).
Each triangle sharing at least one vertex with a currently selected triangle becomes selected. Returns the number of newly selected triangles.
Definition at line 539 of file tin.cpp.
References FOREACHTRIANGLE, FOREACHVERTEX, IS_VISITED, MARK_VISIT, UNMARK_VISIT, Triangle::v1(), Triangle::v2(), and Triangle::v3().
{
 Node *n;
 Vertex *v, *v1, *v2, *v3;
 Triangle *t;
 int ns=0;
 FOREACHTRIANGLE(t, n) if (IS_VISITED(t))
 {
  v1 = t->v1(); v2 = t->v2(); v3 = t->v3();
  MARK_VISIT(v1); MARK_VISIT(v2); MARK_VISIT(v3);
 }
 FOREACHTRIANGLE(t, n) if (!IS_VISITED(t))
 {
  v1 = t->v1(); v2 = t->v2(); v3 = t->v3();
  if (IS_VISITED(v1) || IS_VISITED(v2) || IS_VISITED(v3)) {MARK_VISIT(t); ns++;}
 }
 FOREACHVERTEX(v, n) UNMARK_VISIT(v);
 return ns;
}
int Triangulation::handles () [inline]
Get the number of handles of the triangle mesh. O(1) or O(N).
Definition at line 107 of file tin.h.
References d_handles, eulerUpdate(), and n_handles.
{if (d_handles) eulerUpdate(); return n_handles;}
void Triangulation::invertSelection (Triangle * t0 = NULL)
Inverts the selection status of all the triangles. O(N).
If 't0' is not NULL, then only the connected component containing 't0' is inverted.
Definition at line 588 of file tin.cpp.
References List::appendTail(), FOREACHTRIANGLE, IS_VISITED, MARK_VISIT, List::popHead(), Triangle::t1(), Triangle::t2(), Triangle::t3(), and UNMARK_VISIT.
{
 Node *n;
 Triangle *t;
 if (t0 != NULL)
 {
  List totoggle(t0);
  Triangle *s;
  bool unmark = IS_VISITED(t0);
  if (unmark) UNMARK_VISIT(t0); else MARK_VISIT(t0);
  while ((t = (Triangle *)totoggle.popHead()) != NULL)
  {
   if ((s = t->t1()) != NULL && ((IS_VISITED(s) && unmark) || (!IS_VISITED(s) && !unmark)))
    {if (unmark) UNMARK_VISIT(s); else MARK_VISIT(s); totoggle.appendTail(s);}
   if ((s = t->t2()) != NULL && ((IS_VISITED(s) && unmark) || (!IS_VISITED(s) && !unmark)))
    {if (unmark) UNMARK_VISIT(s); else MARK_VISIT(s); totoggle.appendTail(s);}
   if ((s = t->t3()) != NULL && ((IS_VISITED(s) && unmark) || (!IS_VISITED(s) && !unmark)))
    {if (unmark) UNMARK_VISIT(s); else MARK_VISIT(s); totoggle.appendTail(s);}
  }
 }
 else
 {
  FOREACHTRIANGLE(t, n) if (IS_VISITED(t)) UNMARK_VISIT(t); else MARK_VISIT(t);
 }
}
bool Triangulation::isSelectionSimple (List * l)
TRUE iff the set of selected triangles in 'l' is simply connected. O(l->numels()).
Definition at line 819 of file tin.cpp.
References List::appendHead(), Node::data, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHVEEDGE, FOREACHVTTRIANGLE, List::head(), IS_VISITED, IS_VISITED2, MARK_VISIT, MARK_VISIT2, List::numels(), Edge::oppositeVertex(), List::popHead(), Triangle::t1(), Triangle::t2(), Triangle::t3(), UNMARK_VISIT, UNMARK_VISIT2, Edge::v1, and Vertex::VE().
{
 if (!s->numels()) return 0; // Empty region is not simple
 Node *n;
 Triangle *ta, *t = (Triangle *)s->head()->data;
 List bdr, top(t);
 MARK_VISIT2(t);
 int nv=0;
 while (top.numels())
 {
  t = (Triangle *)top.popHead();
  nv++;
  ta=t->t1(); if (ta && IS_VISITED(ta) && !IS_VISITED2(ta)) {MARK_VISIT2(ta); top.appendHead(ta);}
  else if (ta == NULL) break; else if (!IS_VISITED(ta)) bdr.appendHead(t->e1);
  ta=t->t2(); if (ta && IS_VISITED(ta) && !IS_VISITED2(ta)) {MARK_VISIT2(ta); top.appendHead(ta);}
  else if (ta == NULL) break; else if (!IS_VISITED(ta)) bdr.appendHead(t->e2);
  ta=t->t3(); if (ta && IS_VISITED(ta) && !IS_VISITED2(ta)) {MARK_VISIT2(ta); top.appendHead(ta);}
  else if (ta == NULL) break; else if (!IS_VISITED(ta)) bdr.appendHead(t->e3);
 }
 FOREACHVTTRIANGLE(s, t, n) UNMARK_VISIT2(t);
 if (top.numels()) return 0; // Mesh-boundary in selection
 if (nv != s->numels()) return 0; // Disconnected selection
 Edge *e, *f, *ge=NULL, *e0;
 List *ve;
 FOREACHVEEDGE((&(bdr)), e, n) MARK_VISIT(e);
 int nae;
 nv = 0;
 e = e0 = (Edge *)bdr.head()->data;
 Vertex *v = e->v1;
 do
 {
  nv++;
  v = e->oppositeVertex(v);
  ve = v->VE();
  nae=0; FOREACHVEEDGE(ve, f, n) if (f!=e && IS_VISITED(f)) {ge=f; nae++;}
  delete(ve);
  if (nae > 1) break;
  e=ge;
 } while (e != e0);
 FOREACHVEEDGE((&(bdr)), e, n) UNMARK_VISIT(e);
 if (nv != bdr.numels()) return 0; // Non-simple selection
 return 1;
}
bool Triangulation::iterativeEdgeSwaps ()
Iteratively swaps edges to minimize the Delaunay minimum angle. O(N).
Edges tagged as sharp are constrained not to swap. On generically curved manifolds this process is not guaranteed to converge. This method returns TRUE if convergence is reached, FALSE otherwise.
Definition at line 1327 of file tin.cpp.
References List::appendHead(), List::appendTail(), JMesh::begin_progress(), Node::data, Edge::delaunayMinAngle(), JMesh::end_progress(), FOREACHEDGE, FOREACHTRIANGLE, Triangle::getNormal(), List::head(), IS_SHARPEDGE, IS_VISITED, Triangle::isNeedle(), Edge::isOnBoundary(), MARK_VISIT, Node::next(), Triangle::nextEdge(), Node::prev(), Triangle::prevEdge(), List::removeCell(), JMesh::report_progress(), Edge::swap(), Edge::t1, Edge::t2, List::tail(), UNMARK_VISIT, and JMesh::warning().
{
 Node *n;
 Edge *e, *f;
 double l;
 int swaps=1, totits=1;
 Point n1, n2, nor;
 List toswap;
 bool selection=0;
 Triangle *t;
 FOREACHTRIANGLE(t, n) if (IS_VISITED(t)) {selection=1; break;}
 FOREACHEDGE(e, n) if (!IS_SHARPEDGE(e) && !e->isOnBoundary())
 {
  MARK_VISIT(e); if ((!selection || (IS_VISITED(e->t1) && IS_VISITED(e->t2)))) toswap.appendTail(e);
 }
 JMesh::begin_progress();
 while (swaps && totits++ < 10)
 {
  swaps = 0; for (n=toswap.head(); n!=NULL; )
  {
   e = (Edge *)n->data;
   if (n==toswap.tail()) {toswap.removeCell(toswap.tail()); n=NULL;}
   else {n=n->next(); toswap.removeCell(n->prev());}
   UNMARK_VISIT(e);
   if (!e->t1->isNeedle() && !e->t2->isNeedle())
   {
    n1 = e->t1->getNormal();
    n2 = e->t2->getNormal();
    nor = n1+n2;
    l = e->delaunayMinAngle();
    if (e->swap())
    {
     if (e->t1->isNeedle() || e->t2->isNeedle() || e->delaunayMinAngle() <= l*1.000001 || nor*e->t1->getNormal() <= 0 || nor*e->t2->getNormal() <= 0) e->swap(1);
     else
     {
      swaps++;
      f = e->t1->nextEdge(e); if (!IS_VISITED(f) && !IS_SHARPEDGE(f) && !f->isOnBoundary()) {MARK_VISIT(f); toswap.appendHead(f);}
      f = e->t1->prevEdge(e); if (!IS_VISITED(f) && !IS_SHARPEDGE(f) && !f->isOnBoundary()) {MARK_VISIT(f); toswap.appendHead(f);}
      f = e->t2->nextEdge(e); if (!IS_VISITED(f) && !IS_SHARPEDGE(f) && !f->isOnBoundary()) {MARK_VISIT(f); toswap.appendHead(f);}
      f = e->t2->prevEdge(e); if (!IS_VISITED(f) && !IS_SHARPEDGE(f) && !f->isOnBoundary()) {MARK_VISIT(f); toswap.appendHead(f);}
     }
    }
   }
  }
  JMesh::report_progress("Swaps: %d      ", swaps);
 }
 JMesh::end_progress();
 FOREACHEDGE(e, n) UNMARK_VISIT(e);
 if (totits >= 10)
 {
  JMesh::warning("Optimization did not converge after 10 iterations! Stopping.\n");
  JMesh::warning("You may try to run the method again.\n");
  return 0;
 }
 return 1;
}
int Triangulation::load (const char * filename, const bool update = 1)
Initialize the triangle mesh from the file 'filename'.
The file format is automatically deduced from the magic number or the filename extension. If 'doupdate' is FALSE, the global update for the topological entities is prevented. Currently, the following file formats are supported: Open Inventor (IV), VRML 1.0 and 2.0 (WRL), Object File Format (OFF), IMATI Ver-Tri (VER, TRI). A non-zero value is returned in case of error. Specifically, IO_CANTOPEN means that the file couldn't be opened for reading. IO_FORMAT means that the file format was not recognized by the loader. IO_UNKNOWN represents all the other errors. The calling function is responsible of verifying that the mesh is empty before calling this method.
Definition at line 158 of file io.cpp.
References eulerUpdate(), IO_CANTOPEN, IO_UNKNOWN, IV_HEADER, IV_HSIZE, loadIV(), loadOBJ(), loadOFF(), loadPLY(), loadSTL(), loadVerTri(), loadVRML1(), loadVRML2(), OFF_HEADER, OFF_HSIZE, PLY_HEADER, PLY_HSIZE, sameString(), VRML1_HEADER, VRML1_HSIZE, VRML2_HEADER, and VRML2_HSIZE.
{
 FILE *fp;
 char header[256];
 size_t as;
 int err = IO_UNKNOWN;
 if ((fp = fopen(fname,"r")) == NULL) return IO_CANTOPEN;
 as = fread(header, 1, 256, fp);
 fclose(fp);
 if (as >= VRML1_HSIZE && !strncmp(header, VRML1_HEADER, VRML1_HSIZE)) err = loadVRML1(fname);
 else if (as >= VRML2_HSIZE && !strncmp(header, VRML2_HEADER, VRML2_HSIZE)) err = loadVRML2(fname);
 else if (as >= OFF_HSIZE && !strncmp(header, OFF_HEADER, OFF_HSIZE)) err = loadOFF(fname);
 else if (as >= PLY_HSIZE && !strncmp(header, PLY_HEADER, PLY_HSIZE)) err = loadPLY(fname);
 else if (as >= IV_HSIZE && !strncmp(header, IV_HEADER, IV_HSIZE)) err = loadIV(fname);
 else if (sameString((char *)(fname+strlen(fname)-4), (char *)".obj")) err = loadOBJ(fname);
 else if (sameString((char *)(fname+strlen(fname)-4), (char *)".tri")) err = loadVerTri(fname);
 else if (sameString((char *)(fname+strlen(fname)-4), (char *)".stl")) err = loadSTL(fname);
 if (!err && doupdate) eulerUpdate();
 return err;
}
int Triangulation::loadIV (const char * fname)
Loads IV.
Definition at line 375 of file io.cpp.
References loadVRML1().
{
 return loadVRML1(fname);
}
int Triangulation::loadOBJ (const char * fname)
Loads OBJ.
Definition at line 1149 of file io.cpp.
References List::appendTail(), JMesh::begin_progress(), closeLoadingSession(), CreateIndexedTriangle(), JMesh::end_progress(), JMesh::error(), FOREACHVERTEX, IO_CANTOPEN, List::numels(), readLineFromFile(), JMesh::report_progress(), V, and JMesh::warning().
{
 FILE *fp;
 Node *n;
 char c, cmd[3] = "";
 float x,y,z;
 bool face_section = 0;
 int i=0,i1,i2,i3,nv=0,triangulate=0;
 Vertex *v;
 ExtVertex **var=NULL;
 if ((fp = fopen(fname,"r")) == NULL) return IO_CANTOPEN;
 JMesh::begin_progress();
 while (fscanf(fp, "%2s", cmd) && cmd[0] != '\0')
 {
  if (!strcmp(cmd,"v"))
  {
   if (face_section) JMesh::error("\nloadOBJ: Sorry. Couldn't manage disconnected vertex sections.\n");
   if (fscanf(fp, "%f %f %f", &x, &y, &z) == 3) V.appendTail(new Vertex(x,y,z));
   else JMesh::error("\nloadOBJ: Couldn't read coordinates for vertex # %d\n",i);
  }
  else if (!strcmp(cmd,"f"))
  {
   if (!face_section)
   {
    nv = V.numels();
    var = (ExtVertex **)malloc(sizeof(ExtVertex *)*nv);
    i=0; FOREACHVERTEX(v, n) var[i++] = new ExtVertex(v);
    face_section = 1;
    i=0;
   }
   if (fscanf(fp,"%d %d %d",&i1,&i2,&i3) == 3)
   {
    if ((i%1000) == 0) JMesh::report_progress("Loading ..%d%%",(i*100)/(nv*2));
    if (i1<0 || i2<0 || i3<0) JMesh::error("\nloadOBJ: Sorry. Negative vertex references not supported.\n");
    if (i1<1 || i2<1 || i3<1 || i1>nv || i2>nv || i3>nv) JMesh::error("\nloadOBJ: Invalid index at face %d!\n",i);
    do
    {
     if (i1 == i2 || i2 == i3 || i3 == i1) JMesh::warning("\nloadOBJ: Coincident indexes at triangle %d! Skipping.\n",i);
     else if (!CreateIndexedTriangle(var, i1-1, i2-1, i3-1)) JMesh::warning("\nloadOBJ: This shouldn't happen!!! Skipping triangle.\n");
     i2 = i3;
     while ((c=fgetc(fp)) != EOF && isspace(c) && c != '\n' && c != '\r');
     if (c==EOF) JMesh::error("\nloadOBJ: Unexpected end of file!\n");
     if (c != '\n' && c != '\r')
     {
      ungetc(c, fp);
      if (fscanf(fp,"%d",&i3) != 1) JMesh::error("\nloadOBJ: Couldn't read indexes for face # %d\n",i);
      else triangulate=1;
     }
    } while (c != '\n' && c != '\r');
   }
   else JMesh::error("\nloadOBJ: Couldn't read indexes for face # %d\n",i);
   i++;
  }
  else if (readLineFromFile(fp, 0) == NULL) break;
  cmd[0]='\0';
 }
 JMesh::end_progress();
 closeLoadingSession(fp, i, var, (triangulate!=0));
 return 0;
}
int Triangulation::loadOFF (const char * fname)
Loads OFF.
Definition at line 383 of file io.cpp.
References List::appendTail(), JMesh::begin_progress(), closeLoadingSession(), CreateIndexedTriangle(), JMesh::end_progress(), JMesh::error(), FOREACHVERTEX, IO_CANTOPEN, IO_FORMAT, readLineFromFile(), JMesh::report_progress(), skipCommentAndBlankLines(), V, and JMesh::warning().
{
 FILE *fp;
 Node *n;
 char s[256], *line;
 float x,y,z;
 int i,j,i1,i2,i3,i4,nv,nt,ne,triangulate=0;
 Vertex *v;
 if ((fp = fopen(fname,"rb")) == NULL) return IO_CANTOPEN;
 fscanf(fp,"%255s",s);
 if (strcmp(s,"OFF") || feof(fp)) return IO_FORMAT;
 do {line = readLineFromFile(fp);} while (line[0] == '#' || line[0] == '\0' || !sscanf(line,"%256s",s));
 if (sscanf(line,"%d %d %d",&nv,&nt,&ne) < 3) return IO_FORMAT;
 if (nv < 3) JMesh::error("\nloadOFF: Sorry. Can't load objects with less than 3 vertices.\n");
 if (nt < 1) JMesh::error("\nloadOFF: Sorry. Can't load objects with no faces.\n");
 skipCommentAndBlankLines(fp);
 for (i=0; i<nv; i++)
  if (fscanf(fp,"%f %f %f",&x,&y,&z) == 3) V.appendTail(new Vertex(x,y,z));
  else JMesh::error("\nloadOFF: Couldn't read coordinates for vertex # %d\n",i);
 ExtVertex **var = (ExtVertex **)malloc(sizeof(ExtVertex *)*nv);
 i=0; FOREACHVERTEX(v, n) var[i++] = new ExtVertex(v);
 skipCommentAndBlankLines(fp);
 JMesh::begin_progress();
 for (i=0; i<nt; i++)
 {
  if (fscanf(fp,"%d %d %d %d",&i4,&i1,&i2,&i3) == 4)
  {
   if ((i%1000) == 0) JMesh::report_progress("Loading ..%d%%",(i*100)/(nv*2));
   if (i1<0 || i2<0 || i3<0 || i4<3 || i1>(nv-1) || i2>(nv-1) || i3>(nv-1)) JMesh::error("\nloadOFF: Invalid index at face %d!\n",i);
   for (j=3; j<=i4; j++)
   {
    if (i1 == i2 || i2 == i3 || i3 == i1) JMesh::warning("\nloadOFF: Coincident indexes at triangle %d! Skipping.\n",i);
    else if (!CreateIndexedTriangle(var, i1, i2, i3)) JMesh::warning("\nloadOFF: This shouldn't happen!!! Skipping triangle.\n");
    i2 = i3;
    if (j<i4)
    {
     if (fscanf(fp,"%d",&i3) != 1) JMesh::error("\nloadOFF: Couldn't read indexes for face # %d\n",i);
     else triangulate=1;
    }
   }
  }
  else JMesh::error("\nloadOFF: Couldn't read indexes for face # %d\n",i);
 }
 JMesh::end_progress();
 closeLoadingSession(fp, i, var, (triangulate != 0));
 return 0;
}
int Triangulation::loadPLY (const char * fname)
Loads PLY.
Definition at line 1013 of file io.cpp.
References List::appendTail(), JMesh::begin_progress(), closeLoadingSession(), CreateIndexedTriangle(), JMesh::end_progress(), JMesh::error(), FOREACHVERTEX, ply_checkFaceProperties(), ply_checkVertexProperties(), PLY_FORMAT_ASCII, PLY_FORMAT_BIN_B, PLY_FORMAT_BIN_L, ply_getOverhead(), ply_parseElements(), ply_readAnotherFIndex(), ply_readFIndices(), ply_readOverhead(), ply_readVCoords(), readLineFromFile(), JMesh::report_progress(), V, and JMesh::warning().
{
 int format=0, voh, foh, vph, fph;
 int nv,nt,i,j,i1,i2,i3,i4;
 float x,y,z;
 bool triangulate = 0;
 FILE *in;
 char keyword[64], formats[24], version[10];
 Vertex *v;
 Node *n;
 if ((in = fopen(fname,"rb")) == NULL) JMesh::error("Can't open input ply file\n");
 if (strcmp(readLineFromFile(in),"ply")) JMesh::error("Input doesn't seem a valid ply file.\n");
 if (sscanf(readLineFromFile(in),"%7s %24s %10s",keyword,formats,version) < 3) JMesh::error("Unexpected token or end of file!\n");
 if (strcmp(keyword,"format")) JMesh::error("format definition expected!\n");
 if (!strcmp(formats,"ascii")) format = PLY_FORMAT_ASCII;
 else if (!strcmp(formats,"binary_little_endian")) format = PLY_FORMAT_BIN_L;
 else if (!strcmp(formats,"binary_big_endian")) format = PLY_FORMAT_BIN_B;
 else JMesh::error("Unrecognized format '%s'\n",formats);
 nv = ply_parseElements(in, "vertex");
 vph = ply_getOverhead(in, format, "vertex");
 ply_checkVertexProperties(in);
 voh = ply_getOverhead(in, format, "vertex");
 nt = ply_parseElements(in, "face");
 fph = ply_getOverhead(in, format, "face");
 ply_checkFaceProperties(in);
 foh = ply_getOverhead(in, format, "face");
 if (!sscanf(readLineFromFile(in),"%64s ",keyword)) JMesh::error("Unexpected token or end of file!\n");
 while (strcmp(keyword, "end_header"))
  if (!sscanf(readLineFromFile(in),"%64s ",keyword)) JMesh::error("Unexpected token or end of file!\n");
 for (i=0; i<nv; i++)
 {
  ply_readVCoords(in, format, vph, voh, &x, &y, &z);
  V.appendTail(new Vertex(x,y,z));
 }
 ExtVertex **var = (ExtVertex **)malloc(sizeof(ExtVertex *)*nv);
 i=0; FOREACHVERTEX(v, n) var[i++] = new ExtVertex(v);
 i=0;
 JMesh::begin_progress();
 for (i=0; i<nt; i++)
 {
  if (ply_readFIndices(in, format, fph, &i4, &i1, &i2, &i3))
  {
   if ((i%1000) == 0) JMesh::report_progress("Loading ..%d%%",(i*100)/(nv*2));
   if (i1<0 || i2<0 || i3<0 || i4<3 || i1>(nv-1) || i2>(nv-1) || i3>(nv-1)) JMesh::error("\nloadPLY: Invalid index at face %d!\n",i);
   for (j=3; j<=i4; j++)
   {
    if (i1 == i2 || i2 == i3 || i3 == i1) JMesh::warning("\nloadPLY: Coincident indexes at triangle %d! Skipping.\n",i);
    else if (!CreateIndexedTriangle(var, i1, i2, i3)) JMesh::warning("\nloadPLY: This shouldn't happen!!! Skipping triangle.\n");
    i2 = i3;
    if (j<i4)
    {
     if (!ply_readAnotherFIndex(in, format, &i3)) JMesh::error("\nloadPLY: Couldn't read indexes for face # %d\n",i);
     else triangulate=1;
    }
    else ply_readOverhead(in, format, foh);
   }
  }
  else JMesh::error("\nloadPLY: Couldn't read indexes for face # %d\n",i);
 }
 JMesh::end_progress();
 closeLoadingSession(in, i, var, triangulate);
 return 0;
}
int Triangulation::loadSTL (const char * fname)
Loads STL.
Definition at line 1256 of file io.cpp.
References List::appendHead(), JMesh::begin_progress(), CreateEdge(), CreateTriangle(), duplicateNonManifoldVertices(), JMesh::end_progress(), JMesh::error(), JMesh::info(), IO_CANTOPEN, mergeCoincidentEdges(), List::numels(), readLineFromFile(), removeDuplicatedTriangles(), JMesh::report_progress(), Point::setValue(), T, V, and JMesh::warning().
{
 FILE *fp;
 int nt=0, i=0;
 char kw[64]="", kw2[64]="", *line, facet[50];
 float x,y,z;
 bool binary=0;
 Vertex *v, *v1=NULL, *v2=NULL, *v3=NULL;
 Edge *e1, *e2, *e3;
 Triangle *t;
 Point nor;
 if ((fp = fopen(fname,"r")) == NULL) return IO_CANTOPEN;
 fscanf(fp,"%5s",kw);
 if (strcmp(kw,"solid")) binary=1;
 JMesh::begin_progress();
 if (binary)
 {
  fseek(fp, 80, SEEK_SET);
  fread(&nt, 4, 1, fp);
  for (i=0; i<nt; i++)
  {
   if ((i)%10000 == 0) JMesh::report_progress(NULL);
   if (!fread(facet, 50, 1, fp)) JMesh::error("loadSTL: Unexpected end of file!\n");
   nor.setValue((*((float *)(facet+0))), (*((float *)(facet+4))), (*((float *)(facet+8))));
   v1 = new Vertex((*((float *)(facet+12))), (*((float *)(facet+16))), (*((float *)(facet+20))));
   v2 = new Vertex((*((float *)(facet+24))), (*((float *)(facet+28))), (*((float *)(facet+32))));
   v3 = new Vertex((*((float *)(facet+36))), (*((float *)(facet+40))), (*((float *)(facet+44))));
   V.appendHead(v1); V.appendHead(v2); V.appendHead(v3);
   e1=CreateEdge(v1, v2); e2=CreateEdge(v2, v3); e3=CreateEdge(v3, v1);
   if (Triangle(e1,e2,e3).getNormal()*nor < 0) t=CreateTriangle(e1, e3, e2);
   else t=CreateTriangle(e1, e2, e3);
  }
 }
 else
 {
  while ((line = readLineFromFile(fp, 0))!=NULL)
  {
   if ((i++)%10000 == 0) JMesh::report_progress(NULL);
   sscanf(line,"%64s %f %f %f",kw,&x,&y,&z);
   if (!strcmp(kw,"facet"))
   {
    sscanf(line,"%64s %64s %f %f %f",kw,kw2,&x,&y,&z);
    nor.setValue(x,y,z);
   }
   else
   if (!strcmp(kw,"vertex"))
   {
    V.appendHead((v=new Vertex(x,y,z)));
    if (v1==NULL) v1=v;
    else if (v2==NULL) v2=v;
    else if (v3==NULL)
    {
     v3=v;
     e1=CreateEdge(v1, v2);
     e2=CreateEdge(v2, v3);
     e3=CreateEdge(v3, v1);
     if (Triangle(e1,e2,e3).getNormal()*nor < 0) t=CreateTriangle(e1, e3, e2);
     else t=CreateTriangle(e1, e2, e3);
     v1=v2=v3=NULL;
    }
   }
  }
 }
 JMesh::end_progress();
 fclose(fp);
 JMesh::info("Loaded %d vertices and %d faces.\n",V.numels(),T.numels());
 mergeCoincidentEdges();
 if ((i=duplicateNonManifoldVertices())) JMesh::warning("%d non-manifold vertices have been duplicated.\n",i);
 if ((i=removeDuplicatedTriangles())) JMesh::warning("%d vertices have been added to split double-triangles.\n",i);
 return 0;
}
int Triangulation::loadVerTri (const char * fname)
Loads VER-TRI.
Definition at line 491 of file io.cpp.
References List::appendTail(), JMesh::begin_progress(), closeLoadingSession(), CreateIndexedTriangle(), JMesh::end_progress(), JMesh::error(), FOREACHVERTEX, IO_FORMAT, IO_UNKNOWN, List::numels(), JMesh::report_progress(), sameString(), T, V, and JMesh::warning().
{
 FILE *fpv, *fpt;
 int numvers, numtris, i, i1, i2, i3, a1, a2, a3;
 float x,y,z;
 char vername[256], triname[256];
 Node *n;
 Vertex *v;
 if (!sameString((char *)(fname+strlen(fname)-4), (char *)".tri")) return IO_UNKNOWN;
 strcpy(triname,fname);
 strcpy(vername,fname); vername[strlen(vername)-4]='\0';
 strcat(vername,".ver");
 if ((fpv = fopen(vername,"r")) == NULL)
 {
  fprintf(stderr,"Can't open '%s' for input !\n",vername);
  return 1;
 }
 if ((fpt = fopen(triname,"r")) == NULL)
 {
  fclose(fpv);
  fprintf(stderr,"Can't open '%s' for input !\n",triname);
  return 1;
 }
 if (!fscanf(fpv,"%d\n",&numvers) || numvers < 3) {fclose(fpv); fclose(fpt); return IO_FORMAT;}
 if (!fscanf(fpt,"%d\n",&numtris) || numtris < 1) {fclose(fpv); fclose(fpt); return IO_FORMAT;}
 for (i=0; i<numvers; i++)
  if (fscanf(fpv,"%f %f %f\n",&x,&y,&z) != 3) JMesh::error("Couldn't read %d'th vertex!\n",i+1);
  else V.appendTail(new Vertex(x,y,z));
 fclose(fpv);
 ExtVertex **var = (ExtVertex **)malloc(sizeof(ExtVertex *)*numvers);
 i=0; FOREACHVERTEX(v, n) var[i++] = new ExtVertex(v);
 JMesh::begin_progress();
 for (i=0; i<numtris; i++)
  if (fscanf(fpt,"%d %d %d %d %d %d",&i1,&i2,&i3,&a1,&a2,&a3) == 6)
  {
   if (((i)%1000) == 0) JMesh::report_progress("Loading ..%d%%",(i*100)/(numtris));
   if (i1 < 1 || i2 < 1 || i3 < 1) JMesh::error("\nloadVerTri: Illegal index at triangle %d!\n",i);
   else if (i1 > (numvers) || i2 > (numvers) || i3 > (numvers)) JMesh::error("\nloadVerTri: Index out of bounds at triangle %d!\n",i);
   else if (i1 == i2 || i2 == i3 || i3 == i1) JMesh::warning("\nloadVerTri: Coincident indexes at triangle %d! Skipping.\n",i);
   else if (!CreateIndexedTriangle(var, i1-1, i2-1, i3-1)) JMesh::warning("\nloadVerTri: This shouldn't happen!!! Skipping triangle.\n");
  }
  else JMesh::error("loadVerTri: Couldn't read %dth triangle !\n",i+1);
 JMesh::end_progress();
 closeLoadingSession(fpt, T.numels(), var, 0);
 return 0;
}
int Triangulation::loadVRML1 (const char * fname)
Loads VRML 1.0.
Definition at line 331 of file io.cpp.
References List::appendTail(), JMesh::begin_progress(), closeLoadingSession(), CreateIndexedTriangle(), JMesh::end_progress(), JMesh::error(), FOREACHVERTEX, IO_CANTOPEN, IO_FORMAT, List::numels(), JMesh::report_progress(), seek_keyword(), V, and JMesh::warning().
{
 FILE *fp;
 Node *n;
 float x,y,z;
 int i,i1,i2,i3,i4,nv=0,triangulate=0;
 Vertex *v;
 if ((fp = fopen(fname,"r")) == NULL) return IO_CANTOPEN;
 if (!seek_keyword(fp, "point")) {closeLoadingSession(fp, 0, NULL, 0); return IO_FORMAT;}
 if (!seek_keyword(fp, "[")) {closeLoadingSession(fp, 0, NULL, 0); return IO_FORMAT;}
 while (fscanf(fp,"%f %f %f,",&x,&y,&z) == 3) V.appendTail(new Vertex(x,y,z));
 nv = V.numels();
 ExtVertex **var = (ExtVertex **)malloc(sizeof(ExtVertex *)*nv);
 i=0; FOREACHVERTEX(v, n) var[i++] = new ExtVertex(v);
 if (!seek_keyword(fp, "coordIndex")) {closeLoadingSession(fp, 0, var, 0); return IO_FORMAT;}
 if (!seek_keyword(fp, "[")) {closeLoadingSession(fp, 0, var, 0); return IO_FORMAT;}
 i=0; JMesh::begin_progress();
 while (fscanf(fp,"%d, %d, %d,",&i1,&i2,&i3) == 3)
 {
  if (((i++)%1000) == 0) JMesh::report_progress("Loading ..%d%%",(i*100)/(nv*2));
  if (i1<0 || i2<0 || i3<0 || i1>(nv-1) || i2>(nv-1) || i3>(nv-1))
      JMesh::error("\nloadVRML1: Invalid indices %d %d %d!\n",i1,i2,i3);
  do
  {
   if (i1 == i2 || i2 == i3 || i3 == i1) JMesh::warning("\nloadVRML1: Coincident indexes at face %d! Skipping.\n",i);
   else if (!CreateIndexedTriangle(var, i1, i2, i3)) JMesh::warning("\nloadVRML1: This shouldn't happen!!! Skipping triangle.\n");
   if (fscanf(fp,"%d,",&i4) != 1) JMesh::error("loadVRML1: Unexpected end of file at face %d!\n",i);
   i2=i3; i3=i4;
   if (i4 != -1) triangulate=1;
  } while (i4 != -1);
 }
 JMesh::end_progress();
 closeLoadingSession(fp, i, var, (triangulate != 0));
 return 0;
}
int Triangulation::loadVRML2 (const char * fname)
Loads VRML 2.0.
Definition at line 444 of file io.cpp.
References List::appendTail(), JMesh::begin_progress(), closeLoadingSession(), CreateIndexedTriangle(), JMesh::end_progress(), JMesh::error(), FOREACHVERTEX, IO_CANTOPEN, IO_FORMAT, List::numels(), JMesh::report_progress(), seek_keyword(), V, and JMesh::warning().
{
 FILE *fp;
 Node *n;
 float x,y,z;
 int i,i1,i2,i3,i4,nv=0,triangulate=0;
 Vertex *v;
 if ((fp = fopen(fname,"r")) == NULL) return IO_CANTOPEN;
 if (!seek_keyword(fp, "point")) {fclose(fp); return IO_FORMAT;}
 if (!seek_keyword(fp, "[")) {fclose(fp); return IO_FORMAT;}
 while (fscanf(fp,"%f %f %f,",&x,&y,&z) == 3) V.appendTail(new Vertex(x,y,z));
 nv = V.numels();
 if (!seek_keyword(fp, "coordIndex")) {fclose(fp); return IO_FORMAT;}
 if (!seek_keyword(fp, "[")) {fclose(fp); return IO_FORMAT;}
 ExtVertex **var = (ExtVertex **)malloc(sizeof(ExtVertex *)*nv);
 i=0; FOREACHVERTEX(v, n) var[i++] = new ExtVertex(v);
 i=0;
 JMesh::begin_progress();
 while (fscanf(fp,"%d, %d, %d,",&i1,&i2,&i3) == 3)
 {
  if (((i++)%1000) == 0) JMesh::report_progress("Loading ..%d%%",(i*100)/(nv*2));
  if (i1<0 || i2<0 || i3<0 || i1>(nv-1) || i2>(nv-1) || i3>(nv-1)) JMesh::error("\nloadVRML2: Invalid index at face %d!\n",i);
  do
  {
   if (i1 == i2 || i2 == i3 || i3 == i1) JMesh::warning("\nloadVRML2: Coincident indexes at triangle %d! Skipping.\n",i);
   else if (!CreateIndexedTriangle(var, i1, i2, i3)) JMesh::warning("\nloadVRML2: This shouldn't happen!!! Skipping triangle.\n");
   if (fscanf(fp,"%d,",&i4) != 1) JMesh::error("loadVRML2: Unexpected end of file at triangle %d!\n",i);
   i2=i3; i3=i4;
   if (i4 != -1) triangulate=1;
  } while (i4 != -1);
 }
 JMesh::end_progress();
 closeLoadingSession(fp, i, var, (triangulate != 0));
 return 0;
}
int Triangulation::mergeCoincidentEdges ()
Definition at line 258 of file checkAndRepair.cpp.
References List::appendHead(), d_boundaries, d_handles, d_shells, FOREACHEDGE, Edge::isLinked(), Edge::isOnBoundary(), jqsort(), lexEdgeCompare(), Edge::merge(), List::numels(), removeEdges(), removeVertices(), Edge::t1, Edge::t2, List::toArray(), Edge::v1, Edge::v2, JMesh::warning(), and Vertex::zip().
{
 List bes;
 Node *n;
 Edge *e1, *e2;
 FOREACHEDGE(e1, n) if (e1->isOnBoundary()) bes.appendHead(e1);
 if (!bes.numels()) return 0;
 Edge **evarr = (Edge **)bes.toArray();
 int i, ret = 0, wrn = 0;
 jqsort((void **)evarr, bes.numels(), lexEdgeCompare);
  for (i=0; i<(bes.numels()-1); i++)
  {
   e1 = evarr[i];
   e2 = evarr[i+1];
   if (!e2->isLinked()) evarr[i+1]=e1;
   else if (!lexEdgeCompare(e1, e2) &&
            (
             (((*(e1->v1))==(*(e2->v1))) && ((e1->t1 && e2->t2) || (e1->t2 && e2->t1))) ||
             (((*(e1->v1))==(*(e2->v2))) && ((e1->t1 && e2->t1) || (e1->t2 && e2->t2)))
            )
           )
           {
            if (!e2->merge(e1)) wrn++;
            else
            {
             ret += e2->v1->zip();
             ret += e2->v2->zip();
            }
           }
  }
 free(evarr);
 removeEdges();
 removeVertices();
 if (wrn) JMesh::warning("mergeCoincidentEdges: Couldn't merge unconsistently oriented edges.\n");
 if (ret) d_boundaries = d_handles = d_shells = 1;
 return ret;
}
Vertex * Triangulation::nextVertexOnRegionBoundary (Vertex * v) const
Get the vertex next to 'v' on the boundary of the region. O(1).
Definition at line 1035 of file tin.cpp.
References FOREACHVEEDGE, IS_VISITED, Edge::leftTriangle(), Edge::oppositeVertex(), Edge::rightTriangle(), and Vertex::VE().
{
 Triangle *lt, *rt;
 Edge *e;
 List *ve = sv->VE();
 Node *n;
 FOREACHVEEDGE(ve, e, n)
 {
  lt = e->leftTriangle(sv);
  rt = e->rightTriangle(sv);
  if (lt != NULL && IS_VISITED(lt) && (rt == NULL || !IS_VISITED(rt)))
   {delete(ve); return e->oppositeVertex(sv);}
 }
 delete(ve);
 return NULL;
}
void Triangulation::normalize (const double s = 1.0)
Scale the mesh to make it fit within a cube [0,0,0]-[s,s,s]. O(N).
Definition at line 1270 of file tin.cpp.
References FOREACHVERTEX, getBoundingBox(), and Point::setValue().
{
 Vertex *v;
 Node *n;
 Point mp, Mp;
 double mel = getBoundingBox(mp, Mp)/mc;
 FOREACHVERTEX(v, n) v->setValue(((*v)-mp)/mel);    // Shift and normalize
}
void Triangulation::openToDisk ()
Duplicates edges and vertices to make the mesh homeomorphic to a disk. O(N).
Definition at line 1551 of file tin.cpp.
References List::appendHead(), List::appendTail(), d_boundaries, d_handles, d_shells, Node::data, duplicateNonManifoldVertices(), E, Triangle::e1, Triangle::e2, Triangle::e3, JMesh::error(), FOREACHEDGE, FOREACHTRIANGLE, FOREACHVERTEX, List::head(), Point::info, IS_BIT, Edge::isOnBoundary(), MARK_BIT, Node::next(), List::numels(), Edge::oppositeVertex(), List::popHead(), List::removeNode(), Triangle::replaceEdge(), T, Edge::t1, Triangle::t1(), Triangle::t2(), Triangle::t3(), UNMARK_BIT, Edge::v1, Edge::v2, and Vertex::VE().
{
 Triangle *t = (Triangle *)T.head()->data;
 Triangle *s;
 List triList, *ve;
 Vertex *v, *w;
 Edge *e, *ne;
 Node *n;
 triList.appendHead(t);
 MARK_BIT(t,3);
 while(triList.numels())
 {
  t = (Triangle *)triList.popHead();
  if ((s = t->t1()) != NULL && !IS_BIT(s,3))
   {triList.appendTail(s); MARK_BIT(s,3); MARK_BIT(t->e1,3);}
  if ((s = t->t2()) != NULL && !IS_BIT(s,3))
   {triList.appendTail(s); MARK_BIT(s,3); MARK_BIT(t->e2,3);}
  if ((s = t->t3()) != NULL && !IS_BIT(s,3))
   {triList.appendTail(s); MARK_BIT(s,3); MARK_BIT(t->e3,3);}
 }
 FOREACHTRIANGLE (t, n) UNMARK_BIT(t, 3);
 FOREACHVERTEX(v, n) v->info = new List;
 FOREACHEDGE(e, n) if (!IS_BIT(e, 3))
 {
  ((List *)e->v1->info)->appendHead(e);
  ((List *)e->v2->info)->appendHead(e);
 }
 FOREACHVERTEX(v, n) if (((List *)v->info)->numels()==1) triList.appendHead(v);
 if (!triList.numels()) JMesh::error("Triangulation::openToDisk: Couldn't find a root.\n");
 while(triList.numels())
 {
  v = (Vertex *)triList.popHead();
  ve = ((List *)v->info);
  if (ve->numels())
  {
   e = (Edge *)(ve->head()->data);
   MARK_BIT(e, 3);
   ve->popHead();
   w = e->oppositeVertex(v);
   ve = ((List *)w->info);
   ve->removeNode(e);
   if (ve->numels() == 1) triList.appendHead(w);
  }
  else
  {
   ve = v->VE();
   e = (Edge *)ve->head()->data; UNMARK_BIT(e, 3); ((List *)v->info)->appendHead(e);
   e = (Edge *)ve->head()->next()->data; UNMARK_BIT(e, 3); ((List *)v->info)->appendHead(e);
   delete(ve);
  }
 }
 FOREACHEDGE(e, n) if (!IS_BIT(e, 3) && !e->isOnBoundary())
 {
  ne = new Edge(e->v1, e->v2);
  ne->t1 = e->t1; e->t1 = NULL; E.appendHead(ne);
  ne->t1->replaceEdge(e, ne);
 }
 FOREACHEDGE(e, n) UNMARK_BIT(e, 3);
 FOREACHVERTEX(v, n) if (v->info) {delete(((List *)v->info)); v->info = NULL;}
 duplicateNonManifoldVertices();
 d_boundaries = d_handles = d_shells = 1;
}
void Triangulation::printReport ()
Definition at line 2115 of file tin.cpp.
References boundaries(), E, eulerUpdate(), handles(), JMesh::info(), List::numels(), shells(), T, and V.
{
 eulerUpdate();
 JMesh::info("*** Triangulation Report ***\n");
 JMesh::info("V: %d\n",V.numels());
 JMesh::info("E: %d\n",E.numels());
 JMesh::info("T: %d\n",T.numels());
 JMesh::info("Boundary: %d components.\n",boundaries());
 JMesh::info("Handles: %d.\n",handles());
 JMesh::info("Shells: %d.\n",shells());
}
int Triangulation::removeDegenerateTriangles ()
Definition at line 330 of file checkAndRepair.cpp.
References List::appendHead(), List::appendTail(), Edge::collapse(), FOREACHTRIANGLE, FOREACHVTTRIANGLE, IS_VISITED2, Triangle::isCap(), Triangle::isDegenerate(), Triangle::isLinked(), Triangle::isNeedle(), Edge::isOnBoundary(), MARK_VISIT, MARK_VISIT2, Triangle::nextEdge(), List::numels(), Edge::oppositeTriangle(), Triangle::oppositeVertex(), Triangle::overlaps(), List::popHead(), removeUnlinkedElements(), Edge::swap(), Edge::t1, Edge::t2, unlinkTriangle(), UNMARK_VISIT, UNMARK_VISIT2, Edge::v2, Vertex::valence(), Vertex::VT(), and JMesh::warning().
{
 Triangle *t;
 Edge *e;
 int collapses, swaps, degn, tcs = 0;
 List todo, *vt;
 Node *n;
int i=0;
 do
 {
  collapses = swaps = 0;
  FOREACHTRIANGLE(t, n) if (t->isDegenerate())
   {MARK_VISIT2(t); todo.appendHead(t);}
  while (todo.numels())
  {
i++;
   t = (Triangle *)todo.popHead();
   UNMARK_VISIT2(t);
   if (t->isLinked())
   {
    if ((e = t->isCap()) != NULL)
    {
     if (e->isOnBoundary()) {unlinkTriangle(t); collapses++;}
     else if (e->swap())
     {
      if (e->t1->overlaps() || e->t2->overlaps() || e->t1->isCap() || e->t2->isCap()) e->swap(1);
      else
      {
       swaps++;
       if (!IS_VISITED2(e->t1)) {MARK_VISIT2(e->t1); todo.appendTail(e->t1);}
       if (!IS_VISITED2(e->t2)) {MARK_VISIT2(e->t2); todo.appendTail(e->t2);}
      }
     }
    }
    else if ((e = t->isNeedle()) != NULL)
    {
     vt = e->v2->VT();
     if (e->collapse())
     {
      collapses++;
      FOREACHVTTRIANGLE(vt, t, n)
       if (t->isLinked() && !IS_VISITED2(t)) {MARK_VISIT2(t); todo.appendTail(t);}
     }
     else if (!e->isOnBoundary() && e->oppositeTriangle(t)->oppositeVertex(e)->valence() == 3)
     {
      if (e->oppositeTriangle(t)->nextEdge(e)->collapse())
      {
       MARK_VISIT2(t); todo.appendHead(t);
       t = e->oppositeTriangle(t);
       if (t && !IS_VISITED2(t)) {MARK_VISIT2(t); todo.appendTail(t);}
       collapses++;
      }
     }
     delete(vt);
    }
   }
  }
  if (collapses) removeUnlinkedElements();
  tcs += collapses; tcs += swaps;
 } while (collapses+swaps);
 degn=0;
 FOREACHTRIANGLE(t, n) if (t->isDegenerate()) degn++;
 if (degn)
 {
  FOREACHTRIANGLE(t, n) if (t->isDegenerate()) MARK_VISIT(t); else UNMARK_VISIT(t);
  JMesh::warning("removeDegenerateTriangles: %d degeneracies couldn't be removed.\n",degn);
  JMesh::warning("removeDegenerateTriangles: and have been selected.\n");
  return -tcs;
 }
 return tcs;
}
int Triangulation::removeDuplicatedTriangles ()
Definition at line 307 of file checkAndRepair.cpp.
References d_boundaries, d_handles, d_shells, FOREACHEDGE, Triangle::getCenter(), Edge::isOnBoundary(), Triangle::oppositeVertex(), splitTriangle(), Edge::t1, and Edge::t2.
{
 Edge *e;
 Node *n;
 Point p;
 int i=0;
 FOREACHEDGE(e, n)
  if (!e->isOnBoundary() && e->t1->oppositeVertex(e) == e->t2->oppositeVertex(e))
  {
   p = e->t2->getCenter();
   splitTriangle(e->t2, &p, 1);
   i++;
  }
 if (i)  d_boundaries = d_handles = d_shells = 1;
 return i;
}
int Triangulation::removeEdges ()
Removes all the unlinked edges from List E. Returns the number of removed edges. O(N).
Definition at line 432 of file tin.cpp.
References d_boundaries, d_handles, d_shells, Node::data, E, List::head(), Node::next(), Node::prev(), List::removeCell(), List::tail(), Edge::v1, and Edge::v2.
{
 Node *n;
 Edge *e;
 int r = 0;
 n = E.head();
 do
 {
  e = (Edge *)n->data;
  n = n->next();
  if (e->v1 == NULL || e->v2 == NULL)
  {
   r++;
   E.removeCell((n!=NULL)?(n->prev()):E.tail());
   delete e;
  }
 } while (n != NULL);
 d_boundaries = d_handles = d_shells = 1;
 return r;
}
int Triangulation::removeOverlappingTriangles ()
Definition at line 566 of file checkAndRepair.cpp.
References List::appendHead(), d_boundaries, d_handles, d_shells, Node::data, edgeCompare(), FOREACHEDGE, Triangle::getDAngle(), Triangle::isDegenerate(), Edge::isOnBoundary(), M_PI, Triangle::nextEdge(), Node::prev(), Triangle::prevEdge(), removeUnlinkedElements(), List::sort(), Edge::swap(), Edge::t1, Edge::t2, List::tail(), and unlinkTriangle().
{
 Node *n;
 Edge *e, *ea;
 List oved;
 FOREACHEDGE(e, n)
  if (!e->isOnBoundary() && e->t1->getDAngle(e->t2) == M_PI)
   oved.appendHead(e);
 oved.sort(edgeCompare);
 for (n=oved.tail(); n!=NULL; n=n->prev())
 {
  e = (Edge *)n->data;
  if (e->t1->getDAngle(e->t2) == M_PI && e->swap())
  {
   if (e->t1->isDegenerate() || e->t2->isDegenerate()) {e->swap(1); continue;}
   ea = e->t1->nextEdge(e);
   if (!ea->isOnBoundary() && ea->t1->getDAngle(ea->t2) == M_PI) {e->swap(1); continue;}
   ea = e->t1->prevEdge(e);
   if (!ea->isOnBoundary() && ea->t1->getDAngle(ea->t2) == M_PI) {e->swap(1); continue;}
   ea = e->t2->nextEdge(e);
   if (!ea->isOnBoundary() && ea->t1->getDAngle(ea->t2) == M_PI) {e->swap(1); continue;}
   ea = e->t2->prevEdge(e);
   if (!ea->isOnBoundary() && ea->t1->getDAngle(ea->t2) == M_PI) {e->swap(1); continue;}
  }
 }
 for (n=oved.tail(); n!=NULL; n=n->prev())
 {
  e = (Edge *)n->data;
  if (!e->isOnBoundary() && e->t1->getDAngle(e->t2) == M_PI) {unlinkTriangle(e->t1); unlinkTriangle(e->t2);}
 }
 removeUnlinkedElements();
 d_boundaries = d_handles = d_shells = 1;
 return 0;
}
void Triangulation::removeRegion (Triangle * t0, const double L, const Point * p)
Removes triangles within distance L from 'p'. O(N).
Starting from 't0', which is assumed to contain 'p', remove a triangle at a time as long as all its vertices stay within distance L from 'p'.
Definition at line 1000 of file tin.cpp.
References List::appendHead(), Node::data, Point::distance(), Triangle::e1, Triangle::e2, Triangle::e3, List::head(), IS_VISITED, MARK_VISIT, List::numels(), Triangle::oppositeVertex(), Node::prev(), List::removeCell(), removeUnlinkedElements(), Triangle::t1(), Triangle::t2(), Triangle::t3(), List::tail(), and unlinkTriangle().
{
 List triList, toRemove;
 Node *n;
 Triangle *s;
 triList.appendHead(t);
 MARK_VISIT(t);
 while(triList.numels() > 0)
 {
  t = (Triangle *)triList.head()->data;
  triList.removeCell(triList.head());
  toRemove.appendHead(t);
  if ((s = t->t1()) != NULL && !IS_VISITED(s) && s->oppositeVertex(t->e1)->distance(center) <= L)
   {triList.appendHead(s); MARK_VISIT(s);}
  if ((s = t->t2()) != NULL && !IS_VISITED(s) && s->oppositeVertex(t->e2)->distance(center) <= L)
   {triList.appendHead(s); MARK_VISIT(s);}
  if ((s = t->t3()) != NULL && !IS_VISITED(s) && s->oppositeVertex(t->e3)->distance(center) <= L)
   {triList.appendHead(s); MARK_VISIT(s);}
 }
 for (n = toRemove.tail(); n != NULL; n=n->prev())
 {
  s = ((Triangle *)n->data);
  unlinkTriangle(s);
 }
 removeUnlinkedElements();
}
void Triangulation::removeSelectedTriangles ()
Removes all the selected triangles. O(N).
Definition at line 504 of file tin.cpp.
References FOREACHTRIANGLE, IS_VISITED, removeUnlinkedElements(), and unlinkTriangle().
{
 Node *n;
 Triangle *t;
 FOREACHTRIANGLE(t, n) if (IS_VISITED(t)) unlinkTriangle(t);
 removeUnlinkedElements();
}
void Triangulation::removeShell (Triangle * t0)
Remove all the triangles belonging to the shell containing 't0'. O(N).
Definition at line 1142 of file tin.cpp.
References List::appendHead(), IS_VISITED2, MARK_VISIT2, List::numels(), List::popHead(), removeUnlinkedElements(), Triangle::t1(), Triangle::t2(), Triangle::t3(), and unlinkTriangle().
{
 List todo(t0);
 Triangle *t, *t1, *t2, *t3;
 while (todo.numels())
 {
  t = (Triangle *)todo.popHead();
  t1 = t->t1(); t2 = t->t2(); t3 = t->t3();
  if (t1 != NULL && !IS_VISITED2(t1)) {MARK_VISIT2(t1); todo.appendHead(t1);}
  if (t2 != NULL && !IS_VISITED2(t2)) {MARK_VISIT2(t2); todo.appendHead(t2);}
  if (t3 != NULL && !IS_VISITED2(t3)) {MARK_VISIT2(t3); todo.appendHead(t3);}
  unlinkTriangle(t);
 }
 removeUnlinkedElements();
}
int Triangulation::removeSmallestComponents ()
Definition at line 412 of file checkAndRepair.cpp.
References List::appendHead(), List::appendTail(), d_boundaries, d_handles, d_shells, Node::data, Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHNODE, FOREACHTRIANGLE, FOREACHVTTRIANGLE, List::head(), IS_VISITED2, MARK_VISIT2, Node::next(), List::numels(), List::removeCell(), List::removeNodes(), removeUnlinkedElements(), T, Triangle::t1(), Triangle::t2(), Triangle::t3(), UNMARK_VISIT2, Edge::v1, and Edge::v2.
{
 Node *n,*m;
 List todo;
 List components;
 List *component, *biggest = NULL;
 Triangle *t, *t1, *t2, *t3;
 int nt = 0, gnt = 0;
 t = ((Triangle *)T.head()->data);
 n = T.head();
 do
 {
  component = new List;
  components.appendHead(component);
  todo.appendHead(t);
  while (todo.numels())
  {
   t = (Triangle *)todo.head()->data;
   todo.removeCell(todo.head());
   if (!IS_VISITED2(t))
   {
    t1 = t->t1();
    t2 = t->t2();
    t3 = t->t3();
    if (t1 != NULL && !IS_VISITED2(t1)) todo.appendHead(t1);
    if (t2 != NULL && !IS_VISITED2(t2)) todo.appendHead(t2);
    if (t3 != NULL && !IS_VISITED2(t3)) todo.appendHead(t3);
    MARK_VISIT2(t);
    component->appendTail(t);
   }
  }
  todo.removeNodes();
  for (; n != NULL; n=n->next()) {t = ((Triangle *)n->data); if (!IS_VISITED2(t)) break;}
 }
 while (n != NULL);
 FOREACHNODE(components, n)
  if ((nt = ((List *)n->data)->numels()) > gnt) {gnt=nt; biggest = (List *)n->data;}
 FOREACHTRIANGLE(t, n) UNMARK_VISIT2(t);
 nt = 0;
 FOREACHNODE(components, n)
  if (((List *)n->data) != biggest)
   FOREACHVTTRIANGLE(((List *)n->data), t, m)
   {
    if (t->e1->v1 != NULL) t->e1->v1->e0 = NULL;
    if (t->e1->v2 != NULL) t->e1->v2->e0 = NULL;
    if (t->e2->v1 != NULL) t->e2->v1->e0 = NULL;
    if (t->e2->v2 != NULL) t->e2->v2->e0 = NULL;
    if (t->e3->v1 != NULL) t->e3->v1->e0 = NULL;
    if (t->e3->v2 != NULL) t->e3->v2->e0 = NULL;
    t->e1->v1 = t->e1->v2 = t->e2->v1 = t->e2->v2 = t->e3->v1 = t->e3->v2 = NULL;
    t->e1 = t->e2 = t->e3 = NULL;
    nt++;
   }
 FOREACHNODE(components, n) delete((List *)n->data);
 if (nt)
 {
  d_boundaries = d_handles = d_shells = 1;
  removeUnlinkedElements();
  return 1;
 }
 return 0;
}
void Triangulation::removeTriangle (Triangle * t) [inline]
Removes a triangle from the mesh. O(N).
This is equivalent to an unlinkTriangle(t) followed by a removeUnlinkedElements().
Definition at line 270 of file tin.h.
References removeUnlinkedElements(), and unlinkTriangle().
{unlinkTriangle(t); removeUnlinkedElements();}
int Triangulation::removeTriangles ()
Removes all the unlinked triangles from List T. Returns the number of removed triangles. O(N).
Definition at line 405 of file tin.cpp.
References d_boundaries, d_handles, d_shells, Node::data, Triangle::e1, Triangle::e2, Triangle::e3, List::head(), Node::next(), Node::prev(), List::removeCell(), T, and List::tail().
{
 Node *n;
 Triangle *t;
 int r = 0;
 n = T.head();
 do
 {
  t = (Triangle *)n->data;
  n = n->next();
  if (t->e1 == NULL || t->e2 == NULL || t->e3 == NULL)
  {
   r++;
   T.removeCell((n!=NULL)?(n->prev()):T.tail());
   delete t;
  }
 } while (n != NULL);
 d_boundaries = d_handles = d_shells = 1;
 return r;
}
int Triangulation::removeUnlinkedElements () [inline]
Removes all the unlinked elements from the lists. Returns the number of removed elements. O(N).
Definition at line 282 of file tin.h.
References removeEdges(), removeTriangles(), and removeVertices().
{return removeTriangles()+removeEdges()+removeVertices();}
int Triangulation::removeVertices ()
Removes all the unlinked vertices from List V. Returns the number of removed vertices. O(N).
Definition at line 459 of file tin.cpp.
References d_boundaries, d_handles, d_shells, Node::data, Vertex::e0, List::head(), Node::next(), Node::prev(), List::removeCell(), List::tail(), and V.
{
 Node *n;
 Vertex *v;
 int r = 0;
 n = V.head();
 do
 {
  v = (Vertex *)n->data;
  n = n->next();
  if (v->e0 == NULL)
  {
   r++;
   V.removeCell((n!=NULL)?(n->prev()):V.tail());
   delete v;
  }
 } while (n != NULL);
 d_boundaries = d_handles = d_shells = 1;
 return r;
}
void Triangulation::reselectSelection (Triangle * t0)
If 't0' is selected, deselect everything but the selected triangles connected to 't0'.
Definition at line 616 of file tin.cpp.
References List::appendHead(), FOREACHTRIANGLE, IS_VISITED, IS_VISITED2, MARK_VISIT2, List::numels(), List::popHead(), Triangle::t1(), Triangle::t2(), Triangle::t3(), UNMARK_VISIT, and UNMARK_VISIT2.
{
 if (!IS_VISITED(t0)) return;
 Node *n;
 Triangle *t, *s;
 List triList(t0);
 MARK_VISIT2(t0);
 while(triList.numels())
 {
  t = (Triangle *)triList.popHead();
  if ((s = t->t1()) != NULL && !IS_VISITED2(s) && IS_VISITED(s)) {triList.appendHead(s); MARK_VISIT2(s);}
  if ((s = t->t2()) != NULL && !IS_VISITED2(s) && IS_VISITED(s)) {triList.appendHead(s); MARK_VISIT2(s);}
  if ((s = t->t3()) != NULL && !IS_VISITED2(s) && IS_VISITED(s)) {triList.appendHead(s); MARK_VISIT2(s);}
 }
 FOREACHTRIANGLE(t, n) if (!IS_VISITED2(t)) UNMARK_VISIT(t); else UNMARK_VISIT2(t);
}
void Triangulation::reselectSphericalRegion (Triangle * t0, const double L, const Point * p)
Deselects all the triangles farther than L from 'p'. O(N).
A triangle is considered to be farther than L from 'p' if at least one of its three vertices is so. Point 'p' is assumed to belong to triangle 't0'. Passing 't0' avoids the non robust and expensive computation of point-in-triangle.
Definition at line 760 of file tin.cpp.
References FOREACHTRIANGLE, FOREACHVTTRIANGLE, getRegion(), IS_VISITED, IS_VISITED2, MARK_VISIT2, UNMARK_VISIT, and UNMARK_VISIT2.
{
 List *reg = getRegion(t, L, center);
 Node *n;
 Triangle *s;
 FOREACHVTTRIANGLE(reg, s, n) MARK_VISIT2(s);
 FOREACHTRIANGLE(s, n) if (IS_VISITED(s) && !IS_VISITED2(s)) UNMARK_VISIT(s);
 FOREACHVTTRIANGLE(reg, s, n) UNMARK_VISIT2(s);
 delete(reg);
}
bool Triangulation::retriangulateSelectedRegion ()
Re-triangulates the currently selected region using a Delaunay-like approach. O(SlogS).
A common plane is computed as the average of the planes of the triangles selected; then, the vertices of the region are projected on the plane and edges are iteratively swapped up to convergence (which is guaranteed on planar and simple domains). Finally, the vertices are moved back to their original positions. This operation is particularly useful to improve the quality of nearly flat regions. The selection must be simple and its Gauss map must be entirely contained in a semi-sphere. Returns TRUE on success, FALSE otherwise.
Definition at line 775 of file tin.cpp.
References List::appendHead(), Triangle::area(), Node::data, FOREACHTRIANGLE, FOREACHVTTRIANGLE, Triangle::getNormal(), getRegionInternalVertices(), List::head(), IS_VISITED, isSelectionSimple(), Node::next(), List::numels(), removeUnlinkedElements(), TriangulateHole(), unlinkTriangle(), and JMesh::warning().
{
 List ttbr;
 Node *n;
 Triangle *u;
 Point nor;
 FOREACHTRIANGLE(u, n) if (IS_VISITED(u))
  {ttbr.appendHead(u); nor = nor+(u->getNormal()*u->area());}
 if (ttbr.numels() < 2)
 {
  JMesh::warning("retriangulateRegion: Nothing to retriangulate.\n");
  return 0;
 }
 FOREACHVTTRIANGLE((&(ttbr)), u, n)
  if (u->getNormal()*nor <= 0.0)
  {
   JMesh::warning("retriangulateRegion: Too complex geometry. Can't retriangulate.\n");
   return 0;
  }
 if (!isSelectionSimple(&ttbr))
 {
  JMesh::warning("retriangulateRegion: Non-simple region. Can't retriangulate.\n");
  return 0;
 }
 List *ms = getRegionInternalVertices(&ttbr);
 FOREACHVTTRIANGLE((&(ttbr)), u, n) unlinkTriangle(u);
 Edge *e = ((Edge *)ms->head()->data);
 List *vl = ((List *)ms->head()->next()->data);
 TriangulateHole(e, vl);
 delete(vl);
 delete(ms);
 removeUnlinkedElements();
 return 1;
}
int Triangulation::retriangulateVT (Vertex * v)
Definition at line 1962 of file tin.cpp.
References List::appendTail(), Node::data, Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHVTTRIANGLE, Triangle::getNormal(), List::head(), Triangle::isDegenerate(), Node::next(), Triangle::nextEdge(), Point::normalize(), Triangle::oppositeEdge(), Triangle::overlaps(), Triangle::prevEdge(), T, Edge::t1, Edge::t2, TriangulateHole(), unlinkTriangle(), Edge::v1, Edge::v2, Vertex::VT(), and JMesh::warning().
{
 Point nor;
 Edge *e, *e0 = v->e0->t1->oppositeEdge(v);
 List *vt = v->VT();
 List oe;
 Triangle *t;
 Node *m, *n;
 int i, nt;
 FOREACHVTTRIANGLE(vt, t, m)
 {
  e = t->oppositeEdge(v);
  oe.appendTail(t->prevEdge(e));
  oe.appendTail(e);
  oe.appendTail(t->nextEdge(e));
  nor = nor+t->getNormal();
  unlinkTriangle(t);
 }
 nor.normalize();
 nt = TriangulateHole(e0, &nor);
 for (m=T.head(), i=0; i<nt; i++, m=m->next())
 {
  t = ((Triangle *)m->data);
  if (t->overlaps() || t->isDegenerate()) break;
 }
 if (i<nt)
 {
  JMesh::warning("Re-triangulation failed. Restoring..\n");
  for (m=T.head(), i=0; i<nt; i++, m=m->next())
   unlinkTriangle(((Triangle *)m->data));
  n = oe.head();
  FOREACHVTTRIANGLE(vt, t, m)
  {
   t->e1 = ((Edge *)n->data); n=n->next();
   t->e2 = ((Edge *)n->data); n=n->next();
   t->e3 = ((Edge *)n->data); n=n->next();
   t->e1->v1 = v; t->e1->v2 = (t->e2->t1 == NULL)?(t->e2->v1):(t->e2->v2);
   t->e3->v1 = v; t->e3->v2 = (t->e2->t1 == NULL)?(t->e2->v2):(t->e2->v1);
   ((t->e2->t1 == NULL)?(t->e2->t1):(t->e2->t2)) = t;
   t->e1->t1 = t;
   t->e3->t2 = t;
  }
  v->e0 = ((Triangle *)vt->head()->data)->e1;
 }
 delete(vt);
 return 1;
}
int Triangulation::save (const char * filename, bool back_approx = 0)
Save the triangle mesh to file 'filename'.
The file format is deduced from the filename extension (wrl = vrml 1.0), (iv = OpenInventor), (off = Object file format), (ply = PLY format), (tri = IMATI Ver-Tri). If 'back_approx' is set, vertex coordinates are approximated to reflect the limited precision of floating point representation in ASCII files. This should be used when coherence is necessary between in-memory and saved data. A non-zero return value is returned if errors occur.
Definition at line 200 of file io.cpp.
References coordBackApproximation(), sameString(), saveIV(), saveOBJ(), saveOFF(), savePLY(), saveSTL(), saveVerTri(), saveVRML1(), and JMesh::warning().
{
 char nfname[4096];
 strcpy(nfname, fname);
 int rv;
 size_t i=strlen(fname)-1;
 while (i>0 && fname[i] != '.') i--;
 if (i==0) {strcat(nfname,".wrl"); i=strlen(fname);}
 if (sameString(nfname+i, ".wrl")) rv = saveVRML1(nfname);
 else if (sameString(nfname+i, ".iv")) rv = saveIV(nfname);
 else if (sameString(nfname+i, ".off")) rv = saveOFF(nfname);
 else if (sameString(nfname+i, ".ply")) rv = savePLY(nfname);
 else if (sameString(nfname+i, ".obj")) rv = saveOBJ(nfname);
 else if (sameString(nfname+i, ".stl")) rv = saveSTL(nfname);
 else if (sameString(nfname+i, ".tri")) {nfname[i]='\0'; rv = saveVerTri(nfname);}
 else
 {
  JMesh::warning("Unknown extension '%s'.\n",nfname+i);
  JMesh::warning("I did not save anything.\n");
  JMesh::warning("Recognized extensions are:");
  JMesh::warning(".wrl (ASCII VRML 1.0)\n");
  JMesh::warning(".iv (Open Inventor 2.1)\n");
  JMesh::warning(".off (Object File Format)\n");
  JMesh::warning(".obj (Wavefront/Java3D)\n");
  JMesh::warning(".stl (Stereolithography)\n");
  JMesh::warning(".ply (Ascii PLY 1.0 Format)\n");
  JMesh::warning(".tri (IMATI ver-tri File Format)\n");
  return 0;
 }
 if (!rv && back_approx) coordBackApproximation();
 return rv;
}
int Triangulation::saveIV (const char * fname)
Saves IV.
Definition at line 551 of file io.cpp.
References FOREACHNODE, FOREACHVERTEX, List::numels(), PRINT_HEADING_COMMENT(), T, TVI1, TVI2, TVI3, V, JMesh::warning(), Point::x, Point::y, and Point::z.
{
 FILE *fp;
 int i;
 char triname[256];
 Node *n;
 coord *ocds;
 Vertex *v;
 strcpy(triname,fname);
 if ((fp = fopen(triname,"w")) == NULL)
 {
  JMesh::warning("Can't open '%s' for output !\n",triname);
  return 1;
 }
 fprintf(fp,"#Inventor V2.1 ascii\n\n");
 PRINT_HEADING_COMMENT(fp);
 fprintf(fp,"Separator {\n");
 fprintf(fp," Coordinate3 {\n  point [\n");
 FOREACHVERTEX(v, n) fprintf(fp,"   %f %f %f,\n",v->x,v->y,v->z);
 fprintf(fp,"  ]\n }\n");
 fprintf(fp," IndexedFaceSet {\n  coordIndex [\n");
 ocds = (coord *)malloc(sizeof(coord)*V.numels());
 i=0; FOREACHVERTEX(v, n) ocds[i++] = v->x;
 i=0; FOREACHVERTEX(v, n) v->x = i++;
 FOREACHNODE(T, n) fprintf(fp,"   %d, %d, %d, -1,\n",TVI1(n),TVI2(n),TVI3(n));
 fprintf(fp,"  ]\n }\n");
 fprintf(fp,"}\n");
 fclose(fp);
 i=0; FOREACHVERTEX(v, n) v->x = ocds[i++];
 free(ocds);
 return 0;
}
int Triangulation::saveOBJ (const char * fname)
Saves OBJ.
Definition at line 1218 of file io.cpp.
References FOREACHNODE, FOREACHVERTEX, List::numels(), PRINT_HEADING_COMMENT(), T, TVI1, TVI2, TVI3, V, JMesh::warning(), Point::x, Point::y, and Point::z.
{
 FILE *fp;
 int i;
 char triname[256];
 Node *n;
 coord *ocds;
 Vertex *v;
 strcpy(triname,fname);
 if ((fp = fopen(triname,"w")) == NULL)
 {
  JMesh::warning("Can't open '%s' for output !\n",triname);
  return 1;
 }
 PRINT_HEADING_COMMENT(fp);
 FOREACHVERTEX(v, n) fprintf(fp,"v %f %f %f\n",v->x,v->y,v->z);
 ocds = (coord *)malloc(sizeof(coord)*V.numels());
 i=0; FOREACHVERTEX(v, n) ocds[i++] = v->x;
 i=0; FOREACHVERTEX(v, n) v->x = i++;
 FOREACHNODE(T, n) fprintf(fp,"f %d %d %d\n",TVI1(n)+1,TVI2(n)+1,TVI3(n)+1);
 fclose(fp);
 i=0; FOREACHVERTEX(v, n) v->x = ocds[i++];
 free(ocds);
 return 0;
}
int Triangulation::saveOFF (const char * fname)
Saves OFF 1.0.
Definition at line 704 of file io.cpp.
References FOREACHNODE, FOREACHVERTEX, List::numels(), PRINT_HEADING_COMMENT(), T, TVI1, TVI2, TVI3, V, JMesh::warning(), Point::x, Point::y, and Point::z.
{
 FILE *fp;
 int i;
 char triname[256];
 Node *n;
 coord *ocds;
 Vertex *v;
 strcpy(triname,fname);
 if ((fp = fopen(triname,"w")) == NULL)
 {
  JMesh::warning("Can't open '%s' for output !\n",triname);
  return 1;
 }
 fprintf(fp,"OFF\n");
 PRINT_HEADING_COMMENT(fp);
 fprintf(fp,"%d %d 0\n",V.numels(),T.numels());
 FOREACHVERTEX(v, n) fprintf(fp,"%f %f %f\n",v->x,v->y,v->z);
 ocds = (coord *)malloc(sizeof(coord)*V.numels());
 i=0; FOREACHVERTEX(v, n) ocds[i++] = v->x;
 i=0; FOREACHVERTEX(v, n) v->x = i++;
 FOREACHNODE(T, n) fprintf(fp,"3 %d %d %d\n",TVI1(n),TVI2(n),TVI3(n));
 fclose(fp);
 i=0; FOREACHVERTEX(v, n) v->x = ocds[i++];
 free(ocds);
 return 0;
}
int Triangulation::savePLY (const char * fname, bool ascii = 1)
Saves PLY 1.0 (ascii or binary)
Definition at line 1089 of file io.cpp.
References FOREACHNODE, FOREACHVERTEX, List::numels(), PRINT_PLY_COMMENT(), T, TVI1, TVI2, TVI3, V, JMesh::warning(), Point::x, Point::y, and Point::z.
{
 FILE *fp;
 int i, ii[3];
 float fc[3];
 char triname[256];
 unsigned char ii0 = 3;
 Node *n;
 coord *ocds;
 Vertex *v;
 strcpy(triname,fname);
 if ((fp = fopen(triname,"w")) == NULL)
 {
  JMesh::warning("Can't open '%s' for output !\n",triname);
  return 1;
 }
 fprintf(fp,"ply\n");
 if (ascii) fprintf(fp,"format ascii 1.0\n");
 else fprintf(fp,"format binary_little_endian 1.0\n");
 PRINT_PLY_COMMENT(fp);
 fprintf(fp,"element vertex %d\n",V.numels());
 fprintf(fp,"property float x\n");
 fprintf(fp,"property float y\n");
 fprintf(fp,"property float z\n");
 fprintf(fp,"element face %d\n",T.numels());
 fprintf(fp,"property list uchar int vertex_indices\n");
 fprintf(fp,"end_header\n");
 if (ascii) FOREACHVERTEX(v, n) fprintf(fp,"%f %f %f\n",v->x,v->y,v->z);
 else FOREACHVERTEX(v, n)
 {
  fc[0]=(float)v->x; fc[1]=(float)v->y; fc[2]=(float)v->z;
  fwrite(fc, sizeof(float), 3, fp);
 }
 ocds = (coord *)malloc(sizeof(coord)*V.numels());
 i=0; FOREACHVERTEX(v, n) ocds[i++] = v->x;
 i=0; FOREACHVERTEX(v, n) v->x = i++;
 if (ascii) FOREACHNODE(T, n) fprintf(fp,"3 %d %d %d\n",TVI1(n),TVI2(n),TVI3(n));
 else FOREACHNODE(T, n)
 {
  ii[0]=TVI1(n); ii[1]=TVI2(n); ii[2]=TVI3(n);
  fwrite(&ii0, sizeof(unsigned char), 1, fp);
  fwrite(ii, sizeof(int), 3, fp);
 }
 fclose(fp);
 i=0; FOREACHVERTEX(v, n) v->x = ocds[i++];
 free(ocds);
 return 0;
}
int Triangulation::saveSTL (const char * fname)
Saves STL.
Definition at line 1339 of file io.cpp.
References FOREACHTRIANGLE, Triangle::getNormal(), Triangle::v1(), Triangle::v2(), Triangle::v3(), JMesh::warning(), Point::x, Point::y, and Point::z.
{
 FILE *fp;
 char triname[256];
 Node *n;
 Triangle *t;
 Point nor;
 strcpy(triname,fname);
 if ((fp = fopen(triname,"w")) == NULL)
 {
  JMesh::warning("Can't open '%s' for output !\n",triname);
  return 1;
 }
 fprintf(fp,"solid JMESH_STL\n");
 FOREACHTRIANGLE(t, n)
 {
  nor = t->getNormal();
  fprintf(fp," facet normal %f %f %f\n",nor.x,nor.y,nor.z);
  fprintf(fp,"  outer loop\n");
  fprintf(fp,"   vertex %f %f %f\n",t->v1()->x,t->v1()->y,t->v1()->z);
  fprintf(fp,"   vertex %f %f %f\n",t->v2()->x,t->v2()->y,t->v2()->z);
  fprintf(fp,"   vertex %f %f %f\n",t->v3()->x,t->v3()->y,t->v3()->z);
  fprintf(fp,"  endloop\n");
  fprintf(fp," endfacet\n");
 }
 fprintf(fp,"endsolid JMESH_STL\n");
 fclose(fp);
 return 0;
}
int Triangulation::saveVerTri (const char * fname)
Saves Ver-Tri.
Definition at line 744 of file io.cpp.
References Node::data, FOREACHTRIANGLE, FOREACHVERTEX, Triangle::info, Point::info, List::numels(), Node::prev(), T, Triangle::t1(), Triangle::t2(), Triangle::t3(), List::tail(), V, Triangle::v1(), Triangle::v2(), Triangle::v3(), JMesh::warning(), Point::x, Point::y, and Point::z.
{
#ifdef SAVE_INFO
 JMesh::warning("saveVerTri: Assuming that the vertex info field is allocated!\n");
 FILE *fpj;
 char jkkname[256];
#endif
 FILE *fpv, *fpt;
 int i, i1, i2, i3, a1, a2, a3;
 char vername[256], triname[256];
 Node *n;
 Vertex *v;
 Triangle *t, *t1, *t2, *t3;
 coord *ocds;
 strcpy(triname,fname);
 strcpy(vername,fname);
 strcat(triname,".tri");
 strcat(vername,".ver");
#ifdef SAVE_INFO
 strcpy(jkkname,fname);
 strcat(jkkname,".jkk");
#endif
 if ((fpv = fopen(vername,"w")) == NULL)
 {
  fprintf(stderr,"Can't open '%s' for output !\n",vername);
  return 1;
 }
 if ((fpt = fopen(triname,"w")) == NULL)
 {
  fclose(fpv);
  fprintf(stderr,"Can't open '%s' for output !\n",triname);
  return 1;
 }
#ifdef SAVE_INFO
 if ((fpj = fopen(jkkname,"w")) == NULL)
 {
  fclose(fpv); fclose(fpt);
  fprintf(stderr,"Can't open '%s' for output !\n",jkkname);
  return 1;
 }
#endif
 fprintf(fpv,"%d\n",V.numels());
 FOREACHVERTEX(v, n)
 {
  fprintf(fpv,"%f %f %f\n",v->x,v->y,v->z);
 }
 fclose(fpv);
#ifdef SAVE_INFO
 for (n=V.tail; n != NULL; n=n->prev)
 {
  v = ((Vertex *)n->data);
  fprintf(fpj,"%f\n",(*((double *)(v->info))));
 }
 fclose(fpj);
#endif
 ocds = (coord *)malloc(sizeof(coord)*V.numels());
 i=0; FOREACHVERTEX(v, n) ocds[i++] = v->x;
 i=0; FOREACHVERTEX(v, n) v->x = ++i;
 i=0; FOREACHTRIANGLE(t, n) {i++; t->info = (void *)i;}
 fprintf(fpt,"%d\n",T.numels());
 FOREACHTRIANGLE(t, n)
 {
  i1 = (int)(t->v1()->x); i2 = (int)(t->v2()->x); i3 = (int)(t->v3()->x);
  t1 = t->t1(); t2 = t->t2(); t3 = t->t3();
  a1 = (t1)?((long int)(t1->info)):(0); a2 = (t2)?((long int)(t2->info)):(0); a3 = (t3)?((long int)(t3->info)):(0);
  fprintf(fpt,"%d %d %d %d %d %d\n",i1, i2, i3, a1, a2, a3);
 }
 fclose(fpt);
 i=0; FOREACHVERTEX(v, n) v->x = ocds[i++];
 free(ocds);
 return 0;
}
int Triangulation::saveVRML1 (const char * fname, const int mode = 0)
Saves the triangle mesh to a VRML 1.0 file. The value of 'mode' specifies whether to use additional information attached to mesh elements in order to assign them a proper color. IO_CSAVE_OVERALL assigns a unique color for the entire mesh (default). IO_CSAVE_PERFACE assigns a color to each triangle depending on the value of its 'info' field. IO_CSAVE_PERVERTEX assigns a color to each vertex depending on the value of its 'info' field. IO_CSAVE_PERFACE_INDEXED assigns one of five base colors to each triangle depending on the value of its 'mask' field. IO_CSAVE_PERVERTEX_INDEXED assigns one of five base colors to each vertex depending on the value of its 'mask' field.
Definition at line 597 of file io.cpp.
References JMesh::error(), FOREACHTRIANGLE, FOREACHVERTEX, Point::info, Triangle::info, IO_CSAVE_OVERALL, IO_CSAVE_PERFACE, IO_CSAVE_PERFACE_INDEXED, IO_CSAVE_PERVERTEX, IO_CSAVE_PERVERTEX_INDEXED, Vertex::mask, Triangle::mask, List::numels(), PRINT_HEADING_COMMENT(), V, Triangle::v1(), Triangle::v2(), Triangle::v3(), JMesh::warning(), Point::x, Point::y, and Point::z.
{
 FILE *fp;
 int i;
 unsigned int pkc;
 char triname[256];
 Node *n;
 Vertex *v;
 Triangle *t;
 coord *ocds;
 strcpy(triname,fname);
 if ((fp = fopen(triname,"w")) == NULL)
 {
  JMesh::warning("Can't open '%s' for output !\n",triname);
  return 1;
 }
 fprintf(fp,"#VRML V1.0 ascii\n\n");
 PRINT_HEADING_COMMENT(fp);
 fprintf(fp,"Separator {\n");
 fprintf(fp," Coordinate3 {\n  point [\n");
 FOREACHVERTEX(v, n) fprintf(fp,"   %f %f %f,\n",v->x,v->y,v->z);
 fprintf(fp,"  ]\n }\n");
 ocds = (coord *)malloc(sizeof(coord)*V.numels());
 i=0; FOREACHVERTEX(v, n) {ocds[i] = v->x; v->x = i++;}
 switch (mode)
 {
  case IO_CSAVE_OVERALL:
   fprintf(fp,"Material {\n diffuseColor 0.6 0.6 0.6\n}\n");
   break;
  case IO_CSAVE_PERFACE:
   fprintf(fp,"Material {\n diffuseColor [\n");
   FOREACHTRIANGLE(t, n)
   {
    pkc = (unsigned int)((j_voidint)t->info);
    fprintf(fp,"  %f %f %f,\n",((pkc>>24)&0x000000ff)/255.0,((pkc>>16)&0x000000ff)/255.0,((pkc>>8)&0x000000ff)/255.0);
   }
   fprintf(fp," ]\n}\nMaterialBinding {\n value PER_FACE_INDEXED\n}\n");
   break;
  case IO_CSAVE_PERVERTEX:
   fprintf(fp,"Material {\n diffuseColor [\n");
   FOREACHVERTEX(v, n)
   {
    pkc = (unsigned int)((j_voidint)v->info);
    fprintf(fp,"  %f %f %f,\n",((pkc>>24)&0x000000ff)/255.0,((pkc>>16)&0x000000ff)/255.0,((pkc>>8)&0x000000ff)/255.0);
   }
   fprintf(fp," ]\n}\nMaterialBinding {\n value PER_VERTEX_INDEXED\n}\n");
   break;
  case IO_CSAVE_PERFACE_INDEXED:
   fprintf(fp,"Material {\n diffuseColor [\n");
   fprintf(fp,"1.0 1.0 1.0,\n1.0 0.0 0.0,\n0.0 1.0 0.0,\n0.0 0.0 1.0,\n 0.8 0.8 0.0\n");
   fprintf(fp," ]\n}\nMaterialBinding {\n value PER_FACE_INDEXED\n}\n");
   break;
  case IO_CSAVE_PERVERTEX_INDEXED:
   fprintf(fp,"Material {\n diffuseColor [\n");
   fprintf(fp,"1.0 1.0 1.0,\n1.0 0.0 0.0,\n0.0 1.0 0.0,\n0.0 0.0 1.0,\n 0.8 0.8 0.0\n");
   fprintf(fp," ]\n}\nMaterialBinding {\n value PER_VERTEX_INDEXED\n}\n");
   break;
  default: JMesh::error("Triangulation::saveVRML1. Unknown mode %d\n",mode);
 }
 fprintf(fp," IndexedFaceSet {\n  coordIndex [\n");
 FOREACHTRIANGLE(t, n)
  fprintf(fp,"   %d, %d, %d, -1,\n",(int)t->v1()->x,(int)t->v2()->x,(int)t->v3()->x);
 fprintf(fp,"  ]\n");
 if (mode != IO_CSAVE_OVERALL)
 {
  fprintf(fp,"  materialIndex [\n");
  switch (mode)
  {
   case IO_CSAVE_PERFACE_INDEXED:
    FOREACHTRIANGLE(t, n) fprintf(fp,"   %d,\n",t->mask);
    break;
   case IO_CSAVE_PERVERTEX_INDEXED:
    FOREACHTRIANGLE(t, n) fprintf(fp,"   %d, %d, %d, -1,\n",t->v1()->mask,t->v2()->mask,t->v3()->mask);
    break;
   case IO_CSAVE_PERFACE:
    i=0; FOREACHTRIANGLE(t, n) fprintf(fp,"   %d,\n",i++);
    break;
   case IO_CSAVE_PERVERTEX:
    FOREACHTRIANGLE(t, n) fprintf(fp,"   %d, %d, %d, -1,\n",(int)t->v1()->x,(int)t->v2()->x,(int)t->v3()->x);
    break;
  }
  fprintf(fp,"  ]\n");
 }
 fprintf(fp," }\n}\n");
 fclose(fp);
 i=0; FOREACHVERTEX(v, n) v->x = ocds[i++];
 free(ocds);
 return 0;
}
int Triangulation::selectBoundaryTriangles ()
Selects all the triangles having at least one boundary vertex. O(N). Returns the number of selected triangles.
Definition at line 516 of file tin.cpp.
References FOREACHEDGE, FOREACHTRIANGLE, FOREACHVERTEX, IS_VISITED, Edge::isOnBoundary(), MARK_VISIT, UNMARK_VISIT, Triangle::v1(), Edge::v1, Triangle::v2(), Edge::v2, and Triangle::v3().
{
 Node *n;
 Edge *e;
 Vertex *v, *v1, *v2, *v3;
 Triangle *t;
 int ns=0;
 FOREACHEDGE(e, n) if (e->isOnBoundary()) {MARK_VISIT(e->v1); MARK_VISIT(e->v2);}
 FOREACHTRIANGLE(t, n) if (!IS_VISITED(t))
 {
  v1 = t->v1(); v2 = t->v2(); v3 = t->v3();
  if (IS_VISITED(v1) || IS_VISITED(v2) || IS_VISITED(v3)) {MARK_VISIT(t); ns++;}
 }
 FOREACHVERTEX(v, n) UNMARK_VISIT(v);
 return ns;
}
int Triangulation::selectConnectedComponent (Triangle * t0, bool stop_on_sharp = 0)
Selects all the triangles of the connected component containing t0. O(N).
If 'stop_on_sharp', expansion from 't0' brakes at tagged sharp edges. Returns the number of selected triangles.
Definition at line 889 of file tin.cpp.
References List::appendHead(), Triangle::e1, Triangle::e2, Triangle::e3, IS_SHARPEDGE, IS_VISITED, MARK_VISIT, List::numels(), List::popHead(), Triangle::t1(), Triangle::t2(), and Triangle::t3().
{
 List todo;
 Triangle *t, *t1, *t2, *t3;
 int ns = 0;
 todo.appendHead(t0);
 while (todo.numels())
 {
  t = (Triangle *)todo.popHead();
  if (!IS_VISITED(t))
  {
   t1 = t->t1(); t2 = t->t2(); t3 = t->t3();
   if (t1 != NULL && !IS_VISITED(t1) && (!(sos && IS_SHARPEDGE(t->e1)))) todo.appendHead(t1);
   if (t2 != NULL && !IS_VISITED(t2) && (!(sos && IS_SHARPEDGE(t->e2)))) todo.appendHead(t2);
   if (t3 != NULL && !IS_VISITED(t3) && (!(sos && IS_SHARPEDGE(t->e3)))) todo.appendHead(t3);
   MARK_VISIT(t); ns++;
  }
 }
 return ns;
}
int Triangulation::selectSphericalRegion (Triangle * t0, const double L, const Point * p)
Marks all the triangles within distance L from 'p' as selected. O(output).
A triangle is considered to be within distance L from 'p' only if all its three vertices are so. Point 'p' is assumed to belong to triangle 't0', which is required to limit the complexity to the size of the selected region. Returns the number of selected triangles.
Definition at line 727 of file tin.cpp.
References FOREACHVTTRIANGLE, getRegion(), and MARK_VISIT.
{
 List *reg = getRegion(t, L, center);
 Node *n;
 Triangle *s;
 int nt=0;
 FOREACHVTTRIANGLE(reg, s, n) {MARK_VISIT(s); nt++;}
 delete(reg);
 return nt;
}
int Triangulation::selectTinyHandles (double L)
Definition at line 609 of file checkAndRepair.cpp.
References List::appendHead(), createSubMeshFromSelection(), Triangle::e1, Triangle::e2, Triangle::e3, FOREACHEDGE, FOREACHTRIANGLE, FOREACHVERTEX, FOREACHVTTRIANGLE, Triangle::getCenter(), handles(), JMesh::info(), Triangle::info, invertSelection(), IS_VISITED2, Vertex::isOnBoundary(), Triangle::leftTriangle(), MARK_VISIT2, Edge::mask, Vertex::mask, Triangle::mask, Vertex::nextBoundaryEdge(), Triangle::nextEdge(), Edge::oppositeVertex(), Triangle::oppositeVertex(), List::popHead(), Triangle::prevEdge(), Triangle::rightTriangle(), selectSphericalRegion(), shells(), T, Edge::t1, Edge::t2, UNMARK_VISIT, UNMARK_VISIT2, unmarkEverything(), Edge::v1, Triangle::v1(), Edge::v2, Triangle::v2(), Triangle::v3(), and JMesh::warning().
{
 if (shells() > 1) {JMesh::warning("Sorry. This feature was not implemented for multi-component meshes.\n"); return 1;}
 int bdrr, nh = 0;
 Triangle *t, *lt, *rt;
 Edge *e, *se, *le, *re, *gate = NULL;
 Vertex *v, *ov;
 Node *n, *m;
 FOREACHTRIANGLE(t, n)
  if (!t->v1()->isOnBoundary() && !t->v2()->isOnBoundary() && !t->v3()->isOnBoundary()) break;
 if (n==NULL) return 1;
 unmarkEverything();
 t->mask = t->v1()->mask = t->v2()->mask = t->v3()->mask = 1;
 t->e1->mask = t->e2->mask = t->e3->mask = 1;
 List todo((gate = t->e1));
 while ((gate = (Edge *)todo.popHead()) != NULL)
 {
  while(1)
  {
   bdrr = 0;
   t = (gate->t1 == NULL || gate->t1->mask)?((gate->t2 == NULL || gate->t2->mask)?(NULL):(gate->t2)):(gate->t1);
   if (t == NULL)
   {
    if (gate->t1) MARK_VISIT2(gate->t1); else MARK_VISIT2(gate->t2);
    nh++;
    break;
   }
   t->mask = 1; t->e1->mask = t->e2->mask = t->e3->mask = 1;
   le = t->prevEdge(gate);
   re = t->nextEdge(gate);
   lt = t->leftTriangle(gate);
   rt = t->rightTriangle(gate);
   ov = t->oppositeVertex(gate);
   if (lt && rt && !lt->mask && !rt->mask && !ov->mask && ov->isOnBoundary())
   {
    bdrr = 1;
    e = se = ov->nextBoundaryEdge();
    v = ov;
    do
    {
     e->mask = e->v1->mask = e->v2->mask = 1;
     v = e->oppositeVertex(v);
     e = v->nextBoundaryEdge();
    } while (e != se);
   }
   if (ov->mask)
   {
    if ((!lt || lt->mask) && (!rt || rt->mask)) break;  // E
    else if ((!lt || lt->mask)) gate = re;      // L
    else if ((!rt || rt->mask)) gate = le;      // R
    else {if (!bdrr) todo.appendHead(le); gate = re;}   // S
   }
   else gate = re;                  // C
   t->v1()->mask = t->v2()->mask = t->v3()->mask = 1;
  }
 }
 nh /= 2;
 FOREACHTRIANGLE(t, n) UNMARK_VISIT(t);
 FOREACHEDGE(e, n) UNMARK_VISIT(e);
 FOREACHVERTEX(v, n) UNMARK_VISIT(v);
 Point center;
 Triangulation *stin;
 int sh=0;
 FOREACHTRIANGLE(t, n) if (IS_VISITED2(t))
 {
  center = t->getCenter();
  selectSphericalRegion(t, L, &center);
 }
 FOREACHTRIANGLE(t, n) if (IS_VISITED2(t))
 {
  UNMARK_VISIT2(t);
  if ((stin = createSubMeshFromSelection(t)) != NULL)
  {
   if (stin->handles() < 1) invertSelection(t);
   else
   {
    sh += stin->handles();
    FOREACHVTTRIANGLE((&(stin->T)), lt, m) {rt = (Triangle *)lt->info; UNMARK_VISIT2(rt);}
   }
   delete(stin);
  }
 }
 JMesh::info("Selected %d out of %d handles\n",sh,nh);
 JMesh::info("Radius: %f\n",L);
 return 0;
}
void Triangulation::sharpEdgeTagging (const double t)
Tag sharp edges based on threshold angle. O(N).
Tag as sharp all the edges in which the normals of the two incident triangles form an angle greater than 't'.
Definition at line 1172 of file tin.cpp.
References Edge::curvature(), FOREACHEDGE, TAG_SHARPEDGE, and UNTAG_SHARPEDGE.
{
 Node *n;
 Edge *e;
 FOREACHEDGE(e, n)
  if (e->curvature() > ta) TAG_SHARPEDGE(e);
  else UNTAG_SHARPEDGE(e);
}
int Triangulation::shells () [inline]
Get the number of connected components of the triangle mesh. O(1) or O(N).
Definition at line 110 of file tin.h.
References d_shells, eulerUpdate(), and n_shells.
{if (d_shells) eulerUpdate(); return n_shells;}
void Triangulation::shrinkSelection ()
Shrinks the current selection of one triangle in width. O(N).
Each triangle sharing at least one vertex with a currently unselected triangle becomes unselected.
Definition at line 565 of file tin.cpp.
References FOREACHTRIANGLE, FOREACHVERTEX, IS_VISITED, MARK_VISIT, UNMARK_VISIT, Triangle::v1(), Triangle::v2(), and Triangle::v3().
{
 Node *n;
 Vertex *v, *v1, *v2, *v3;
 Triangle *t;
 FOREACHTRIANGLE(t, n) if (!IS_VISITED(t))
 {
  v1 = t->v1(); v2 = t->v2(); v3 = t->v3();
  MARK_VISIT(v1); MARK_VISIT(v2); MARK_VISIT(v3);
 }
 FOREACHTRIANGLE(t, n) if (IS_VISITED(t))
 {
  v1 = t->v1(); v2 = t->v2(); v3 = t->v3();
  if (IS_VISITED(v1) || IS_VISITED(v2) || IS_VISITED(v3)) UNMARK_VISIT(t);
 }
 FOREACHVERTEX(v, n) UNMARK_VISIT(v);
}
Vertex * Triangulation::splitEdge (Edge * e, Point * p, bool copy_mask = 0)
Definition at line 2016 of file tin.cpp.
References List::appendHead(), E, Vertex::e0, Triangle::mask, Edge::mask, Triangle::nextEdge(), Triangle::oppositeVertex(), Triangle::prevEdge(), Triangle::replaceEdge(), Edge::replaceTriangle(), T, Edge::t1, Edge::t2, V, Edge::v1, Edge::v2, Point::x, Point::y, and Point::z.
{
 if ((*p)==(*(e->v1))) return e->v1;
 if ((*p)==(*(e->v2))) return e->v2;
 Vertex *v3 = (e->t1 != NULL)?(e->t1->oppositeVertex(e)):(NULL);
 Vertex *v4 = (e->t2 != NULL)?(e->t2->oppositeVertex(e)):(NULL);
 Edge *be1 = (e->t1 != NULL)?(e->t1->nextEdge(e)):(NULL);
 Edge *be4 = (e->t2 != NULL)?(e->t2->prevEdge(e)):(NULL);
 Vertex *v = new Vertex(p->x, p->y, p->z);
 Edge *ne = new Edge(v, e->v2);
 Edge *ne1 = (e->t1 != NULL)?(new Edge(v, v3)):(NULL);
 Edge *ne2 = (e->t2 != NULL)?(new Edge(v, v4)):(NULL);
 Triangle *nt1 = (e->t1 != NULL)?(new Triangle(ne1, ne,be1)):(NULL);
 Triangle *nt2 = (e->t2 != NULL)?(new Triangle(ne, ne2,be4)):(NULL);
 ne->t1 = nt1; ne->t2 = nt2;
 if (ne1 != NULL) {ne1->t1 = e->t1; ne1->t2 = nt1;}
 if (ne2 != NULL) {ne2->t1 = nt2; ne2->t2 = e->t2;}
 if (be1 != NULL) be1->replaceTriangle(e->t1, nt1);
 if (be4 != NULL) be4->replaceTriangle(e->t2, nt2);
 e->v2->e0 = (be1 != NULL)?(be1):(be4);
 e->v2 = v;
 v->e0 = e;
 if (e->t1 != NULL) e->t1->replaceEdge(be1, ne1);
 if (e->t2 != NULL) e->t2->replaceEdge(be4, ne2);
 if (copy_mask)
 {
  ne->mask = e->mask;
  if (nt1 != NULL) nt1->mask = e->t1->mask;
  if (nt2 != NULL) nt2->mask = e->t2->mask;
 }
 V.appendHead(v);
 E.appendHead(ne);
 if (ne1 != NULL) E.appendHead(ne1);
 if (ne2 != NULL) E.appendHead(ne2);
 if (nt1 != NULL) T.appendHead(nt1);
 if (nt2 != NULL) T.appendHead(nt2);
 return v;
}
Vertex * Triangulation::splitTriangle (Triangle * t, Point * p, bool only_proper = 0)
Definition at line 2064 of file tin.cpp.
References List::appendHead(), E, Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, Point::getAngle(), M_PI, Triangle::replaceEdge(), Edge::replaceTriangle(), splitEdge(), T, Edge::t1, Edge::t2, V, Triangle::v1(), Triangle::v2(), Triangle::v3(), Point::x, Point::y, and Point::z.
{
 Vertex *v1 = t->v1();
 Vertex *v2 = t->v2();
 Vertex *v3 = t->v3();
 if ((*p) == (*v1)) return (only_proper)?(NULL):v1;
 if ((*p) == (*v2)) return (only_proper)?(NULL):v2;
 if ((*p) == (*v3)) return (only_proper)?(NULL):v3;
 if (!only_proper)
 {
  if (p->getAngle(v1,v2) == M_PI) return splitEdge(t->e2, p);
  if (p->getAngle(v2,v3) == M_PI) return splitEdge(t->e3, p);
  if (p->getAngle(v3,v1) == M_PI) return splitEdge(t->e1, p);
 }
 Vertex *v = new Vertex(p->x, p->y, p->z);
 Edge *ne1 = new Edge(v, v1);
 Edge *ne2 = new Edge(v, v2);
 Edge *ne3 = new Edge(v, v3);
 Triangle *nt1 = new Triangle(ne2, t->e3,ne3);
 Triangle *nt2 = new Triangle(ne3, t->e1,ne1);
 t->e3->replaceTriangle(t, nt1);
 t->e1->replaceTriangle(t, nt2);
 t->replaceEdge(t->e3, ne2);
 t->replaceEdge(t->e1, ne1);
 ne1->t1 = t; ne1->t2 = nt2;
 ne2->t1 = nt1; ne2->t2 = t;
 ne3->t1 = nt2; ne3->t2 = nt1;
 v->e0 = ne1;
 V.appendHead(v);
 E.appendHead(ne1);
 E.appendHead(ne2);
 E.appendHead(ne3);
 T.appendHead(nt1);
 T.appendHead(nt2);
 return v;
}
int Triangulation::StarTriangulateHole (Edge * e)
Definition at line 1632 of file tin.cpp.
References List::appendHead(), CreateEdge(), CreateTriangle(), Node::data, FOREACHVVVERTEX, Vertex::getEdge(), List::head(), Edge::isOnBoundary(), Node::next(), Vertex::nextOnBoundary(), List::numels(), V, and Edge::v1.
{
 if (!e->isOnBoundary()) return 0;
 List bvs;
 Node *n;
 Edge *e1, *e2, *e3;
 Point np;
 Vertex *v, *nv, *v1, *v2;
 int nt=0;
 v = e->v1;
 do
 {
  bvs.appendHead(v);
  v = v->nextOnBoundary();
 } while (v != e->v1);
 FOREACHVVVERTEX((&(bvs)), v, n) np = np+(*v);
 np = np/bvs.numels();
 nv = new Vertex(&np);
 V.appendHead(nv);
 v1 = ((Vertex *)bvs.head()->data);
 e1 = CreateEdge(nv, v1);
 for (n=bvs.head()->next(); n!=NULL; n=n->next())
 {
  v2 = ((Vertex *)n->data);
  e2 = CreateEdge(nv, v2);
  e3 = v1->getEdge(v2);
  CreateTriangle(e1, e2, e3);
  nt++;
  v1 = v2;
  e1 = e2;
 }
 v2 = ((Vertex *)bvs.head()->data);
 e2 = nv->getEdge(v2);
 e3 = v1->getEdge(v2);
 CreateTriangle(e1, e2, e3);
 nt++;
 return nt;
}
Triangle * Triangulation::topTriangle (Triangle * t0)
Return the triangle with the maximum 'z' coordinate in the shell containing 't0'. O(N).
Useful for orienting meshes bounding solids.
Definition at line 1460 of file tin.cpp.
References List::appendHead(), COORD_MAX, Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHVEEDGE, FOREACHVTTRIANGLE, FOREACHVVVERTEX, Triangle::getNormal(), Edge::hasVertex(), IS_BIT, IS_VISITED, Edge::length(), MARK_BIT, MARK_VISIT, List::numels(), Edge::oppositeVertex(), List::popHead(), Edge::t1, Triangle::t1(), Edge::t2, Triangle::t2(), Triangle::t3(), UNMARK_BIT, UNMARK_VISIT, Triangle::v1(), Triangle::v2(), Triangle::v3(), and Point::z.
{
 Node *n;
 Vertex *v, *hv = NULL, *v1, *v2, *v3;
 Edge *e, *fe = NULL;
 coord az, Mz = -COORD_MAX;
 Triangle *t, *t1, *t2, *t3;
 List *ve, todo, tlist, elist, vlist;
 todo.appendHead(t0); MARK_BIT(t0,2);
 while (todo.numels())
 {
  t = (Triangle *)todo.popHead(); tlist.appendHead(t);
  t1 = t->t1(); t2 = t->t2(); t3 = t->t3();
  v1 = t->v1(); v2 = t->v2(); v3 = t->v3();
  if (!IS_VISITED(v1)) {MARK_VISIT(v1); vlist.appendHead(v1);}
  if (!IS_VISITED(v2)) {MARK_VISIT(v2); vlist.appendHead(v2);}
  if (!IS_VISITED(v3)) {MARK_VISIT(v3); vlist.appendHead(v3);}
  if (!IS_VISITED(t->e1)) {MARK_VISIT(t->e1); elist.appendHead(t->e1);}
  if (!IS_VISITED(t->e2)) {MARK_VISIT(t->e2); elist.appendHead(t->e2);}
  if (!IS_VISITED(t->e3)) {MARK_VISIT(t->e3); elist.appendHead(t->e3);}
  if (t1 != NULL && !IS_BIT(t1,2)) {MARK_BIT(t1,2); todo.appendHead(t1);}
  if (t2 != NULL && !IS_BIT(t2,2)) {MARK_BIT(t2,2); todo.appendHead(t2);}
  if (t3 != NULL && !IS_BIT(t3,2)) {MARK_BIT(t3,2); todo.appendHead(t3);}
 }
 ve = new List;
 FOREACHVVVERTEX((&(vlist)), v, n) {UNMARK_VISIT(v); if ((az = v->z) > Mz) {Mz=az; hv = v;}}
 Mz = COORD_MAX;
 FOREACHVEEDGE((&(elist)), e, n) {UNMARK_VISIT(e); if (e->hasVertex(hv) && e->length() != 0) ve->appendHead(e);}
 FOREACHVTTRIANGLE((&(tlist)), t, n) UNMARK_BIT(t, 2);
 FOREACHVEEDGE(ve, e, n)
  if ((az = (hv->z - e->oppositeVertex(hv)->z)/e->length()) < Mz) {Mz=az; fe = e;}
 delete(ve);
 if (fe == NULL) fe = hv->e0;
 if (fe->t1 == NULL || fe->t2 == NULL) return NULL;
 return (fabs(fe->t1->getNormal().z) > fabs(fe->t2->getNormal().z))?(fe->t1):(fe->t2);
}
void Triangulation::transform (const Matrix4x4 & m)
Transform the mesh geometry using the transformation matrix m. O(N).
Definition at line 1282 of file tin.cpp.
References FOREACHVERTEX, Matrix4x4::matrix, Point::x, Point::y, and Point::z.
{
 Node *n;
 Vertex *v;
 double x,y,z,w;
 FOREACHVERTEX(v, n)
 {
  x = ((*v)*Point(m.matrix[0][0],m.matrix[1][0],m.matrix[2][0]))+m.matrix[3][0];
  y = ((*v)*Point(m.matrix[0][1],m.matrix[1][1],m.matrix[2][1]))+m.matrix[3][1];
  z = ((*v)*Point(m.matrix[0][2],m.matrix[1][2],m.matrix[2][2]))+m.matrix[3][2];
  w = ((*v)*Point(m.matrix[0][3],m.matrix[1][3],m.matrix[2][3]))+m.matrix[3][3];
  v->x = x/w; v->y = y/w; v->z = z/w;
 }
}
void Triangulation::transformShell (Triangle * t0, const Matrix4x4 & m)
Transform the vertices of the shell containing 't0' using the matrix m. O(S).
Definition at line 1102 of file tin.cpp.
References List::appendHead(), IS_VISITED, MARK_VISIT, Matrix4x4::matrix, List::numels(), List::popHead(), Triangle::t1(), Triangle::t2(), Triangle::t3(), UNMARK_VISIT, Triangle::v1(), Triangle::v2(), Triangle::v3(), Point::x, Point::y, and Point::z.
{
 List todo(t0), st, sv;
 Triangle *t, *nt;
 Vertex *v;
 double x, y, z, w;
 while (todo.numels())
 {
  t = (Triangle *)todo.popHead();
  st.appendHead(t);
  nt=t->t1(); if (nt != NULL && !IS_VISITED(nt)) {MARK_VISIT(nt); todo.appendHead(nt);}
  nt=t->t2(); if (nt != NULL && !IS_VISITED(nt)) {MARK_VISIT(nt); todo.appendHead(nt);}
  nt=t->t3(); if (nt != NULL && !IS_VISITED(nt)) {MARK_VISIT(nt); todo.appendHead(nt);}
 }
 while (st.numels())
 {
  t = (Triangle *)st.popHead();
  UNMARK_VISIT(t);
  v = t->v1(); if (!IS_VISITED(v)) {MARK_VISIT(v); sv.appendHead(v);}
  v = t->v2(); if (!IS_VISITED(v)) {MARK_VISIT(v); sv.appendHead(v);}
  v = t->v3(); if (!IS_VISITED(v)) {MARK_VISIT(v); sv.appendHead(v);}
 }
 while (sv.numels())
 {
  v = (Vertex *)sv.popHead();
  UNMARK_VISIT(v);
  x = ((*v)*Point(m.matrix[0][0],m.matrix[1][0],m.matrix[2][0]))+m.matrix[3][0];
  y = ((*v)*Point(m.matrix[0][1],m.matrix[1][1],m.matrix[2][1]))+m.matrix[3][1];
  z = ((*v)*Point(m.matrix[0][2],m.matrix[1][2],m.matrix[2][2]))+m.matrix[3][2];
  w = ((*v)*Point(m.matrix[0][3],m.matrix[1][3],m.matrix[2][3]))+m.matrix[3][3];
  v->x = x/w; v->y = y/w; v->z = z/w;
 }
}
int Triangulation::TriangulateHole (Edge * e, List * vl)
Definition at line 1740 of file tin.cpp.
References List::appendHead(), List::appendList(), List::appendTail(), Node::data, Edge::delaunayMinAngle(), E, Vertex::e0, EulerEdgeTriangle(), FOREACHNODE, FOREACHVEEDGE, FOREACHVVVERTEX, Vertex::getAngleForTriangulation(), Vertex::getEdge(), List::head(), IS_VISITED, Point::isNull(), Edge::isOnBoundary(), MARK_VISIT, Node::next(), Vertex::nextOnBoundary(), Point::normalize(), List::numels(), Node::prev(), Point::project(), List::removeCell(), Edge::swap(), T, List::tail(), UNMARK_VISIT, Edge::v1, JMesh::warning(), watsonInsert(), Point::x, Point::y, and Point::z.
{
 if (!e->isOnBoundary()) return 0;
 List bvs, ovbs, nedg;
 Node *n, *gn = NULL;
 Edge *e1, *e2;
 Vertex *v, *v1, *v2;
 double ang, gang;
 int nt = 0, neb;
 v = e->v1;
 do
 {
  bvs.appendHead(v);
  v = v->nextOnBoundary();
 } while (v != e->v1);
 ovbs.appendList(&bvs);
 while (bvs.numels() > 2) // While there are more than two boundary vertices
 {
  gang = DBL_MAX;
  FOREACHVVVERTEX((&(bvs)), v, n)
   if (!IS_VISITED(v) && v->e0 && (ang = v->getAngleForTriangulation()) < gang)
    {gang = ang; gn = n;}
  if (gang == DBL_MAX)
  {
   JMesh::warning("TriangulateHole: Can't complete the triangulation.\n");
   FOREACHVVVERTEX((&(bvs)), v, n) UNMARK_VISIT(v);
   return 0;
  }
  v = ((Vertex *)gn->data);
  v1 = (Vertex *)((gn->next() != NULL)?(gn->next()):(bvs.head()))->data;
  v2 = (Vertex *)((gn->prev() != NULL)?(gn->prev()):(bvs.tail()))->data;
  e1 = v->getEdge(v1);
  e2 = v->getEdge(v2);
  neb = E.numels();
  if (!EulerEdgeTriangle(e1,e2)) MARK_VISIT(v);
  else
  {
   bvs.removeCell(gn);
   UNMARK_VISIT(v1);
   UNMARK_VISIT(v2);
   nt++;
   if (E.numels() > neb) nedg.appendHead(E.head()->data);
  }
 }
// if (nt < 2) return nt;
 // Calcolo una normale per il buco come media dei nuovi triangoli
 int i;
 Point nor;
 for (i=0, n=T.head(); i<nt; i++, n=n->next()) nor = nor+((Triangle *)n->data)->getNormal();
 if (nor.isNull())
 {
  JMesh::warning("TriangulateHole: Unable to compute an average normal. Can't optimize.\n");
  return nt;
 }
 nor.normalize();
 // Memorizzo da qualche parte la posizione originale dei vertici
 // e Proietto il boundary sul piano con normale quella appena calcolata
 coord *ovps = (coord *)malloc((ovbs.numels())*3*sizeof(coord));
 int j = 0;
 FOREACHVVVERTEX((&(ovbs)), v, n)
 {
  ovps[j++] = v->x; ovps[j++] = v->y; ovps[j++] = v->z;
  v->project(&nor);
 }
 // Proietto i punti interni sul piano d'appoggio
 Point *p;
 coord *ovpsi = (coord *)malloc((vl->numels())*3*sizeof(coord));
 j = 0;
 FOREACHNODE((*vl), n)
 {
  p = ((Point *)n->data);
  ovpsi[j++] = p->x; ovpsi[j++] = p->y; ovpsi[j++] = p->z;
 }
 FOREACHNODE((*vl), n)
 {
  p = ((Point *)n->data);
  p->project(&nor);
 }
 // Ottimizzo secondo Delaunay vincolato al boundary la nuova regione
 int sw;
 do
 {
  sw = 0;
  FOREACHVEEDGE((&(nedg)), e1, n)
  {
   ang = e1->delaunayMinAngle();
   if (e1->swap())
    {if (e1->delaunayMinAngle() <= ang) e1->swap(1); else sw++;}
  }
 } while (sw);
 // Inserisco i punti interni
 int ntt = T.numels()-nt;
 List ivs;
 FOREACHNODE((*vl), n)
 {
  p = ((Point *)n->data);
  ivs.appendTail(watsonInsert(p, &T, T.numels()-ntt));
 }
 nt = (T.numels() - ntt);
 // Riporto i vertici interni al loro posto
 j=0; FOREACHVVVERTEX((&(ivs)), v, n)
 {
  if (v != NULL)
  {
   v->x = ovpsi[j++]; v->y = ovpsi[j++]; v->z = ovpsi[j++];
  } else j+=3;
 }
 free(ovpsi);
 // Riporto i vertici del boundary al loro posto
 j=0; FOREACHVVVERTEX((&(ovbs)), v, n)
 {
  v->x = ovps[j++]; v->y = ovps[j++]; v->z = ovps[j++];
 }
 free(ovps);
 return nt;
}
int Triangulation::TriangulateHole (Edge * e, Point * nor)
Definition at line 1681 of file tin.cpp.
References List::appendHead(), Node::data, Edge::delaunayMinAngle(), E, Vertex::e0, EulerEdgeTriangle(), FOREACHVVVERTEX, Vertex::getAngleOnAveragePlane(), Vertex::getEdge(), List::head(), IS_VISITED, Edge::isOnBoundary(), MARK_VISIT, Node::next(), Vertex::nextOnBoundary(), List::numels(), Node::prev(), List::removeCell(), Edge::swap(), List::tail(), UNMARK_VISIT, Edge::v1, and JMesh::warning().
{
 if (!e->isOnBoundary()) return 0;
 List bvs;
 Node *n, *gn = NULL;
 Edge *e1, *e2;
 Vertex *v, *v1, *v2;
 double ang, gang;
 int nt = 0;
 v = e->v1;
 do
 {
  bvs.appendHead(v);
  v = v->nextOnBoundary();
 } while (v != e->v1);
 while (bvs.numels() > 2)
 {
  gang = DBL_MAX;
  FOREACHVVVERTEX((&(bvs)), v, n)
   if (!IS_VISITED(v) && v->e0 && (ang = v->getAngleOnAveragePlane(nor)) < gang)
    {gang = ang; gn = n;}
  if (gang == DBL_MAX)
  {
   JMesh::warning("TriangulateHole: Can't complete the triangulation.\n");
   FOREACHVVVERTEX((&(bvs)), v, n) UNMARK_VISIT(v);
   return 0;
  }
  v = ((Vertex *)gn->data);
  v1 = (Vertex *)((gn->next() != NULL)?(gn->next()):(bvs.head()))->data;
  v2 = (Vertex *)((gn->prev() != NULL)?(gn->prev()):(bvs.tail()))->data;
  e1 = v->getEdge(v1);
  e2 = v->getEdge(v2);
  if (!EulerEdgeTriangle(e1,e2)) MARK_VISIT(v);
  else {bvs.removeCell(gn); UNMARK_VISIT(v1); UNMARK_VISIT(v2); nt++;}
 }
 int i, skips;
 do
 {
  skips = 0;
  for (n=E.head(), i=2*nt*nt; i<nt; n=n->next(), i--)
  {
   e = ((Edge *)n->data);
   ang = e->delaunayMinAngle();
   if (e->swap())
    {if (e->delaunayMinAngle() <= ang) e->swap(1); else skips++;}
  }
  if (i < 0) {JMesh::warning("Optimization is taking too long. I give up.\n"); break;}
 } while (skips);
 return nt;
}
void Triangulation::unlinkTriangle (Triangle * t)
Unlinks a triangle from the mesh. O(1).
Resulting isolated vertices and edges are unlinked too. If necessary, this method duplicates non-manifold vertices that can occur due to the removal of the triangle. The unlinked triangle, along with the other possible unlinked elements, must be removed from the List T through removeUnlinkedElements().
Definition at line 322 of file tin.cpp.
References List::appendHead(), Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHVEEDGE, Edge::isIsolated(), Edge::isOnBoundary(), Vertex::isOnBoundary(), Edge::replaceTriangle(), V, Edge::v1, Triangle::v1(), Edge::v2, Triangle::v2(), Triangle::v3(), Vertex::VE(), Point::x, Point::y, and Point::z.
{
 Vertex *v1 = t->v1(), *v2 = t->v2(), *v3 = t->v3();
 Edge *e1 = t->e1, *e2 = t->e2, *e3 = t->e3;
 int v1nm = (v1->isOnBoundary() && !e1->isOnBoundary() && !e2->isOnBoundary());
 int v2nm = (v2->isOnBoundary() && !e2->isOnBoundary() && !e3->isOnBoundary());
 int v3nm = (v3->isOnBoundary() && !e3->isOnBoundary() && !e1->isOnBoundary());
 v1->e0 = ((e2->isOnBoundary())?(e1):(e2));
 v2->e0 = ((e3->isOnBoundary())?(e2):(e3));
 v3->e0 = ((e1->isOnBoundary())?(e3):(e1));
 e1->replaceTriangle(t, NULL);
 e2->replaceTriangle(t, NULL);
 e3->replaceTriangle(t, NULL);
 if (e1->isIsolated() && e2->isIsolated()) v1->e0 = NULL;
 if (e2->isIsolated() && e3->isIsolated()) v2->e0 = NULL;
 if (e3->isIsolated() && e1->isIsolated()) v3->e0 = NULL;
 if (e1->isIsolated()) e1->v1 = e1->v2 = NULL;
 if (e2->isIsolated()) e2->v1 = e2->v2 = NULL;
 if (e3->isIsolated()) e3->v1 = e3->v2 = NULL;
 t->e1 = t->e2 = t->e3 = NULL;
 Vertex *nv;
 Edge *e;
 List *ve;
 Node *n;
 if (v1nm)
 {
  nv = new Vertex(v1->x, v1->y, v1->z);
  nv->e0 = v1->e0;
  ve = v1->VE();
  FOREACHVEEDGE(ve, e, n) e->replaceVertex(v1, nv);
  delete(ve);
  v1->e0 = e1;
  V.appendHead(nv);
 }
 if (v2nm)
 {
  nv = new Vertex(v2->x, v2->y, v2->z);
  nv->e0 = v2->e0;
  ve = v2->VE();
  FOREACHVEEDGE(ve, e, n) e->replaceVertex(v2, nv);
  delete(ve);
  v2->e0 = e2;
  V.appendHead(nv);
 }
 if (v3nm)
 {
  nv = new Vertex(v3->x, v3->y, v3->z);
  nv->e0 = v3->e0;
  ve = v3->VE();
  FOREACHVEEDGE(ve, e, n) e->replaceVertex(v3, nv);
  delete(ve);
  v3->e0 = e3;
  V.appendHead(nv);
 }
}
void Triangulation::unlinkTriangleNoManifold (Triangle * t)
Unlinks a triangle from the mesh. O(1).
No check is performed on the resulting topology, which may be inconsistent. The unlinked triangle, along with the other possible unlinked elements, must be removed from the List T through removeUnlinkedElements().
Definition at line 388 of file tin.cpp.
References Triangle::e1, Triangle::e2, Triangle::e3, Edge::isIsolated(), Edge::replaceTriangle(), Edge::v1, and Edge::v2.
{
 Edge *e1 = t->e1, *e2 = t->e2, *e3 = t->e3;
 e1->replaceTriangle(t, NULL);
 e2->replaceTriangle(t, NULL);
 e3->replaceTriangle(t, NULL);
 if (e1->isIsolated()) e1->v1 = e1->v2 = NULL;
 if (e2->isIsolated()) e2->v1 = e2->v2 = NULL;
 if (e3->isIsolated()) e3->v1 = e3->v2 = NULL;
 t->e1 = t->e2 = t->e3 = NULL;
}
void Triangulation::unmarkEverything ()
Unmark all the elements. O(N).
Definition at line 1184 of file tin.cpp.
References FOREACHEDGE, FOREACHTRIANGLE, FOREACHVERTEX, Triangle::mask, Edge::mask, and Vertex::mask.
{
 Vertex *v;
 Edge *e;
 Triangle *t;
 Node *n;
 FOREACHVERTEX(v, n) v->mask = 0;
 FOREACHEDGE(e, n) e->mask = 0;
 FOREACHTRIANGLE(t, n) t->mask = 0;
}
void Triangulation::unmarkEverythingButSelections ()
Unmarks all the elements but leaves the selection status of triangles as is. O(N).
Definition at line 875 of file tin.cpp.
References FOREACHEDGE, FOREACHTRIANGLE, FOREACHVERTEX, Triangle::mask, Edge::mask, and Vertex::mask.
{
 Vertex *v;
 Edge *e;
 Triangle *t;
 Node *n;
 FOREACHVERTEX(v, n) v->mask = 0;
 FOREACHEDGE(e, n) e->mask = 0;
 FOREACHTRIANGLE(t, n) t->mask &= (unsigned char)1;
}
double Triangulation::volume () const
Total volume of the mesh assuming that boundaries() = 0. O(N).
Definition at line 1255 of file tin.cpp.
References Triangle::area(), FOREACHTRIANGLE, Triangle::getCenter(), and Triangle::getNormal().
{
 Triangle *t;
 Node *n;
 double v=0.0;
 FOREACHTRIANGLE(t, n)
  v += (t->getCenter()*t->getNormal())*t->area();
 return v/3;
}
Vertex * Triangulation::watsonInsert (Point * p, List * tR, int nt)
Definition at line 1876 of file tin.cpp.
References List::appendHead(), CreateTriangle(), Node::data, E, Vertex::e0, Triangle::e1, EulerEdgeTriangle(), FOREACHVEEDGE, FOREACHVVVERTEX, List::freeCell(), Vertex::getEdge(), List::head(), Triangle::inSphere(), IS_BIT, IS_VISITED, MARK_BIT, MARK_VISIT, Node::next(), Vertex::nextOnBoundary(), List::numels(), Node::prev(), List::removeCell(), T, Edge::t1, Edge::t2, unlinkTriangleNoManifold(), UNMARK_VISIT, V, Triangle::v1(), Triangle::v2(), Triangle::v3(), Vertex::VE(), Point::x, Point::y, and Point::z.
{
 Node *n, *m;
 Edge *e;
 Triangle *t;
 List bdr, bdrs, todo, *ve;
 Vertex *v1, *v2, *v3;
 int i;
 for (i=0, n = T.head(); i<nt; n=n->next(), i++)
 {
  t = ((Triangle *)n->data);
  if (t->e1 != NULL && t->inSphere(p))
  {
   v1 = t->v1(); v2 = t->v2(); v3 = t->v3();
   if (!IS_VISITED(v1)) bdr.appendHead(v1);
   if (!IS_VISITED(v2)) bdr.appendHead(v2);
   if (!IS_VISITED(v3)) bdr.appendHead(v3);
   MARK_VISIT(v1); MARK_VISIT(v2); MARK_VISIT(v3);
   MARK_BIT(t, 3);
   todo.appendHead(t);
  }
 }
 if (bdr.numels() == 0) return NULL;
 FOREACHVVVERTEX((&(bdr)), v1, n)
 {
  ve = v1->VE();
  FOREACHVEEDGE(ve, e, m) if (!IS_BIT(e->t1, 3) || !IS_BIT(e->t2, 3)) v1->e0 = e;
  delete(ve);
 }
 while (todo.numels())
 {
  t = ((Triangle *)todo.head()->data);
  todo.removeCell(todo.head());
  unlinkTriangleNoManifold(t);
 }
 Node *tmp;
 for (i=0, n = T.head(); i<nt; i++)
 {
  t = ((Triangle *)n->data);
  if (t->e1 == NULL) {tmp = n; n=n->next(); T.freeCell(tmp);}
  else n=n->next();
 }
 for (n = bdr.head(); n!=NULL;)
 {
  v1 = ((Vertex *)n->data);
  if (v1->e0 == NULL) {tmp = n; n=n->next(); bdr.removeCell(tmp);}
  else n=n->next();
 }
 v1 = v2 = ((Vertex *)bdr.head()->data);
 do
 {
  bdrs.appendHead(v1);
  v1 = v1->nextOnBoundary();
 } while (v1 != v2);
 Vertex *v = new Vertex(p->x, p->y, p->z);
 V.appendHead(v);
 v1 = ((Vertex *)bdrs.head()->data);
 v->e0 = e = new Edge(v, v1);
 UNMARK_VISIT(v1);
 E.appendHead(e);
 for (n = bdrs.head()->next(); n!=NULL; n=n->next())
 {
  v1 = ((Vertex *)n->data);
  UNMARK_VISIT(v1);
  v2 = ((Vertex *)n->prev()->data);
  e = new Edge(v, v1);
  CreateTriangle(e, v1->getEdge(v2), (Edge *)E.head()->data);
  E.appendHead(e);
 }
 EulerEdgeTriangle(v->e0, (Edge *)E.head()->data);
 return v;
}
Member Data Documentation
bool Triangulation::d_boundaries [protected]
Dirty bit for n_boundaries.
Definition at line 62 of file tin.h.
bool Triangulation::d_handles [protected]
Dirty bit for n_handles.
Definition at line 63 of file tin.h.
bool Triangulation::d_shells [protected]
Dirty bit for n_shells.
Definition at line 64 of file tin.h.
List Triangulation::E
Edge set.
Definition at line 69 of file tin.h.
int Triangulation::n_boundaries [protected]
Number of boundary loops.
Definition at line 58 of file tin.h.
int Triangulation::n_handles [protected]
Number of handles.
Definition at line 59 of file tin.h.
int Triangulation::n_shells [protected]
Number of connected components.
Definition at line 60 of file tin.h.
List Triangulation::T
Triangle set.
Definition at line 70 of file tin.h.
List Triangulation::V
Vertex set.
Definition at line 68 of file tin.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/tin.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/MESH_STRUCTURE/checkAndRepair.cpp
/home/wondereamer/object_detection/JMeshLib-1.2/src/MESH_STRUCTURE/io.cpp
/home/wondereamer/object_detection/JMeshLib-1.2/src/MESH_STRUCTURE/tin.cpp