OpenCog Framework: Edge Class Reference
Edge Class Reference
Edge of a Triangulation.
#include <edge.h>
Public Member Functions
Edge (Vertex *s, Vertex *d)
Constructor.
~Edge ()
Destructor.
bool isLinked () const
TRUE iff edge is properly linked to a Triangulation.
bool hasVertex (const Vertex *v) const
TRUE iff 'v' is an end-point of the edge.
bool hasTriangle (const Triangle *t) const
TRUE iff 't' is incident to the edge.
bool hasVertices (const Vertex *va, const Vertex *vb) const
TRUE if both 'va' and 'vb' are vertices of the edge.
double length () const
Euclidean length of the edge.
double squaredLength () const
Squared length of the edge.
Point toVector () const
Convert to vector v2-v1.
Point toUnitVector () const
Convert to normalized vector (v2-v1)/|v2-v1|.
Point getMidPoint () const
Return the edge's mid-point.
void invert ()
Invert the edge's orientation.
Triangle * leftTriangle (const Vertex *v) const
Triangle on the left of the edge when looking from 'v'. NULL if 'v' is not a vertex of the edge.
Triangle * rightTriangle (const Vertex *v) const
Triangle on the right of the edge when looking from 'v'. NULL if 'v' is not a vertex of the edge.
Vertex * oppositeVertex (const Vertex *v) const
Vertex opposite to 'v'. NULL if 'v' is not a vertex of the edge.
Triangle * oppositeTriangle (const Triangle *t) const
Incident triangle opposite to 't'. NULL if 't' is not incident to the edge.
bool replaceVertex (const Vertex *a, Vertex *b)
Replace vertex 'a' with vertex 'b' in the edge and return TRUE. If 'a' is not a vertex of the edge return FALSE.
bool replaceTriangle (const Triangle *a, Triangle *b)
Replace incident triangle 'a' with 'b' and return TRUE. If 'a' is not incident to the edge return FALSE.
Vertex * commonVertex (const Edge *b) const
Vertex shared with edge 'b'. NULL if this and 'b' do not share any vertex.
bool isOnBoundary () const
TRUE iff edge is on the boundary (i.e., one of the two incident triangles is NULL).
bool isIsolated () const
TRUE iff edge is isolated (i.e., both the two incident triangles are NULL).
Triangle * getBoundaryTriangle () const
If the edge is on boundary return its only incident triangle. NULL otherwise.
void printEdge (FILE *f=stdout) const
Print the coordinates of the end-ponts to the file handler pointed to by 'f' (stdout by default).
Point getNormal () const
Return the normal at the edge as the average of the normals of the two incident triangles.
bool swap (const bool fast=0)
Combinatorial edge-swap.
bool collapse (const Point &p)
Edge collapse.
bool collapse ()
Edge collapse.
bool merge (Edge *e)
Merge with another boundary edge.
bool stitch ()
Stitching primitive.
double dihedralAngle () const
Dihedral angle at the edge.
double curvature () const
Angle between the normals of the two incident triangles.
double delaunayMinAngle () const
Return the minimum among the six angles of the two incident triangles.2PI if on boundary.
Public Attributes
Vertex * v1
Vertex * v2
End-points.
class Triangle * t1
class Triangle * t2
Incident triangles.
unsigned char mask
bit-mask for marking purposes
void * info
Further information.
Detailed Description
Edge of a Triangulation.
This class represents an edge of a triangulation. An Edge is the main part of the Triangulation data structure. Each edge has an orientation (i.e. from v1 to v2) which forces the order in which incident triangles (t1 and t2) are stored in the class. When looking the edge so that it points "upwards", if the normal of t1 points towards the observer then t1 must be on the left of the edge. The field mask is useful for assigning up to 256 different states to the edge.
Definition at line 45 of file edge.h.
Constructor & Destructor Documentation
Edge::Edge (Vertex * s, Vertex * d)
Constructor.
Definition at line 67 of file edge.cpp.
References info, mask, t1, t2, v1, and v2.
{
 v1 = va;
 v2 = vb;
 t1 = t2 = NULL;
 info = NULL;
 mask = 0;
}
Edge::~Edge ()
Destructor.
Definition at line 79 of file edge.cpp.
{
}
Member Function Documentation
bool Edge::collapse (const Point & p)
Edge collapse.
This method collapses the edge and updates the connectivity of the neighboring elements consistently. The edge will be transformed into a vertex with the coordinates of 'p'. This method returns TRUE on success, FALSE otherwise. Failure occurs when the collapse would produce an invalid connectivity graph. Caution! If the collapse succeeds the edge, its incident triangles and the second vertex are unlinked, but they are still present in the lists of the Triangulation. The calling function is responsible of removing them from the lists using the method removeUnlinkedElements().
Definition at line 139 of file edge.cpp.
References Vertex::e0, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHVEEDGE, Vertex::getEdge(), Vertex::isOnBoundary(), Triangle::nextEdge(), oppositeTriangle(), Triangle::oppositeVertex(), oppositeVertex(), Triangle::prevEdge(), Triangle::replaceEdge(), replaceTriangle(), replaceVertex(), Point::setValue(), t1, t2, v1, v2, and Vertex::VE().
{
 Edge *e;
 Node *n;
 List *ve;
 Vertex *tv;
 Edge *e1 = (t1 != NULL)?(t1->nextEdge(this)):(NULL);
 Edge *e2 = (t1 != NULL)?(t1->prevEdge(this)):(NULL);
 Edge *e3 = (t2 != NULL)?(t2->nextEdge(this)):(NULL);
 Edge *e4 = (t2 != NULL)?(t2->prevEdge(this)):(NULL);
 Vertex *v3 = (e1 != NULL)?(e1->oppositeVertex(v2)):(NULL);
 Vertex *v4 = (e4 != NULL)?(e4->oppositeVertex(v2)):(NULL);
 Triangle *ta1 = (e1 != NULL)?(e1->oppositeTriangle(t1)):(NULL);
 Triangle *ta2 = (e2 != NULL)?(e2->oppositeTriangle(t1)):(NULL);
 Triangle *ta3 = (e3 != NULL)?(e3->oppositeTriangle(t2)):(NULL);
 Triangle *ta4 = (e4 != NULL)?(e4->oppositeTriangle(t2)):(NULL);
 if (v1->isOnBoundary() && v2->isOnBoundary())
  if (!(((ta1 || ta2) && !ta3 && !ta4) || ((ta3 || ta4) && !ta1 && !ta2))) return 0;
 if (ta1 != NULL && ta2 != NULL && ta1->oppositeVertex(e1) == ta2->oppositeVertex(e2))
  return 0;
 if (ta3 != NULL && ta4 != NULL && ta3->oppositeVertex(e3) == ta4->oppositeVertex(e4))
  return 0;
 if (ta1 == NULL && ta2 == NULL) v1->e0 = e3;
 else v1->e0 = e2;
 if (v3 != NULL) v3->e0 = e2;
 if (v4 != NULL) v4->e0 = e3;
 ve = v2->VE();
 FOREACHVEEDGE(ve, e, n)
 {
  tv = e->oppositeVertex(v2);
  if (tv != v3 && tv != v4 && tv->getEdge(v1) != NULL) {delete(ve); return 0;}
 }
 FOREACHVEEDGE(ve, e, n) if (e != this) e->replaceVertex(v2, v1);
 delete(ve);
 if (e2 != NULL) e2->replaceTriangle(t1, ta1);
 if (e3 != NULL) e3->replaceTriangle(t2, ta4);
 if (ta1 != NULL) ta1->replaceEdge(e1, e2);
 if (ta4 != NULL) ta4->replaceEdge(e4, e3);
 v2->e0 = NULL;                     // v2 must be removed
 if (e4 != NULL) e4->v1 = e4->v2 = NULL;        // e4 must be removed
 if (e1 != NULL) e1->v1 = e1->v2 = NULL;        // e1 must be removed
 if (t1 != NULL) t1->e1 = t1->e2 = t1->e3 = NULL;   // t1 must be removed
 if (t2 != NULL) t2->e1 = t2->e2 = t2->e3 = NULL;   // t2 must be removed
 if (e2 != NULL && e2->t1 == NULL && e2->t2 == NULL)
 {
  v3->e0 = NULL;
  e2->v1 = e2->v2 = NULL;
 }
 if (e3 != NULL && e3->t1 == NULL && e3->t2 == NULL)
 {
  v4->e0 = NULL;
  e3->v1 = e3->v2 = NULL;
 }
 v1->setValue(&p);                  // Average the collapse
 v2 = v1 = NULL;                    // this edge must be removed
 return 1;
}
bool Edge::collapse ()
Edge collapse.
This method collapses the edge and updates the connectivity of the neighboring elements consistently. The edge will be transformed into a vertex placed at the edge's mid-point. This method returns TRUE on success, FALSE otherwise. Failure occurs when the collapse would produce an invalid connectivity graph. Caution! If the collapse succeeds the edge, its incident triangles and the second vertex are unlinked, but they are still present in the lists of the Triangulation. The calling function is responsible of removing them from the lists using the method removeUnlinkedElements().
Definition at line 210 of file edge.cpp.
References v1, and v2.
{
 return collapse(((*v1)+(*v2))/2);
}
Vertex* Edge::commonVertex (const Edge * b) const [inline]
Vertex shared with edge 'b'. NULL if this and 'b' do not share any vertex.
Definition at line 106 of file edge.h.
References v1, and v2.
{return ((v1 == b->v1 || v1 == b->v2)?(v1):((v2 == b->v1 || v2 == b->v2)?(v2):(NULL)));}
double Edge::curvature () const
Angle between the normals of the two incident triangles.
Angle between the normals of the two incident triangles. If the edge is on boundary or one or both the incident triangles are degenerate, return -1.
Definition at line 273 of file edge.cpp.
References Triangle::getDAngle(), t1, and t2.
{
 if (!t1 || !t2) return -1.0;
 return t1->getDAngle(t2);
}
double Edge::delaunayMinAngle () const
Return the minimum among the six angles of the two incident triangles.2PI if on boundary.
Definition at line 298 of file edge.cpp.
References Triangle::getAngle(), length(), M_PI, MIN, Triangle::nextEdge(), Triangle::oppositeVertex(), Triangle::prevEdge(), t1, t2, v1, and v2.
{
 if (t1==NULL || t2==NULL) return 2*M_PI;
 if (length()==0) return 0;
 if (t1->nextEdge(this)->length()==0) return 0;
 if (t1->prevEdge(this)->length()==0) return 0;
 double a1 = t1->getAngle(v1);
 double a2 = t1->getAngle(v2);
 double a3 = t1->getAngle(t1->oppositeVertex(this));
 if (t2->nextEdge(this)->length()==0) return 0;
 if (t2->prevEdge(this)->length()==0) return 0;
 double a4 = t2->getAngle(v1);
 double a5 = t2->getAngle(v2);
 double a6 = t2->getAngle(t2->oppositeVertex(this));
 if (a1+a4 >= M_PI || a2+a5 >= M_PI) return 3*M_PI;
 return MIN(a1,(MIN(a2,(MIN(a3,(MIN(a4,(MIN(a5,a6)))))))));
}
double Edge::dihedralAngle () const
Dihedral angle at the edge.
Definition at line 282 of file edge.cpp.
References Point::getAngle(), Triangle::getNormal(), Point::isNull(), M_PI, Triangle::oppositeVertex(), t1, t2, and v1.
{
 if (!t1 || !t2) return -1.0;
 Point nor1 = t1->getNormal();
 Point nor2 = t2->getNormal();
 if (nor1.isNull() || nor2.isNull()) return -1.0;
 double c = nor1.getAngle(&nor2);
 Vertex *ov = t2->oppositeVertex(this);
 if (((*ov)*nor1)-((*v1)*nor1) < 0) return M_PI-c;
 return M_PI+c;
}
Triangle* Edge::getBoundaryTriangle () const [inline]
If the edge is on boundary return its only incident triangle. NULL otherwise.
Definition at line 115 of file edge.h.
References t1, and t2.
{return (t2 == NULL)?(t1):((t1 == NULL)?(t2):(NULL));}
Point Edge::getMidPoint () const [inline]
Return the edge's mid-point.
Definition at line 82 of file edge.h.
References v1, and v2.
{return ((*v1)+(*v2))/2.0;}
Point Edge::getNormal () const
Return the normal at the edge as the average of the normals of the two incident triangles.
A null (0,0,0) vector is returned if the edge is on boundary.
Returns the edge normal. //// It is the average of the incident triangle normals ////
Definition at line 100 of file edge.cpp.
References Triangle::getNormal(), Point::length(), Point::normalize(), t1, and t2.
{
 Point nor, n1, n2;
 if (t1 == NULL || t2 == NULL) return Point(0,0,0);
 n1 = t1->getNormal();
 n2 = t2->getNormal();
 nor = n1+n2;
 if (nor.length() != 0.0) nor.normalize();
 return nor;
}
bool Edge::hasTriangle (const Triangle * t) const [inline]
TRUE iff 't' is incident to the edge.
Definition at line 64 of file edge.h.
References t1, and t2.
{return (t1==t || t2==t);}
bool Edge::hasVertex (const Vertex * v) const [inline]
TRUE iff 'v' is an end-point of the edge.
Definition at line 61 of file edge.h.
References v1, and v2.
{return (v1==v || v2==v);}
bool Edge::hasVertices (const Vertex * va, const Vertex * vb) const [inline]
TRUE if both 'va' and 'vb' are vertices of the edge.
Definition at line 67 of file edge.h.
References v1, and v2.
{return ((v1==va && v2==vb) || (v2==va && v1==vb));}
void Edge::invert () [inline]
Invert the edge's orientation.
Definition at line 85 of file edge.h.
References p_swap(), t1, t2, v1, and v2.
{p_swap((void **)(&v1), (void **)(&v2)); p_swap((void **)(&t1), (void **)(&t2));}
bool Edge::isIsolated () const [inline]
TRUE iff edge is isolated (i.e., both the two incident triangles are NULL).
Definition at line 112 of file edge.h.
References t1, and t2.
{return (t1 == NULL && t2 == NULL);}
bool Edge::isLinked () const [inline]
TRUE iff edge is properly linked to a Triangulation.
Definition at line 58 of file edge.h.
References v1.
{return (v1 != NULL);}
bool Edge::isOnBoundary () const [inline]
TRUE iff edge is on the boundary (i.e., one of the two incident triangles is NULL).
Definition at line 109 of file edge.h.
References t1, and t2.
{return (t1 == NULL || t2 == NULL);}
Triangle* Edge::leftTriangle (const Vertex * v) const [inline]
Triangle on the left of the edge when looking from 'v'. NULL if 'v' is not a vertex of the edge.
Definition at line 88 of file edge.h.
References t1, t2, v1, and v2.
{return ((v1 == v)?(t1):((v2 == v)?(t2):(NULL)));}
double Edge::length () const [inline]
Euclidean length of the edge.
Definition at line 70 of file edge.h.
References Point::distance(), v1, and v2.
{return v1->distance(v2);}
bool Edge::merge (Edge * e)
Merge with another boundary edge.
If both this and 'e' are boundary edges, the edge 'e' is identified with this one, and the connectivity of the neighboring elements is updated consistently. This method returns TRUE on success, FALSE otherwise. Failure occurs when the merge would produce an invalid connectivity graph (i.e., non orientable). Caution! If the merge succeeds the edge 'e' and its two end-points are unlinked, but they are still present in the lists of the Triangulation. It's responsibility of the calling function to remove them from the lists using the method removeUnlinkedElements().
Definition at line 218 of file edge.cpp.
References Vertex::e0, FOREACHVEEDGE, Vertex::getEdge(), invert(), isOnBoundary(), oppositeVertex(), Triangle::replaceEdge(), replaceVertex(), t1, t2, v1, v2, and Vertex::VE().
{
 if (t1 && t2) return 0;
 if (e->t1 && e->t2) return 0;
 Triangle *ot = (e->t1==NULL)?(e->t2):(e->t1);
 if ((t1 && e->t1) || (t2 && e->t2)) e->invert();
 Vertex *ov1 = e->v1, *ov2 = e->v2;
 List *ve1=NULL, *ve2=NULL;
 Node *n;
 Edge *f, *f2;
 if (ov1 != v1)
 {
  ve1 = ov1->VE();
  FOREACHVEEDGE(ve1, f, n)
  {
   f2 = f->oppositeVertex(ov1)->getEdge(v1);
   if (f2 != NULL && (!f2->isOnBoundary() || !f->isOnBoundary()))
    {delete(ve1); return 0;}
  }
 }
 if (ov2 != v2)
 {
  ve2 = ov2->VE();
  FOREACHVEEDGE(ve2, f, n)
  {
   f2 = f->oppositeVertex(ov2)->getEdge(v2);
   if (f2 != NULL && (!f2->isOnBoundary() || !f->isOnBoundary()))
    {delete(ve1); delete(ve2); return 0;}
  }
 }
 if (ov1 != v1)
 {
  FOREACHVEEDGE(ve1, f, n) f->replaceVertex(ov1, v1);
  delete(ve1);
  ov1->e0 = NULL;
 }
 if (ov2 != v2)
 {
  FOREACHVEEDGE(ve2, f, n) f->replaceVertex(ov2, v2);
  delete(ve2);
  ov2->e0 = NULL;
 }
 ot->replaceEdge(e, this);
 ((t1==NULL)?(t1):(t2)) = ot;
 v1->e0 = v2->e0 = this;
 e->v1 = e->v2 = NULL;
 return 1;
}
Triangle* Edge::oppositeTriangle (const Triangle * t) const [inline]
Incident triangle opposite to 't'. NULL if 't' is not incident to the edge.
Definition at line 97 of file edge.h.
References t1, and t2.
{return ((t1 == t)?(t2):((t2 == t)?(t1):(NULL)));}
Vertex* Edge::oppositeVertex (const Vertex * v) const [inline]
Vertex opposite to 'v'. NULL if 'v' is not a vertex of the edge.
Definition at line 94 of file edge.h.
References v1, and v2.
{return ((v1 == v)?(v2):((v2 == v)?(v1):(NULL)));}
void Edge::printEdge (FILE * f = stdout) const [inline]
Print the coordinates of the end-ponts to the file handler pointed to by 'f' (stdout by default).
Definition at line 118 of file edge.h.
References Point::printPoint(), v1, and v2.
{v1->printPoint(f); v2->printPoint(f);}
bool Edge::replaceTriangle (const Triangle * a, Triangle * b) [inline]
Replace incident triangle 'a' with 'b' and return TRUE. If 'a' is not incident to the edge return FALSE.
Definition at line 103 of file edge.h.
References t1, and t2.
{if (t1==a) t1=b; else if (t2==a) t2=b; else return 0; return 1;}
bool Edge::replaceVertex (const Vertex * a, Vertex * b) [inline]
Replace vertex 'a' with vertex 'b' in the edge and return TRUE. If 'a' is not a vertex of the edge return FALSE.
Definition at line 100 of file edge.h.
References v1, and v2.
{if (v1==a) v1=b; else if (v2==a) v2=b; else return 0; return 1;}
Triangle* Edge::rightTriangle (const Vertex * v) const [inline]
Triangle on the right of the edge when looking from 'v'. NULL if 'v' is not a vertex of the edge.
Definition at line 91 of file edge.h.
References t1, t2, v1, and v2.
{return ((v1 == v)?(t2):((v2 == v)?(t1):(NULL)));}
double Edge::squaredLength () const [inline]
Squared length of the edge.
Definition at line 73 of file edge.h.
References Point::squaredDistance(), v1, and v2.
{return v1->squaredDistance(v2);}
bool Edge::stitch ()
Stitching primitive.
If there is a copy of this edge incident to one of the end-points, identify it with this edge, and update the connectivity properly. This method returns TRUE on success, FALSE otherwise. Caution! If the stitch succeeds, the duplicated edge is unlinked, but it is still present in the lists of the Triangulation. It's responsibility of the calling function to remove it from the lists using the method removeEdges().
Definition at line 320 of file edge.cpp.
References Vertex::e0, hasVertex(), isOnBoundary(), Triangle::nextEdge(), oppositeTriangle(), oppositeVertex(), Triangle::replaceEdge(), replaceTriangle(), t1, t2, v1, and v2.
{
 if (!isOnBoundary()) return 0;
 Triangle *t, *t0 = (t1!=NULL)?(t1):(t2);
 Vertex *v0;
 Edge *e1;
 for (v0=v1; v0!=NULL; v0=((v0==v1)?(v2):(NULL)))
 {
  e1=this;
  t = t0;
  while (t!=NULL)
  {
   e1 = t->nextEdge(e1); if (!e1->hasVertex(v0)) e1 = t->nextEdge(e1);
   t = e1->oppositeTriangle(t);
  }
  if (e1->oppositeVertex(v0) == oppositeVertex(v0))
  {
   t = (e1->t1!=NULL)?(e1->t1):(e1->t2);
   t->replaceEdge(e1, this);
   v1->e0 = v2->e0 = this;
   e1->v1=e1->v2=NULL;
   replaceTriangle(NULL, t);
   return 1;
  }
 }
 return 0;
}
bool Edge::swap (const bool fast = 0)
Combinatorial edge-swap.
Vertices of the edge are replaced with vertices of the two incident triangles which are opposite to this edge. Connectivity information is updated properly. If the edge is on boundary or if the edge after the swap already exists return FALSE and do not change anything. Return TRUE on success. If 'fast' is set, no topological check is performed.
Definition at line 115 of file edge.cpp.
References Vertex::e0, Vertex::getEdge(), Triangle::invert(), Triangle::nextEdge(), Triangle::oppositeVertex(), Triangle::replaceEdge(), replaceTriangle(), t1, t2, v1, and v2.
{
 if (!fast && (t1 == NULL || t2 == NULL ||
     t2->oppositeVertex(this)->getEdge(t1->oppositeVertex(this)) != NULL)) return 0;
 Edge *e1 = t1->nextEdge(this);
 Edge *e3 = t2->nextEdge(this);
 v1->e0 = e3;
 v2->e0 = e1;
 v1 = t2->oppositeVertex(this);
 v2 = t1->oppositeVertex(this);
 t1->replaceEdge(e1, e3);
 t2->replaceEdge(e3, e1);
 t1->invert();
 t2->invert();
 e1->replaceTriangle(t1, t2);
 e3->replaceTriangle(t2, t1);
 return 1;
}
Point Edge::toUnitVector () const
Convert to normalized vector (v2-v1)/|v2-v1|.
Definition at line 86 of file edge.cpp.
References JMesh::error(), Point::length(), and toVector().
{
 Point v = toVector();
 double l = v.length();
 if (l == 0) JMesh::error("Edge::toUnitVector : Degenerate Edge !\n");
 return v/l;
}
Point Edge::toVector () const [inline]
Convert to vector v2-v1.
Definition at line 76 of file edge.h.
References v2.
{return (*v2)-(*v1);}
Member Data Documentation
void* Edge::info
Further information.
Definition at line 52 of file edge.h.
unsigned char Edge::mask
bit-mask for marking purposes
Definition at line 51 of file edge.h.
class Triangle* Edge::t1
Definition at line 50 of file edge.h.
class Triangle * Edge::t2
Incident triangles.
Definition at line 50 of file edge.h.
Vertex* Edge::v1
Definition at line 49 of file edge.h.
Vertex * Edge::v2
End-points.
Definition at line 49 of file edge.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/edge.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/MESH_STRUCTURE/edge.cpp