OpenCog Framework: Vertex Class Reference
Vertex Class Reference
Vertex of a Triangulation.
#include <vertex.h>
Public Member Functions
Vertex ()
Creates a new vertex with coordinates (0,0,0).
Vertex (const coord &x, const coord &y, const coord &z)
Creates a new vertex with the same coordinates (x,y,z).
Vertex (const Point *p)
Creates a new vertex with the same coordinates as 'p'. The info field is not copied.
Vertex (const Point &p)
Creates a new vertex with the same coordinates as 'p'. The info field is not copied.
~Vertex ()
Destructor.
bool isLinked () const
TRUE iff vertex is not isolated.
List * VV () const
List of adjacent vertices.
List * VE () const
List of incident edges.
List * VT () const
List of incident triangles.
class Edge * getEdge (const Vertex *v) const
Returns the edge connecting this vertex to 'v'. NULL if such an edge does not exist.
int valence () const
Returns the number of incident edges.
int isOnBoundary () const
TRUE iff vertex is on boundary.
Edge * nextBoundaryEdge () const
Returns the edge following this vertex on the boundary.
Edge * prevBoundaryEdge () const
Returns the edge preceeding this vertex on the boundary.
Vertex * nextOnBoundary () const
Returns the vertex following this one on the boundary.
Vertex * prevOnBoundary () const
Returns the vertex preceeding this one on the boundary.
Point getNormal () const
Normal at the vertex computed as the sum of incident triangle normals weighted on their incidence angle.
double getBoundaryAngle () const
Returns the angle between the two incident boundary edges. If the vertex is not on the boundary, returns -1.
double getAngleForTriangulation () const
Discriminant Angle for triangulating 3D polygons.
double getAngleOnAveragePlane (Point *n) const
Discriminant Angle for triangulating flat (or nearly flat) polygons.
double totalAngle () const
Sum of incident angles. Returns -1 if on boundary.
double gaussianCurvature () const
Excess angle. Returns DBL_MAX if on boundary.
double totalDihedralAngle () const
Sum of signed dihedral angles. Returns DBL_MAX if on boundary.
double voronoiArea () const
A third of the total area of incident triangles.
int zip (const bool=1)
Zips the gap starting from here.
Edge * inverseCollapse (Vertex *, Vertex *, Vertex *)
Edge * inverseCollapse (Vertex *, Edge *, Edge *, Edge *, Edge *, Edge *, class Triangle *, class Triangle *)
int getTopology (const double &) const
Public Attributes
class Edge * e0
One of the incident edges.
unsigned char mask
bit-mask for marking purposes
Detailed Description
Vertex of a Triangulation.
This class represents a vertex of a manifold and oriented triangulation. The base-class Point describes geometrical and additional attributes of the vertex. The field 'e0' is sufficient to retrieve all the neighboring elements in optimal time, while the field 'mask' is useful for assigning up to 256 different states to the vertex.
Definition at line 45 of file vertex.h.
Constructor & Destructor Documentation
Vertex::Vertex ()
Creates a new vertex with coordinates (0,0,0).
Definition at line 37 of file vertex.cpp.
References e0, and mask.
               : Point()
{
 e0 = NULL;
 mask = 0;
}
Vertex::Vertex (const coord & x, const coord & y, const coord & z)
Creates a new vertex with the same coordinates (x,y,z).
Definition at line 44 of file vertex.cpp.
References e0, and mask.
                                                             : Point(a,b,c)
{
 e0 = NULL;
 mask = 0;
}
Vertex::Vertex (const Point * p)
Creates a new vertex with the same coordinates as 'p'. The info field is not copied.
Definition at line 51 of file vertex.cpp.
References e0, and mask.
                             : Point(p->x, p->y, p->z)
{
 e0 = NULL;
 mask = 0;
}
Vertex::Vertex (const Point & p)
Creates a new vertex with the same coordinates as 'p'. The info field is not copied.
Definition at line 58 of file vertex.cpp.
References e0, and mask.
                             : Point(p.x, p.y, p.z)
{
 e0 = NULL;
 mask = 0;
}
Vertex::~Vertex ()
Destructor.
Definition at line 66 of file vertex.cpp.
{
}
Member Function Documentation
double Vertex::gaussianCurvature () const [inline]
Excess angle. Returns DBL_MAX if on boundary.
Definition at line 158 of file vertex.h.
References totalAngle().
  {double t=totalAngle(); return (t>=0)?(t):(DBL_MAX);}
double Vertex::getAngleForTriangulation () const
Discriminant Angle for triangulating 3D polygons.
This method is useful when patching holes, and represents a heuristic for choosing which vertex of the hole's boundary must be patched first. Several cases are considered, including degenerate ones. Let 'v1' and 'v2' be the two boundary vertices which are linked to this one through a boundary edge. If 'v1' and 'v2' coincide, the method returns a negative number. If 'v1' , 'this' , 'v2' form a flat angle, the method returns 3PI (270 degrees). If the angle formed by 'v1' , 'this' , 'v2' is 0, the method returns 0. If the vertex is not on the boundary, the method returns the limit number DBL_MAX. In all the other cases the method returns the sum of three angles A + D1 + D2, where A is the angle formed by v1 , this , v2 , while D1 is the angle between the normal of the clockwise-most incident boundary triangle and the normal of the triangle v1 , this , v2; D2 is the analogous for the counterclockwise-most incident boundary triangle.
Definition at line 343 of file vertex.cpp.
References Point::distance(), Point::getAngle(), Edge::getBoundaryTriangle(), Triangle::getDAngle(), M_PI, nextBoundaryEdge(), Edge::oppositeVertex(), and prevBoundaryEdge().
{
 Edge *e1 = prevBoundaryEdge();
 Edge *e2 = nextBoundaryEdge();
 if (e1 == NULL || e2 == NULL) return DBL_MAX;
 Triangle *t1 = e1->getBoundaryTriangle();
 Triangle *t2 = e2->getBoundaryTriangle();
 Vertex *v1 = e1->oppositeVertex(this);
 Vertex *v2 = e2->oppositeVertex(this);
 if ((*v2)==(*v1)) return -2;
 if (distance(v1)*distance(v2) == 0.0) return -1;
 double ang = getAngle(v1,v2);
 if (ang == M_PI) return 3*M_PI;
 if (ang == 0)    return 0;
 Edge e3(v1,v2);
 Triangle t(e1,e2,&e3);
 double da1 = t.getDAngle(t1);
 double da2 = t.getDAngle(t2);
 if (da1==M_PI && da2==M_PI) return (DBL_MAX/2.0);
 if (da1==M_PI || da2==M_PI) return (DBL_MAX/4.0);
 return da1+da2+ang;
}
double Vertex::getAngleOnAveragePlane (Point * n) const
Discriminant Angle for triangulating flat (or nearly flat) polygons.
This method returns the angle between the two incident boundary edges when projected onto the plane whose normal is 'n'. This angle may be more than PI, because it represents the aperture of the non-tri- angulated region around the vertex when projected on the plane. If the vertex is not on the boundary, the method returns the limit value DBL_MAX.
Definition at line 373 of file vertex.cpp.
References Point::distance(), Point::getAngle(), M_PI, nextBoundaryEdge(), Edge::oppositeVertex(), prevBoundaryEdge(), Point::project(), Point::setValue(), Point::side3D(), and JMesh::warning().
{
 Edge *e1 = prevBoundaryEdge();
 Edge *e2 = nextBoundaryEdge();
 if (e1 == NULL || e2 == NULL) return DBL_MAX;
 Vertex *v1 = e1->oppositeVertex(this);
 Vertex *v2 = e2->oppositeVertex(this);
 Point p, p1, p2;
 p1.setValue(v1);
 p2.setValue(v2);
 p.setValue(this);
 p.project(nor);
 p1.project(nor);
 p2.project(nor);
 if (p.distance(p1)*p.distance(p2) == 0.0)
 {
  JMesh::warning("getAngleOnAveragePlane: coincident projections\n");
  return 0.0;
 }
 double ang = p.getAngle(&p1, &p2);
 if (nor->side3D(&p1, &p, &p2) < 0) ang = 2*M_PI-ang;
 return ang;
}
double Vertex::getBoundaryAngle () const
Returns the angle between the two incident boundary edges. If the vertex is not on the boundary, returns -1.
Definition at line 328 of file vertex.cpp.
References Point::getAngle(), nextBoundaryEdge(), Edge::oppositeVertex(), and prevBoundaryEdge().
{
 Edge *e1 = prevBoundaryEdge();
 Edge *e2 = nextBoundaryEdge();
 if (e1 == NULL || e2 == NULL) return -1.0;
 Vertex *v1 = e1->oppositeVertex(this);
 Vertex *v2 = e2->oppositeVertex(this);
 double ang = getAngle(v1,v2);
 return ang;
}
Edge * Vertex::getEdge (const Vertex * v) const
Returns the edge connecting this vertex to 'v'. NULL if such an edge does not exist.
Definition at line 184 of file vertex.cpp.
References FOREACHVEEDGE, Edge::oppositeVertex(), and VE().
{
 List *ve = VE();
 Node *m;
 Edge *e;
 FOREACHVEEDGE(ve, e, m)
  if (e->oppositeVertex(this) == v2) {delete(ve); return e;}
 delete(ve);
 return NULL;
}
Point Vertex::getNormal () const
Normal at the vertex computed as the sum of incident triangle normals weighted on their incidence angle.
Definition at line 303 of file vertex.cpp.
References FOREACHVTTRIANGLE, Triangle::getAngle(), Triangle::getNormal(), Point::isNull(), Point::normalize(), Point::Point(), and VT().
{
 List *vt = VT();
 Node *n;
 Triangle *t;
 double pa;
 Point tnor, ttn;
 FOREACHVTTRIANGLE(vt, t, n)
 {
  pa = t->getAngle(this);
  ttn = t->getNormal();
  if (!ttn.isNull()) tnor = tnor+(ttn*pa);
 }
 delete(vt);
 if (tnor.isNull()) return Point(0,0,0);
 tnor.normalize();
 return tnor;
}
int Vertex::getTopology (const double & r) const
Definition at line 590 of file vertex.cpp.
References List::appendHead(), DECREASE_INFO_FIELD, e0, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHVEEDGE, INCREASE_INFO_FIELD, Point::info, IS_BIT, MARK_BIT, List::numels(), Edge::oppositeVertex(), Triangle::oppositeVertex(), List::popHead(), Point::squaredDistance(), Triangle::t1(), Edge::t1, Triangle::t2(), Edge::t2, Triangle::t3(), UNMARK_BIT, Edge::v1, Edge::v2, and VE().
{
 int numBoundaries=0;
 double r2 = r*r;
 List *ve, triList, trisInSphere, edgsInSphere, edgsOnBoundary;
 Node *n;
 Triangle *t, *s;
 Edge *e, *f;
 Vertex *w;
 t = (e0->t1 != NULL)?(e0->t1):(e0->t2);
 triList.appendHead(t);
 MARK_BIT(t,3);
 while(triList.numels() > 0)
 {
  t = (Triangle *)triList.popHead();
  trisInSphere.appendHead(t);
  if ((s = t->t1()) != NULL && !IS_BIT(s,3) && (squaredDistance(s->oppositeVertex(t->e1))<r2))
       {triList.appendHead(s); MARK_BIT(s,3);}
  if ((s = t->t2()) != NULL && !IS_BIT(s,3) && (squaredDistance(s->oppositeVertex(t->e2))<r2))
       {triList.appendHead(s); MARK_BIT(s,3);}
  if ((s = t->t3()) != NULL && !IS_BIT(s,3) && (squaredDistance(s->oppositeVertex(t->e3))<r2))
       {triList.appendHead(s); MARK_BIT(s,3);}
 }
 while ((s = (Triangle *)trisInSphere.popHead()) != NULL)
 {
  UNMARK_BIT(s, 3);
  e = s->e1; if (!IS_BIT(e, 3)) {MARK_BIT(e, 3); edgsInSphere.appendHead(e);} else UNMARK_BIT(e, 3);
  e = s->e2; if (!IS_BIT(e, 3)) {MARK_BIT(e, 3); edgsInSphere.appendHead(e);} else UNMARK_BIT(e, 3);
  e = s->e3; if (!IS_BIT(e, 3)) {MARK_BIT(e, 3); edgsInSphere.appendHead(e);} else UNMARK_BIT(e, 3);
 }
 while ((e = (Edge *)edgsInSphere.popHead()) != NULL) if (IS_BIT(e, 3)) edgsOnBoundary.appendHead(e);
 FOREACHVEEDGE((&edgsOnBoundary), e, n) e->v1->info = e->v2->info = 0;
 FOREACHVEEDGE((&edgsOnBoundary), e, n)
 {
  INCREASE_INFO_FIELD(e->v1);
  INCREASE_INFO_FIELD(e->v2);
 }
 while ((e = (Edge *)edgsOnBoundary.popHead()) != NULL) if (IS_BIT(e, 3))
 {
  numBoundaries++;
  DECREASE_INFO_FIELD(e->v1); UNMARK_BIT(e, 3); w=e->v2;
  while (w->info)
  {
   e = NULL;
   ve = w->VE();
   FOREACHVEEDGE(ve, f, n) if (IS_BIT(f, 3)) {e = f; UNMARK_BIT(e, 3); break;}
   delete(ve);
   DECREASE_INFO_FIELD(w);
   w = e->oppositeVertex(w);
  }
 }
 return numBoundaries;
}
Edge * Vertex::inverseCollapse (Vertex * v2, Edge * e, Edge * e1, Edge * e2, Edge * e3, Edge * e4, class Triangle * t1, class Triangle * t2)
Definition at line 546 of file vertex.cpp.
References Node::data, e0, Triangle::e1, Triangle::e2, Triangle::e3, FOREACHNODECIRCULAR, FOREACHVEEDGE, Edge::leftTriangle(), Edge::oppositeVertex(), Triangle::replaceEdge(), Edge::replaceTriangle(), Edge::replaceVertex(), Edge::rightTriangle(), Edge::t1, Edge::t2, Edge::v1, Edge::v2, and VE().
{
 Triangle *ta1, *ta4;
 Node *n;
 Edge *f;
 ta1 = e2->rightTriangle(this);
 ta4 = e3->leftTriangle(this);
 List *ve = VE();
 FOREACHVEEDGE(ve, f, n) if (f == e3) break;
 FOREACHNODECIRCULAR((*ve), n, n)
 {
  f = ((Edge *)n->data);
  if (f == e2) break;
  else f->replaceVertex(this, v2);
 }
 delete(ve);
 e->v1 = this; e->v2 = v2;
 e1->v1 = v2; e1->v2 = e2->oppositeVertex(this);
 e4->v1 = v2; e4->v2 = e3->oppositeVertex(this);
 t1->e1 = e; t1->e2 = e1; t1->e3 = e2;
 t2->e1 = e; t2->e2 = e3; t2->e3 = e4;
 e->t1 = t1; e->t2 = t2;
 e2->replaceTriangle(ta1, t1);
 e3->replaceTriangle(ta4, t2);
 if (ta1) ta1->replaceEdge(e2, e1);
 if (ta4) ta4->replaceEdge(e3, e4);
 e1->t1 = t1; e1->t2 = ta1;
 e4->t1 = ta4; e4->t2 = t2;
 v2->e0 = e0 = e;
 return e;
}
Edge * Vertex::inverseCollapse (Vertex * v2, Vertex * v3, Vertex * v4)
Definition at line 493 of file vertex.cpp.
References Node::data, e0, FOREACHNODECIRCULAR, FOREACHVEEDGE, Triangle::leftTriangle(), Edge::oppositeVertex(), Triangle::replaceEdge(), Edge::replaceTriangle(), Edge::replaceVertex(), Edge::rightTriangle(), Triangle::t1(), Edge::t1, Triangle::t2(), Edge::t2, and VE().
{
 Edge *e, *e1, *e2=NULL, *e3=NULL, *e4;
 Triangle *t1, *t2, *ta1, *ta4;
 Node *n;
 Vertex *tmp;
 List *ve = VE();
 FOREACHVEEDGE(ve, e, n)
 {
  tmp = e->oppositeVertex(this);
  if (tmp == v3) e2 = e;
  else if (tmp == v4) e3 = e;
 }
 if (!e2 || !e3) {delete(ve); return NULL;}
 ta1 = e2->rightTriangle(this);
 ta4 = e3->leftTriangle(this);
 FOREACHVEEDGE(ve, e, n) if (e == e3) break;
 FOREACHNODECIRCULAR((*ve), n, n)
 {
  e = ((Edge *)n->data);
  if (e == e2) break;
  else e->replaceVertex(this, v2);
 }
 delete(ve);
 e = new Edge(this, v2);
 e1 = new Edge(v2, v3);
 e4 = new Edge(v2, v4);
 t1 = new Triangle(e, e1, e2);
 t2 = new Triangle(e, e3, e4);
 e->t1 = t1; e->t2 = t2;
 e2->replaceTriangle(ta1, t1);
 e3->replaceTriangle(ta4, t2);
 if (ta1) ta1->replaceEdge(e2, e1);
 if (ta4) ta4->replaceEdge(e3, e4);
 e1->t1 = t1; e1->t2 = ta1;
 e4->t1 = ta4; e4->t2 = t2;
 v2->e0 = e0 = e;
// Point p = (*this)-((*v2)-(*this));
// x = p.x; y = p.y; z = p.z;
 return e;
}
bool Vertex::isLinked () const [inline]
TRUE iff vertex is not isolated.
Definition at line 64 of file vertex.h.
References e0.
int Vertex::isOnBoundary () const
TRUE iff vertex is on boundary.
Definition at line 210 of file vertex.cpp.
References e0, Edge::leftTriangle(), Triangle::oppositeEdge(), and Edge::oppositeVertex().
{
 Triangle *t;
 Edge *e;
 Vertex *v;
 if (e0 == NULL) return 0;
 e = e0;
 do
 {
  v = e->oppositeVertex(this);
  t = e->leftTriangle(this);
  if (t == NULL) return 1;
  e = t->oppositeEdge(v);
 } while (e != e0);
 return 0;
}
Edge * Vertex::nextBoundaryEdge () const
Returns the edge following this vertex on the boundary.
This edge is the counterclockwise-most incident edge. Returns NULL if this vertex is not on the boundary.
Definition at line 233 of file vertex.cpp.
References e0, Edge::leftTriangle(), Triangle::oppositeEdge(), and Edge::oppositeVertex().
{
 Triangle *t;
 Edge *e;
 Vertex *v;
 if (e0 == NULL) return NULL;
 e = e0;
 do
 {
  v = e->oppositeVertex(this);
  t = e->leftTriangle(this);
  if (t == NULL) return e;
  e = t->oppositeEdge(v);
 } while (e != e0);
 return NULL;
}
Vertex * Vertex::nextOnBoundary () const
Returns the vertex following this one on the boundary.
If the vertex is on the boundary, this is equivalent to nextBoundaryEdge()->oppositeVertex(v) otherwise returns NULL.
Definition at line 256 of file vertex.cpp.
References nextBoundaryEdge(), and Edge::oppositeVertex().
{
 Edge *e = nextBoundaryEdge();
 if (e != NULL) return e->oppositeVertex(this);
 return NULL;
}
Edge * Vertex::prevBoundaryEdge () const
Returns the edge preceeding this vertex on the boundary.
This edge is the clockwise-most incident edge. Returns NULL if this vertex is not on the boundary.
Definition at line 267 of file vertex.cpp.
References e0, Triangle::oppositeEdge(), Edge::oppositeVertex(), and Edge::rightTriangle().
{
 Triangle *t;
 Edge *e;
 Vertex *v;
 if (e0 == NULL) return NULL;
 e = e0;
 do
 {
  v = e->oppositeVertex(this);
  t = e->rightTriangle(this);
  if (t == NULL) return e;
  e = t->oppositeEdge(v);
 } while (e != e0);
 return NULL;
}
Vertex * Vertex::prevOnBoundary () const
Returns the vertex preceeding this one on the boundary.
If the vertex is on the boundary, this is equivalent to prevBoundaryEdge()->oppositeVertex(v) otherwise returns NULL.
Definition at line 290 of file vertex.cpp.
References Edge::oppositeVertex(), and prevBoundaryEdge().
{
 Edge *e = prevBoundaryEdge();
 if (e != NULL) return e->oppositeVertex(this);
 return NULL;
}
double Vertex::totalAngle () const
Sum of incident angles. Returns -1 if on boundary.
Definition at line 421 of file vertex.cpp.
References FOREACHVEEDGE, Triangle::getAngle(), Edge::isOnBoundary(), Edge::leftTriangle(), and VE().
{
 List *ve = VE();
 double ta = 0.0;
 Edge *e;
 Node *n;
 FOREACHVEEDGE(ve, e, n)
  if (e->isOnBoundary()) {delete(ve); return -1.0;}
  else ta += e->leftTriangle(this)->getAngle(this);
 delete(ve);
 return ta;
}
double Vertex::totalDihedralAngle () const
Sum of signed dihedral angles. Returns DBL_MAX if on boundary.
Definition at line 401 of file vertex.cpp.
References Edge::dihedralAngle(), FOREACHVEEDGE, Edge::isOnBoundary(), M_PI, List::numels(), and VE().
{
 List *ve = VE();
 double mc = 0;
 Edge *e;
 Node *n;
 FOREACHVEEDGE(ve, e, n)
  if (e->isOnBoundary()) {delete(ve); return DBL_MAX;}
  else mc += (M_PI-e->dihedralAngle());
 mc /= ve->numels();
 delete(ve);
 return mc;
}
int Vertex::valence () const
Returns the number of incident edges.
Definition at line 200 of file vertex.cpp.
References List::numels(), and VE().
{
 List *ve = VE();
 int n = ve->numels();
 delete(ve);
 return n;
}
List * Vertex::VE () const
List of incident edges.
Returns the list of edges incident at this vertex. The list is counter-clockwise ordered. In the case of an internal vertex the list starts from 'e0' If the vertex is on the boundary, the list starts from its clockwise-most incident boundary edge.
Definition at line 73 of file vertex.cpp.
References List::appendHead(), List::appendTail(), e0, Edge::leftTriangle(), List::numels(), Triangle::oppositeEdge(), Edge::oppositeVertex(), List::popHead(), and Edge::rightTriangle().
{
 Triangle *t;
 Edge *e;
 Vertex *v;
 List *ve = new List();
 if (e0 == NULL) return ve;
 e = e0;
 do
 {
  ve->appendTail(e);
  v = e->oppositeVertex(this);
  t = e->leftTriangle(this);
  if (t == NULL) break;
  e = t->oppositeEdge(v);
 } while (e != e0);
 if (e == e0 && ve->numels() > 1) return ve;
 ve->popHead();
 e = e0;
 do
 {
  ve->appendHead(e);
  v = e->oppositeVertex(this);
  t = e->rightTriangle(this);
  if (t == NULL) break;
  e = t->oppositeEdge(v);
 } while (e != e0);
 return ve;
}
double Vertex::voronoiArea () const
A third of the total area of incident triangles.
Definition at line 440 of file vertex.cpp.
References Triangle::area(), FOREACHVTTRIANGLE, and VT().
{
 List *vt = VT();
 Node *n;
 Triangle *t;
 double va=0.0;
 FOREACHVTTRIANGLE(vt, t, n) va += t->area();
 delete(vt);
 return va/3.0;
}
List * Vertex::VT () const
List of incident triangles.
Returns the list of triangles incident at this. The list is counter- clockwise ordered. In the case of an internal vertex the list starts from the triangle on the left of e0, when looking from this. If the vertex is on the boundary, the list starts from the clockwise-most boundary triangle.
Definition at line 148 of file vertex.cpp.
References List::appendHead(), List::appendTail(), e0, Edge::leftTriangle(), List::numels(), Triangle::oppositeEdge(), Edge::oppositeVertex(), and Edge::rightTriangle().
{
 Triangle *t;
 Edge *e;
 Vertex *v;
 List *vt = new List();
 if (e0 == NULL) return vt;
 e = e0;
 do
 {
  v = e->oppositeVertex(this);
  t = e->leftTriangle(this);
  if (t == NULL) break;
  vt->appendTail(t);
  e = t->oppositeEdge(v);
 } while (e != e0);
 if (e == e0 && vt->numels() > 1) return vt;
 e = e0;
 do
 {
  v = e->oppositeVertex(this);
  t = e->rightTriangle(this);
  if (t == NULL) break;
  vt->appendHead(t);
  e = t->oppositeEdge(v);
 } while (e != e0);
 return vt;
}
List * Vertex::VV () const
List of adjacent vertices.
Returns the list of vertices which are linked to this through an edge. The list is counter-clockwise ordered. In the case of an internal ver- tex the list starts from the opposite vertex of e0. If the vertex is on the boundary, the list starts from the opposite vertex of the clock- wise-most boundary edge.
Definition at line 111 of file vertex.cpp.
References List::appendHead(), List::appendTail(), e0, Edge::leftTriangle(), List::numels(), Triangle::oppositeEdge(), Edge::oppositeVertex(), List::popHead(), and Edge::rightTriangle().
{
 Triangle *t;
 Edge *e;
 Vertex *v;
 List *vv = new List();
 if (e0 == NULL) return vv;
 e = e0;
 do
 {
  v = e->oppositeVertex(this);
  vv->appendTail(v);
  t = e->leftTriangle(this);
  if (t == NULL) break;
  e = t->oppositeEdge(v);
 } while (e != e0);
 if (e == e0 && vv->numels() > 1) return vv;
 vv->popHead();
 e = e0;
 do
 {
  v = e->oppositeVertex(this);
  vv->appendHead(v);
  t = e->rightTriangle(this);
  if (t == NULL) break;
  e = t->oppositeEdge(v);
 } while (e != e0);
 return vv;
}
int Vertex::zip (const bool check_geom = 1)
Zips the gap starting from here.
Definition at line 459 of file vertex.cpp.
References Node::data, e0, FOREACHVEEDGE, List::head(), Edge::isOnBoundary(), Edge::oppositeVertex(), Triangle::replaceEdge(), Edge::replaceTriangle(), Edge::replaceVertex(), Edge::t1, Edge::t2, List::tail(), Edge::v1, Edge::v2, VE(), and zip().
{
 Node *n;
 Edge *e;
 List *ve = VE();
 Edge *be1 = (Edge *)ve->head()->data;
 Edge *be2 = (Edge *)ve->tail()->data;
 delete(ve);
 if (!be1->isOnBoundary() || !be2->isOnBoundary()) return 0;
 Vertex *ov1 = be1->oppositeVertex(this);
 Vertex *ov2 = be2->oppositeVertex(this);
 if (check_geom && ((*ov1)!=(*ov2))) return 0;
 if (ov1 != ov2)
 {
  ve = ov2->VE();
  FOREACHVEEDGE(ve, e, n) e->replaceVertex(ov2, ov1);
  delete(ve);
  ov2->e0 = NULL;
 }
 Triangle *t = (be2->t1!=NULL)?(be2->t1):(be2->t2);
 t->replaceEdge(be2, be1);
 be1->replaceTriangle(NULL, t);
 be2->v1=be2->v2=NULL;
 e0 = ov1->e0 = be1;
 return 1+ov1->zip(check_geom);
}
Member Data Documentation
class Edge* Vertex::e0
One of the incident edges.
Definition at line 48 of file vertex.h.
unsigned char Vertex::mask
bit-mask for marking purposes
Definition at line 49 of file vertex.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/vertex.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/MESH_STRUCTURE/vertex.cpp