OpenCog Framework: SymMatrix3x3 Class Reference
SymMatrix3x3 Class Reference
Symmetric 3x3 matrix.
#include <matrix.h>
Public Member Functions
SymMatrix3x3 ()
Constructs a null matrix.
SymMatrix3x3 (const double &a11, const double &a12, const double &a22, const double &a13, const double &a23, const double &a33)
Constructs a fully initialized matrix.
SymMatrix3x3 (const double &a, const double &b, const double &c)
Constructs a symmetric matrix as the product of Transpose(a,b,c) and (a,b,c).
SymMatrix3x3 (const Matrix3x3 &S)
Constructs a symmetric 3x3 matrix as a copy of an existing 3x3 matrix S.
bool operator== (const SymMatrix3x3 &s)
bool operator!= (const SymMatrix3x3 &s)
void operator+= (const SymMatrix3x3 &)
Sum another matrix.
void operator-= (const SymMatrix3x3 &)
Subtract another matrix.
void operator*= (const double &)
Multiply by a scalar.
void operator/= (const double &d)
Divide by a scalar.
SymMatrix3x3 operator+ (const SymMatrix3x3 &) const
Returns the sum of this and another matrix.
SymMatrix3x3 operator* (const double &) const
Returns the product of this matrix with a scalar.
void operator= (const double &d)
Initializes all elements to 'd'.
double determinant () const
Returns the determinant.
bool isNull () const
Returns TRUE iff the matrix is made of all zeroes.
double lrMultiply (const double &a, const double &b, const double &c) const
Returns Transpose(a,b,c)*M*(a,b,c)
double lrMultiply (const double &v1, const double &v2, const double &v3, const double &w1, const double &w2, const double &w3) const
Returns the (scalar) result of v*M*w.
bool invert ()
Inverts this matrix. Returns FALSE if not invertible, TRUE otherwise.
double trace () const
Returns the matrix trace.
void diagonalize (double eigen_vals[3], double eigen_vecs[9]) const
Compute eigenvalues and eigenvectors of the matrix (Jacobi method).
void getEigenvalues (double *l1, double *l2, double *l3) const
Compute the eigenvalues l1, l2 and l3.
void getMinEigenvector (double *a, double *b, double *c) const
Compute the eigenvector (a,b,c) corresponding to the minimum eigenvalue.
void getMaxEigenvector (double *a, double *b, double *c) const
void print (FILE *id=stdout) const
Prints the contents of the matrix to the specified FILE id.
Public Attributes
double M [6]
Actual values of the matrix.
Detailed Description
Symmetric 3x3 matrix.
Compact storage:
M[0] M[1] M[3]
M[1] M[2] M[4]
M[3] M[4] M[5]
Definition at line 109 of file matrix.h.
Constructor & Destructor Documentation
SymMatrix3x3::SymMatrix3x3 () [inline]
Constructs a null matrix.
Definition at line 114 of file matrix.h.
References M.
SymMatrix3x3::SymMatrix3x3 (const double & a11, const double & a12, const double & a22, const double & a13, const double & a23, const double & a33)
Constructs a fully initialized matrix.
Definition at line 173 of file matrix.cpp.
References M.
{
 M[0] = a11; M[1] = a12; M[3] = a13;
             M[2] = a22; M[4] = a23;
                         M[5] = a33;
}
SymMatrix3x3::SymMatrix3x3 (const double & a, const double & b, const double & c)
Constructs a symmetric matrix as the product of Transpose(a,b,c) and (a,b,c).
Definition at line 184 of file matrix.cpp.
References M.
{
 M[0] = x*x;  M[1] = x*y;  M[3] = x*z;
              M[2] = y*y;  M[4] = y*z;
                           M[5] = z*z;
}
SymMatrix3x3::SymMatrix3x3 (const Matrix3x3 & S)
Constructs a symmetric 3x3 matrix as a copy of an existing 3x3 matrix S.
If 'S' is not symmetric, its upper triangular part is reflected to the lower.
Definition at line 194 of file matrix.cpp.
References Matrix3x3::M, and M.
{
 M[0] = q.M[0]; M[1] = q.M[1]; M[3] = q.M[2];
                M[2] = q.M[4]; M[4] = q.M[5];
                               M[5] = q.M[8];
}
Member Function Documentation
double SymMatrix3x3::determinant () const [inline]
Returns the determinant.
Definition at line 145 of file matrix.h.
References M.
{return (M[0]*M[2]*M[5])+(2.0*M[1]*M[3]*M[4])-(M[0]*M[4]*M[4])-(M[2]*M[3]*M[3])-(M[5]*M[1]*M[1]);}
void SymMatrix3x3::diagonalize (double eigen_vals[3], double eigen_vecs[9]) const
Compute eigenvalues and eigenvectors of the matrix (Jacobi method).
The calling function is responsible of verifying that the matrix is diagonalizable. Also, eigen_vals and eigen_vecs must be allocated prior to calling this method.
eigen_vals are sorted in ascending order (i.e., eigen_vals[0] is the smallest one).
eigen_vecs are sorted accordingly to the order of eigen_vals, that is, (eigen_vecs[0], eigen_vecs[1], eigen_vecs[2]) is the eigenvector corresponding to eigen_vals[0].
Definition at line 310 of file matrix.cpp.
References FABS, and M.
{
 static const double EPS = 0.00001;
 static const double cos_pi_4 = 0.70710678;
 static const int MAX_ITER = 100;
 double a_P[6], v_P[9];
 double *a = a_P, *v = v_P;
 double a_norm,a_normEPS,thr,thr_nn;
 int nb_iter = 0;
 int i,j,k,ij,jj,ik,l,m,lm,mq,lq,ll,mm,imv,im,iq,ilv,il;
 int index_P[3];
 int *index = index_P;
 double a_ij,a_lm,a_ll,a_mm,a_im,a_il,a_lm_2,v_ilv,v_imv,x;
 double sinx,sinx_2,cosx,cosx_2,sincos,delta;
 a[0] = M[0]; a[1] = M[1]; a[2] = M[2];
 a[3] = M[3]; a[4] = M[4]; a[5] = M[5];
 a--;
 // Step 2 : Init diagonalization matrix as the unit matrix
 for (ij=0, i=0; i<3; i++) for (j=0; j<3; j++) v[ij++] = (i==j)?(1.0):(0.0);
 v--;
 // Step 3 : compute the weight of the non diagonal terms
 a_norm = 0.0;
 for (i=1, ij=1; i<=3; i++) for (j=1; j<=i; j++, ij++) if( i!=j ) {a_ij = a[ij]; a_norm += a_ij*a_ij;}
 if( a_norm != 0.0 )
 {
   a_normEPS = a_norm*EPS;
   thr   = a_norm  ;
   // Step 4 : rotations
   while (thr > a_normEPS && nb_iter < MAX_ITER)
   {
   nb_iter++;
   thr_nn = thr / 6;
   for (l=1; l<3; l++)
   for (m=l+1; m<=3; m++)
   {
     // compute sinx and cosx
     lq = (l*l-l)/2; mq = (m*m-m)/2;
     lm = l+mq; a_lm = a[lm];
     a_lm_2 = a_lm*a_lm;
     if( a_lm_2 < thr_nn ) continue;
     ll = l+lq; mm = m+mq;
     a_ll = a[ll]; a_mm = a[mm];
     delta = a_ll - a_mm;
     if (delta==0.0) {sinx = -cos_pi_4; cosx = cos_pi_4;}
     else {x = -atan( (a_lm+a_lm) / delta )/2.0; sinx=sin(x); cosx=cos(x);}
     sinx_2  = sinx*sinx;
     cosx_2  = cosx*cosx;
     sincos  = sinx*cosx;
     // rotate L and M columns
     ilv = 3*(l-1); imv = 3*(m-1);
     for( i=1; i<=3;i++ )
     {
     if( (i!=l) && (i!=m) )
     {
     iq = (i*i-i)/2;
     im = (i<m)?(i+mq):(m+iq);
     a_im = a[im];
     il = (i<l)?(i+lq):(l+iq);
     a_il = a[il];
     a[il] =  a_il*cosx - a_im*sinx;
     a[im] =  a_il*sinx + a_im*cosx;
     }
     ilv++; imv++;
     v_ilv = v[ilv]; v_imv = v[imv];
     v[ilv] = cosx*v_ilv - sinx*v_imv;
     v[imv] = sinx*v_ilv + cosx*v_imv;
     }
     x = a_lm*sincos; x+=x;
     a[ll] =  a_ll*cosx_2 + a_mm*sinx_2 - x;
     a[mm] =  a_ll*sinx_2 + a_mm*cosx_2 + x;
     a[lm] =  0.0;
     thr = FABS( thr - a_lm_2 );
   }
   }
 }
 // Step 5: index conversion and copy eigen values
 // back from Fortran to C++
 a++;
 for( i=0; i<3; i++ ) { k = i + (i*(i+1))/2; eigen_val[i] = a[k];}
 // Step 6: sort the eigen values and eigen vectors
 for( i=0; i<3; i++ ) index[i] = i;
 for( i=0; i<(3-1); i++ ) {
   x = eigen_val[i];
   k = i;
   for( j=i+1; j<3; j++ ) if( x < eigen_val[j] ) { k = j; x = eigen_val[j];}
   eigen_val[k] = eigen_val[i];
   eigen_val[i] = x;
   jj   = index[k];
   index[k] = index[i];
   index[i] = jj;
 }
 // Step 7: save the eigen vectors
 v++; // back from Fortran to to C++
 ij = 0;
 for( k=0; k<3; k++ ) for(ik = index[k]*3, i=0; i<3; i++ ) eigen_vec[ij++] = v[ik++];
}
void SymMatrix3x3::getEigenvalues (double * l1, double * l2, double * l3) const
Compute the eigenvalues l1, l2 and l3.
This method is much faster and precise than 'diagonalize', as it uses an analytical direct method instead of an iterative approach.
Definition at line 441 of file matrix.cpp.
References M.
{
 double a11 = M[0], a12 = M[1], a22 = M[2], a13 = M[3], a23 = M[4], a33 = M[5];
 double c0 = (a11*a22*a33)+(2.0*a12*a13*a23)-(a11*a23*a23)-(a22*a13*a13)-(a33*a12*a12); // Mat. Determinant
 double c1 = a11*a22-a12*a12+a11*a33-a13*a13+a22*a33-a23*a23;
 double c2 = a11+a22+a33;
 double a = (3*c1-c2*c2)/3.0;
 double b = (9*c1*c2-2*c2*c2*c2-27*c0)/27.0;
 double Q = ((b*b)/4.0)+((a*a*a)/27.0);
 if (Q>1.0e-12) {*L1 = *L2 = *L3 = a11; return;} // Evecs = (1,0,0), (0,1,0), (0,0,1)
 double l1, l2, l3; // Eigenvalues to be computed
 if (Q>=0) {double p=(b>0)?(pow(b/2, 1.0/3.0)):(0); l1=l2=((c2/3.0)+p); l3=((c2/3.0)-2.0*p);}
 else
 {
  double t = atan2(sqrt(-Q), -b/2.0)/3.0, r = pow(((b*b)/4.0)-Q, 1.0/6.0);
  double cos_t = cos(t), sin_t = sin(t);
  const double sq3 = sqrt(3.0);
  l1 = l2 = l3 = (c2/3.0);
  l1 += (2*r*cos_t);
  l2 -= r*(cos_t+sq3*sin_t);
  l3 -= r*(cos_t-sq3*sin_t);
 }
 if (l1<=l2 && l1<=l3) {*L1=l1; *L2=(l2<l3)?(l2):(l3); *L3=(l2<l3)?(l3):(l2);}
 else if (l2<=l1 && l2<=l3) {*L1=l2; *L2=(l1<l3)?(l1):(l3); *L3=(l1<l3)?(l3):(l1);}
 else {*L1=l3; *L2=(l1<l2)?(l1):(l2); *L3=(l1<l2)?(l2):(l1);}
}
void SymMatrix3x3::getMaxEigenvector (double * a, double * b, double * c) const
This method is much faster and precise than 'diagonalize', as it uses an analytical direct method instead of an iterative approach.
Definition at line 500 of file matrix.cpp.
References M, and SymMatrix3x3().
{
 SymMatrix3x3(-M[0], -M[1], -M[2], -M[3], -M[4], -M[5]).getMinEigenvector(x, y, z);
}
void SymMatrix3x3::getMinEigenvector (double * a, double * b, double * c) const
Compute the eigenvector (a,b,c) corresponding to the minimum eigenvalue.
This method is much faster and precise than 'diagonalize', as it uses an analytical direct method instead of an iterative approach.
Definition at line 475 of file matrix.cpp.
References getEigenvalues(), and M.
{
 double a11 = M[0], a12 = M[1], a22 = M[2], a13 = M[3], a23 = M[4], a33 = M[5];
 double l, l1, l2, l3, c0, c1, c2;
 getEigenvalues(&l, &l2, &l3);
 if (l==l3 && l==l2) {*x = 1; *y = *z = 0; return;}
 a11-=l; a22-=l; a33-=l;
 double u11 = a22*a33-a23*a23, u12 = a13*a23-a12*a33, u13 = a12*a23-a13*a22;
 double u22 = a11*a33-a13*a13, u23 = a12*a13-a23*a11, u33 = a11*a22-a12*a12;
 l1 = u11*u11+u12*u12+u13*u13;
 l2 = u12*u12+u22*u22+u23*u23;
 l3 = u13*u13+u23*u23+u33*u33;
 if (l1>=l2 && l1>=l3) {c0=u11; c1=u12; c2=u13; l=l1;}
 else if (l2>=l1 && l2>=l3) {c0=u12; c1=u22; c2=u23; l=l2;}
 else {c0=u13; c1=u23; c2=u33; l=l3;}
 l = sqrt(l); *x = c0/l; *y = c1/l; *z = c2/l;
}
bool SymMatrix3x3::invert ()
Inverts this matrix. Returns FALSE if not invertible, TRUE otherwise.
Definition at line 268 of file matrix.cpp.
References FABS, and M.
{
 double det, pos, neg, t, out[6];
 pos = neg = 0.0;
 t =  M[0]*M[2]*M[5]; ((t >= 0.0)?(pos):(neg)) += t;
 t =  M[1]*M[4]*M[3]; ((t >= 0.0)?(pos):(neg)) += t;
 t =  M[3]*M[1]*M[4]; ((t >= 0.0)?(pos):(neg)) += t;
 t = -M[3]*M[2]*M[3]; ((t >= 0.0)?(pos):(neg)) += t;
 t = -M[1]*M[1]*M[5]; ((t >= 0.0)?(pos):(neg)) += t;
 t = -M[0]*M[4]*M[4]; ((t >= 0.0)?(pos):(neg)) += t;
 det = pos+neg;
 t = det/(pos-neg);
 if (FABS(t) >= 1.0e-15)
 {
  out[0] =  (M[2] * M[5] - M[4] * M[4]) /det;
  out[1] = -(M[1] * M[5] - M[4] * M[3]) /det;
  out[2] =  (M[0] * M[5] - M[3] * M[3]) /det;
  out[3] =  (M[1] * M[4] - M[2] * M[3]) /det;
  out[4] = -(M[0] * M[4] - M[1] * M[3]) /det;
  out[5] =  (M[0] * M[2] - M[1] * M[1]) /det;
  M[0] = out[0]; M[1] = out[1]; M[2] = out[2];
  M[3] = out[3]; M[4] = out[4]; M[5] = out[5];
  return 1;
 }
 return 0;
}
bool SymMatrix3x3::isNull () const [inline]
Returns TRUE iff the matrix is made of all zeroes.
Definition at line 148 of file matrix.h.
References M.
{return (M[0]==0 && M[1]==0 && M[2]==0 && M[3]==0 && M[4]==0 && M[5]==0);}
double SymMatrix3x3::lrMultiply (const double & v1, const double & v2, const double & v3, const double & w1, const double & w2, const double & w3) const
Returns the (scalar) result of v*M*w.
Definition at line 260 of file matrix.cpp.
References M.
{
 return (w1*(v1*M[0] + v2*M[1] + v3*M[3]) + w2*(v1*M[1] + v2*M[2] + v3*M[4]) + w3*(v1*M[3] + v2*M[4] + v3*M[5]));
}
double SymMatrix3x3::lrMultiply (const double & a, const double & b, const double & c) const
Returns Transpose(a,b,c)*M*(a,b,c)
Returns the (scalar) result of multiplying the matrix on the left and on the right by the vector (a,b,c).
Definition at line 248 of file matrix.cpp.
References M.
{
 double a,b,c;
 a = x*M[0] + y*M[1] + z*M[3];
 b = x*M[1] + y*M[2] + z*M[4];
 c = x*M[3] + y*M[4] + z*M[5];
 return (x*a + y*b + z*c);
}
bool SymMatrix3x3::operator!= (const SymMatrix3x3 & s) [inline]
Parameters:
s True iff at least one different entry
Definition at line 131 of file matrix.h.
References M.
  {return (M[0]!=s.M[0] || M[1]!=s.M[1] || M[2]!=s.M[2] || M[3]!=s.M[3] || M[4]!=s.M[4] || M[5]!=s.M[5]);}
SymMatrix3x3 SymMatrix3x3::operator* (const double & d) const
Returns the product of this matrix with a scalar.
Definition at line 240 of file matrix.cpp.
References M, and SymMatrix3x3().
{
 return SymMatrix3x3(M[0]*d, M[1]*d, M[2]*d, M[3]*d, M[4]*d, M[5]*d);
}
void SymMatrix3x3::operator*= (const double & d)
Multiply by a scalar.
Definition at line 222 of file matrix.cpp.
References M.
{
 M[0] *= d; M[1] *= d; M[2] *= d;
 M[3] *= d; M[4] *= d; M[5] *= d;
}
SymMatrix3x3 SymMatrix3x3::operator+ (const SymMatrix3x3 & s) const
Returns the sum of this and another matrix.
Definition at line 231 of file matrix.cpp.
References M, and SymMatrix3x3().
{
 return SymMatrix3x3(M[0]+s.M[0], M[1]+s.M[1], M[2]+s.M[2],
                     M[3]+s.M[3], M[4]+s.M[4], M[5]+s.M[5]);
}
void SymMatrix3x3::operator+= (const SymMatrix3x3 & s)
Sum another matrix.
Definition at line 204 of file matrix.cpp.
References M.
{
 M[0] += s.M[0]; M[1] += s.M[1]; M[2] += s.M[2];
 M[3] += s.M[3]; M[4] += s.M[4]; M[5] += s.M[5];
}
void SymMatrix3x3::operator-= (const SymMatrix3x3 & s)
Subtract another matrix.
Definition at line 213 of file matrix.cpp.
References M.
{
 M[0] -= s.M[0]; M[1] -= s.M[1]; M[2] -= s.M[2];
 M[3] -= s.M[3]; M[4] -= s.M[4]; M[5] -= s.M[5];
}
void SymMatrix3x3::operator/= (const double & d) [inline]
Divide by a scalar.
Definition at line 137 of file matrix.h.
References operator*=().
void SymMatrix3x3::operator= (const double & d) [inline]
Initializes all elements to 'd'.
Definition at line 142 of file matrix.h.
References M.
{M[0]=M[1]=M[2]=M[3]=M[4]=M[5]=d;}
bool SymMatrix3x3::operator== (const SymMatrix3x3 & s) [inline]
Parameters:
s True iff all entries are equal
Definition at line 129 of file matrix.h.
References M.
  {return (M[0]==s.M[0] && M[1]==s.M[1] && M[2]==s.M[2] && M[3]==s.M[3] && M[4]==s.M[4] && M[5]==s.M[5]);}
void SymMatrix3x3::print (FILE * id = stdout) const
Prints the contents of the matrix to the specified FILE id.
If no 'id' is specifyed, results are printed to stdout.
Definition at line 507 of file matrix.cpp.
References M.
{
 fprintf(fp,"%e %e %e\n",M[0],M[1],M[3]);
 fprintf(fp,"%e %e %e\n",M[1],M[2],M[4]);
 fprintf(fp,"%e %e %e\n",M[3],M[4],M[5]);
}
double SymMatrix3x3::trace () const [inline]
Returns the matrix trace.
Definition at line 164 of file matrix.h.
References M.
{return M[0]+M[2]+M[5];}
Member Data Documentation
double SymMatrix3x3::M[6]
Actual values of the matrix.
Definition at line 112 of file matrix.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/matrix.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/matrix.cpp