OpenCog Framework: /home/wondereamer/object_detection/JMeshLib-1.2/src/MESH_STRUCTURE/io.cpp File Reference
io.cpp File Reference
#include "jmesh.h"
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
Defines
#define VRML1_HEADER "#VRML V1.0 ascii"
#define VRML1_HSIZE 16
#define VRML2_HEADER "#VRML V2.0 utf8"
#define VRML2_HSIZE 15
#define OFF_HEADER "OFF"
#define OFF_HSIZE 3
#define PLY_HEADER "ply"
#define PLY_HSIZE 3
#define IV_HEADER "#Inventor V2.1 ascii"
#define IV_HSIZE 20
#define PLY_FORMAT_ASCII 0
#define PLY_FORMAT_BIN_L 1
#define PLY_FORMAT_BIN_B 2
#define TVI1(a) ((int)(((Triangle *)a->data)->v1()->x))
#define TVI2(a) ((int)(((Triangle *)a->data)->v2()->x))
#define TVI3(a) ((int)(((Triangle *)a->data)->v3()->x))
#define MAX_READLINE_CHARS 1024
Functions
void PRINT_HEADING_COMMENT (FILE *f)
void PRINT_PLY_COMMENT (FILE *f)
bool sameString (char *a, char *b)
Returns TRUE if the two strings are equal in a case-insensitive sense /////.
void endian_swap_long (unsigned char *p)
char * readLineFromFile (FILE *in, bool exit_on_eof=1)
bool seek_keyword (FILE *fp, const char *kw)
void skipCommentAndBlankLines (FILE *fp)
int ply_parseElements (FILE *in, const char *elname)
void ply_checkVertexProperties (FILE *in)
int ply_getOverhead (FILE *in, int format, const char *element)
void ply_checkFaceProperties (FILE *in)
void ply_readOverhead (FILE *in, int format, int oh)
int ply_readVCoords (FILE *in, int format, int ph, int oh, float *x, float *y, float *z)
int ply_readFIndices (FILE *in, int format, int ph, int *nv, int *x, int *y, int *z)
int ply_readAnotherFIndex (FILE *in, int format, int *x)
Define Documentation
#define IV_HEADER "#Inventor V2.1 ascii"
Definition at line 42 of file io.cpp.
#define IV_HSIZE 20
Definition at line 43 of file io.cpp.
#define MAX_READLINE_CHARS 1024
#define OFF_HEADER "OFF"
Definition at line 38 of file io.cpp.
#define OFF_HSIZE 3
Definition at line 39 of file io.cpp.
#define PLY_FORMAT_ASCII 0
Definition at line 45 of file io.cpp.
#define PLY_FORMAT_BIN_B 2
Definition at line 47 of file io.cpp.
#define PLY_FORMAT_BIN_L 1
Definition at line 46 of file io.cpp.
#define PLY_HEADER "ply"
Definition at line 40 of file io.cpp.
#define PLY_HSIZE 3
Definition at line 41 of file io.cpp.
#define TVI1 (a) ((int)(((Triangle *)a->data)->v1()->x))
Definition at line 49 of file io.cpp.
#define TVI2 (a) ((int)(((Triangle *)a->data)->v2()->x))
Definition at line 50 of file io.cpp.
#define TVI3 (a) ((int)(((Triangle *)a->data)->v3()->x))
Definition at line 51 of file io.cpp.
#define VRML1_HEADER "#VRML V1.0 ascii"
Definition at line 34 of file io.cpp.
#define VRML1_HSIZE 16
Definition at line 35 of file io.cpp.
#define VRML2_HEADER "#VRML V2.0 utf8"
Definition at line 36 of file io.cpp.
#define VRML2_HSIZE 15
Definition at line 37 of file io.cpp.
Function Documentation
void endian_swap_long (unsigned char * p) [inline]
Definition at line 98 of file io.cpp.
{
 unsigned char b0,b1,b2,b3;
 b0 = *p; b1 = *(p+1); b2 = *(p+2); b3 = *(p+3);
 *p = b3; *(p+1) = b2; *(p+2) = b1; *(p+3) = b0;
}
void ply_checkFaceProperties (FILE * in)
Definition at line 930 of file io.cpp.
References JMesh::error().
{
 char keyword[64], ltype[64], uctype[64], dtype[64], dval[64];
 if (fscanf(in,"%64s %64s %64s %64s %64s\n",keyword,ltype,uctype,dtype,dval) < 5) JMesh::error("Unexpected token or end of file!\n");
 if (strcmp(keyword,"property")) JMesh::error("property definition expected!\n");
 if (strcmp(ltype,"list")) JMesh::error("list property expected!\n");
 if (strcmp(uctype,"uchar") && strcmp(uctype,"uint8")) JMesh::error("uchar property expected!\n");
 if (strcmp(dtype,"int") && strcmp(dtype,"int32")) JMesh::error("int property expected!\n");
 if (strcmp(dval,"vertex_indices")) JMesh::error("vertex_indices property expected!\n");
}
void ply_checkVertexProperties (FILE * in)
Definition at line 886 of file io.cpp.
References JMesh::error().
{
 char keyword[64], dtype[64], dval[64];
 if (fscanf(in,"%64s %64s %64s\n",keyword,dtype,dval) < 3) JMesh::error("Unexpected token or end of file!\n");
 if (strcmp(keyword,"property")) JMesh::error("property definition expected!\n");
 if (strcmp(dtype,"float") && strcmp(dtype,"float32")) JMesh::error("float property expected!\n");
 if (strcmp(dval,"x")) JMesh::error("'x' float property expected!\n");
 if (fscanf(in,"%64s %64s %64s\n",keyword,dtype,dval) < 3) JMesh::error("Unexpected token or end of file!\n");
 if (strcmp(keyword,"property")) JMesh::error("property definition expected!\n");
 if (strcmp(dtype,"float") && strcmp(dtype,"float32")) JMesh::error("float property expected!\n");
 if (strcmp(dval,"y")) JMesh::error("'y' float property expected!\n");
 if (fscanf(in,"%64s %64s %64s\n",keyword,dtype,dval) < 3) JMesh::error("Unexpected token or end of file!\n");
 if (strcmp(keyword,"property")) JMesh::error("property definition expected!\n");
 if (strcmp(dtype,"float") && strcmp(dtype,"float32")) JMesh::error("float property expected!\n");
 if (strcmp(dval,"z")) JMesh::error("'z' float property expected!\n");
}
int ply_getOverhead (FILE * in, int format, const char * element)
Definition at line 903 of file io.cpp.
References JMesh::error(), and readLineFromFile().
{
 char keyword[64], ptype[64], pname[64];
 int oh = 0;
 long pos = ftell(in);
 char *rline = readLineFromFile(in);
 if (!sscanf(rline,"%64s ",keyword)) JMesh::error("Unexpected token or end of file!\n");
 while (!strcmp(keyword, "property"))
 {
  if (sscanf(rline,"%64s %64s %64s",keyword,ptype,pname) < 3) JMesh::error("Unexpected token or end of file!\n");
  if (!strcmp(element,"vertex") && !strcmp(pname,"x")) break;
  else if (!strcmp(element,"face") && !strcmp(ptype,"list")) break;
  pos = ftell(in);
  if (!strcmp(ptype, "char") || !strcmp(ptype, "uchar")) oh += (format)?(1):1;
  else if (!strcmp(ptype, "short") || !strcmp(ptype, "ushort")) oh += (format)?(2):1;
  else if (!strcmp(ptype, "int") || !strcmp(ptype, "uint") ||
           !strcmp(ptype, "float") || !strcmp(ptype,"float32")) oh += (format)?(4):1;
  else if (!strcmp(ptype, "double")) oh += (format)?(8):1;
  else if (!strcmp(ptype, "list")) JMesh::error("list properties other than face indices are not supported!\n");
  else JMesh::error("Unrecognized property type!\n");
  if (!sscanf(readLineFromFile(in),"%64s ",keyword)) JMesh::error("Unexpected token or end of file!\n");
 }
 fseek(in, pos, SEEK_SET);
 return oh;
}
int ply_parseElements (FILE * in, const char * elname)
Definition at line 866 of file io.cpp.
References JMesh::error().
{
 char c, keyword[64];
 int num;
 // skip comments
 if (!fscanf(in,"%64s ",keyword)) JMesh::error("Unexpected token or end of file!\n");
 while (!strcmp(keyword,"comment") || !strcmp(keyword,"obj_info"))
 {
  while ((c = fgetc(in)) != '\n') if (c==EOF) JMesh::error("\nUnexpected end of file!\n");
  if (!fscanf(in,"%64s ",keyword)) JMesh::error("Unexpected token or end of file!\n");
 }
 if (strcmp(keyword,"element")) JMesh::error("element definition expected!\n");
 if (!fscanf(in,"%64s ",keyword)) JMesh::error("Unexpected token or end of file!\n");
 if (strcmp(keyword,elname)) JMesh::error("Sorry. Element type '%s' is not supported!\n",keyword);
 if (!fscanf(in,"%d\n",&num)) JMesh::error("Unexpected token or end of file!\n");
 if (num <= 0) JMesh::error("Unexpected empty element list!\n");
 return num;
}
int ply_readAnotherFIndex (FILE * in, int format, int * x)
Definition at line 1002 of file io.cpp.
References endian_swap_long(), JMesh::error(), PLY_FORMAT_ASCII, and PLY_FORMAT_BIN_B.
{
 if (format == PLY_FORMAT_ASCII) return (fscanf(in,"%d", x));
 if (fread(x, 4, 1, in) < 1) JMesh::error("Unexpected end of file!\n");
 if (format == PLY_FORMAT_BIN_B) endian_swap_long((unsigned char *)(x));
 return 1;
}
int ply_readFIndices (FILE * in, int format, int ph, int * nv, int * x, int * y, int * z)
Definition at line 978 of file io.cpp.
References endian_swap_long(), PLY_FORMAT_ASCII, PLY_FORMAT_BIN_B, and ply_readOverhead().
{
 unsigned char nvs;
 int vc[3];
 ply_readOverhead(in, format, ph);
 if (format == PLY_FORMAT_ASCII) {fscanf(in,"%d %d %d %d", nv, x, y, z); return 1;}
 fread(&nvs, 1, 1, in);
 *nv = (int)nvs;
 fread(vc, 4, 3, in);
 *x = vc[0]; *y = vc[1]; *z = vc[2];
 if (format == PLY_FORMAT_BIN_B)
 {
  endian_swap_long((unsigned char *)(x));
  endian_swap_long((unsigned char *)(y));
  endian_swap_long((unsigned char *)(z));
 }
 return 1;
}
void ply_readOverhead (FILE * in, int format, int oh)
Definition at line 941 of file io.cpp.
References PLY_FORMAT_ASCII.
{
 int i;
 static char token[1024];
 if (format == PLY_FORMAT_ASCII) for (i=0; i<oh; i++) fscanf(in, "%s", token);
 else for (i=0; i<oh; i++) fgetc(in);
}
int ply_readVCoords (FILE * in, int format, int ph, int oh, float * x, float * y, float * z)
Definition at line 950 of file io.cpp.
References endian_swap_long(), JMesh::error(), PLY_FORMAT_ASCII, PLY_FORMAT_BIN_B, and ply_readOverhead().
{
 float vc[3];
 ply_readOverhead(in, format, ph);
 if (format == PLY_FORMAT_ASCII)
 {
  if (fscanf(in,"%f %f %f", x, y, z) < 3) JMesh::error("Unexpected token or end of file!\n");
 }
 else
 {
  if (fread(vc, 4, 3, in) < 3) JMesh::error("Unexpected end of file!\n");
  *x = vc[0]; *y = vc[1]; *z = vc[2];
  if (format == PLY_FORMAT_BIN_B)
  {
   endian_swap_long((unsigned char *)(x));
   endian_swap_long((unsigned char *)(y));
   endian_swap_long((unsigned char *)(z));
  }
 }
 ply_readOverhead(in, format, oh);
 return 1;
}
void PRINT_HEADING_COMMENT (FILE * f) [inline]
Definition at line 53 of file io.cpp.
References JMesh::app_name, JMesh::app_url, JMesh::app_version, and JMesh::app_year.
{
 if (JMesh::app_name != NULL)
 {
  fprintf(f, "# File created by %s",JMesh::app_name);
  if (JMesh::app_version != NULL)
  {
   fprintf(f, " v%s",JMesh::app_version);
   if (JMesh::app_year != NULL) fprintf(f, " (%s)",JMesh::app_year);
  }
  fprintf(f, "\n");
  if (JMesh::app_url != NULL) fprintf(f, "# %s\n",JMesh::app_url);
 }
 fprintf(f, "\n");
}
void PRINT_PLY_COMMENT (FILE * f) [inline]
Definition at line 69 of file io.cpp.
References JMesh::app_name, JMesh::app_url, JMesh::app_version, and JMesh::app_year.
{
 if (JMesh::app_name != NULL)
 {
  fprintf(f, "comment File created by %s",JMesh::app_name);
  if (JMesh::app_version != NULL)
  {
   fprintf(f, " v%s",JMesh::app_version);
   if (JMesh::app_year != NULL) fprintf(f, " (%s)",JMesh::app_year);
  }
  fprintf(f, "\n");
  if (JMesh::app_url != NULL) fprintf(f, "comment %s\n",JMesh::app_url);
 }
}
char* readLineFromFile (FILE * in, bool exit_on_eof = 1)
Definition at line 109 of file io.cpp.
References JMesh::error(), MAX_READLINE_CHARS, and JMesh::warning().
{
#define MAX_READLINE_CHARS  1024
 static char line[MAX_READLINE_CHARS];
 int i=0;
 char c;
 while ((c = fgetc(in)) != '\n' && i<(MAX_READLINE_CHARS-1))
   if (c==EOF)
   {
    if (exit_on_eof) JMesh::error("\nUnexpected end of file!\n");
    else return NULL;
   }
   else if (c != '\r') line[i++] = c;
 line[i] = '\0';
 if (i==MAX_READLINE_CHARS-1)
  JMesh::warning("readLineFromFile: Line is too long. Truncated !\n");
 return line;
}
bool sameString (char * a, char * b) [inline]
Returns TRUE if the two strings are equal in a case-insensitive sense /////.
Definition at line 86 of file io.cpp.
{
 int i=0;
 while (a[i] != '\0' && b[i] != '\0')
  if (tolower(a[i]) != tolower(b[i++])) return false;
 return (a[i] == '\0' && b[i] == '\0');
}
bool seek_keyword (FILE * fp, const char * kw)
Definition at line 137 of file io.cpp.
{
 static char s[256];
 s[0]='\0';
 do fscanf(fp,"%255s",s); while (strcmp(s,kw) && !feof(fp));
 if (feof(fp)) return 0;
 return 1;
}
void skipCommentAndBlankLines (FILE * fp) [inline]
Definition at line 147 of file io.cpp.
References readLineFromFile().
{
 long pos0;
 char *line, s[2];
 do {pos0 = ftell(fp); line = readLineFromFile(fp);} while (line[0] == '#' || line[0] == '\0' || !sscanf(line,"%1s",s));
 fseek(fp, pos0, SEEK_SET);
}