OpenCog Framework: clusterHeap Class Reference
clusterHeap Class Reference
#include <clusterGraph.h>
Public Member Functions
clusterHeap (int n, clusterEdge **edg)
~clusterHeap ()
void push (clusterEdge *e)
clusterEdge * getFirst ()
clusterEdge * popHead ()
int isEmpty ()
void remove (clusterEdge *e)
void update (clusterEdge *e)
int compare (const void *, const void *)
Comparison of two heap elements.
Public Attributes
clusterEdge ** edges
Detailed Description
Definition at line 46 of file clusterGraph.h.
Constructor & Destructor Documentation
clusterHeap::clusterHeap (int n, clusterEdge ** edg) [inline]
Definition at line 51 of file clusterGraph.h.
References edges, and abstractHeap::positions.
                                       : abstractHeap(n)
  {positions = new int[n+1]; edges = edg; for (int i=0; i<=n; i++) positions[i]=0;}
clusterHeap::~clusterHeap () [inline]
Definition at line 54 of file clusterGraph.h.
References abstractHeap::positions.
{delete(positions);}
Member Function Documentation
int clusterHeap::compare (const void * a, const void * b) [virtual]
Comparison of two heap elements.
This function must be implemented in the extended class. The return value must be <0 if a<b, >0 if a>b or 0 if a=b.
Implements abstractHeap.
Definition at line 31 of file clusterGraph.cpp.
References clusterEdge::cost, and edges.
{
 clusterEdge *a = edges[(j_voidint)e1];
 clusterEdge *b = edges[(j_voidint)e2];
 double l1 = a->cost;
 double l2 = b->cost;
 if (l1 < l2) return -1;
 if (l1 > l2) return 1;
 return 0;
}
clusterEdge* clusterHeap::getFirst () [inline]
Definition at line 57 of file clusterGraph.h.
References edges, abstractHeap::getHead(), and abstractHeap::numels.
{return (numels)?(edges[(j_voidint)getHead()]):(NULL);}
int clusterHeap::isEmpty () [inline]
Definition at line 59 of file clusterGraph.h.
References abstractHeap::numels.
{return (numels==0);}
clusterEdge* clusterHeap::popHead () [inline]
Definition at line 58 of file clusterGraph.h.
References edges, abstractHeap::numels, and abstractHeap::removeHead().
{return (numels)?(edges[(j_voidint)removeHead()]):(NULL);}
void clusterHeap::push (clusterEdge * e) [inline]
Definition at line 56 of file clusterGraph.h.
References clusterEdge::index, and abstractHeap::insert().
{insert((void *)(e->index));}
void clusterHeap::remove (clusterEdge * e) [inline]
Definition at line 61 of file clusterGraph.h.
References abstractHeap::positions, abstractHeap::removeHead(), and abstractHeap::upheap().
  {e->cost = -1; if (positions[e->index]) {upheap(positions[e->index]); removeHead();}}
void clusterHeap::update (clusterEdge * e) [inline]
Definition at line 64 of file clusterGraph.h.
References abstractHeap::downheap(), clusterEdge::index, abstractHeap::positions, push(), and abstractHeap::upheap().
  {if (!positions[e->index]) push(e); else downheap(upheap(positions[e->index]));}
Member Data Documentation
clusterEdge** clusterHeap::edges
Definition at line 49 of file clusterGraph.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/clusterGraph.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/clusterGraph.cpp