OpenCog Framework: clusterGraph Class Reference
clusterGraph Class Reference
#include <clusterGraph.h>
Public Member Functions
clusterGraph (int n, double(*cf)(const void *, const void *))
~clusterGraph ()
clusterEdge * createEdge (graphNode *n1, graphNode *n2)
Creates a new edge out of a pair of nodes. O(degree of nodes).
clusterEdge * getFirstEdge ()
double getLowestCost ()
int collapseFirstEdge (void(*)(const void *, const void *)=NULL)
Private Attributes
int curEdgeIndex
int maxNumEdges
clusterEdge ** ces
clusterHeap * ch
double(* costFunction)(const void *, const void *)
Detailed Description
Definition at line 71 of file clusterGraph.h.
Constructor & Destructor Documentation
clusterGraph::clusterGraph (int n, double(*)(const void *, const void *) cf) [inline]
Definition at line 80 of file clusterGraph.h.
References ces, ch, costFunction, curEdgeIndex, and maxNumEdges.
 {
  ces = new clusterEdge *[n];
  maxNumEdges = n;
  curEdgeIndex = 0;
  ch = new clusterHeap(n, ces);
  costFunction = cf;
 }
clusterGraph::~clusterGraph () [inline]
Definition at line 88 of file clusterGraph.h.
References ces, and ch.
{delete ces; delete ch;}
Member Function Documentation
int clusterGraph::collapseFirstEdge (void(*)(const void *, const void *) mergenodes = NULL)
Definition at line 70 of file clusterGraph.cpp.
References ch, graphEdge::collapse(), clusterEdge::cost, costFunction, Node::data, graphNode::edges, FOREACHNODE, graphEdge::isUnlinked(), graphEdge::n1, graphEdge::n2, clusterHeap::popHead(), and clusterHeap::update().
{
 clusterEdge *e;
 while ((e=ch->popHead())!=NULL) if (!e->isUnlinked()) break;
 if (e==NULL) return 0;
 if (mergenodes != NULL) mergenodes(e->n1, e->n2);
 graphNode *gn = e->n1;
 e->collapse();
 Node *n;
 clusterEdge *ne;
 FOREACHNODE(gn->edges, n)
 {
  ne = (clusterEdge *)n->data;
  ne->cost = costFunction(ne->n1, ne->n2);
  ch->update(ne);
 }
 return 1;
}
clusterEdge * clusterGraph::createEdge (graphNode * n1, graphNode * n2)
Creates a new edge out of a pair of nodes. O(degree of nodes).
If the edges already exists, no new edge is created and the existing one is returned. Otherwise the newly created edge is returned.
Reimplemented from Graph.
Definition at line 44 of file clusterGraph.cpp.
References List::appendHead(), ces, ch, clusterEdge::cost, costFunction, curEdgeIndex, Node::data, Graph::edges, graphNode::edges, FOREACHNODE, maxNumEdges, graphEdge::n1, graphEdge::n2, and clusterHeap::update().
{
 Node *n;
 FOREACHNODE(n1->edges, n)
  if (((clusterEdge *)n->data)->hasNode(n2))
   return (clusterEdge *)n->data;
 if (curEdgeIndex >= maxNumEdges) return NULL;
 clusterEdge *ne = new clusterEdge(n1, n2, curEdgeIndex);
 edges.appendHead(ne);
 ces[curEdgeIndex] = ne;
 ne->cost = costFunction(ne->n1, ne->n2);
 ch->update(ne);
 curEdgeIndex++;
 return ne;
}
clusterEdge * clusterGraph::getFirstEdge ()
Definition at line 64 of file clusterGraph.cpp.
References ch, clusterHeap::getFirst(), clusterHeap::isEmpty(), graphEdge::isUnlinked(), and clusterHeap::popHead().
{
 while (!ch->isEmpty() && ch->getFirst()->isUnlinked()) ch->popHead();
 return ch->getFirst();
}
double clusterGraph::getLowestCost () [inline]
Definition at line 93 of file clusterGraph.h.
References clusterEdge::cost, and getFirstEdge().
{clusterEdge *e = getFirstEdge(); return (e!=NULL)?(e->cost):(DBL_MAX);}
Member Data Documentation
clusterEdge** clusterGraph::ces [private]
Definition at line 74 of file clusterGraph.h.
clusterHeap* clusterGraph::ch [private]
Definition at line 75 of file clusterGraph.h.
double(* clusterGraph::costFunction)(const void *, const void *) [private]
Definition at line 76 of file clusterGraph.h.
int clusterGraph::curEdgeIndex [private]
Definition at line 73 of file clusterGraph.h.
int clusterGraph::maxNumEdges [private]
Definition at line 73 of file clusterGraph.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/clusterGraph.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/clusterGraph.cpp