OpenCog Framework: Graph Class Reference
Graph Class Reference
Base class type for non oriented graphs.
#include <graph.h>
Public Member Functions
~Graph ()
graphNode * addNode (graphNode *n)
Adds an existing isolated node to the graph. O(1).
graphEdge * createEdge (graphNode *n1, graphNode *n2)
Creates a new edge out of a pair of nodes. O(degree of nodes).
void deleteUnlinkedElements ()
Public Attributes
List nodes
Nodes and edges of the graph.
List edges
Detailed Description
Base class type for non oriented graphs.
Definition at line 95 of file graph.h.
Constructor & Destructor Documentation
Graph::~Graph ()
Definition at line 106 of file graph.cpp.
References edges, nodes, and List::popHead().
{
 graphNode *gn;
 graphEdge *ge;
 while ((gn=(graphNode *)nodes.popHead())!=NULL) delete gn;
 while ((ge=(graphEdge *)edges.popHead())!=NULL) delete ge;
}
Member Function Documentation
graphNode* Graph::addNode (graphNode * n) [inline]
Adds an existing isolated node to the graph. O(1).
Definition at line 105 of file graph.h.
References List::appendHead(), and nodes.
{nodes.appendHead(n); return n;}
graphEdge * Graph::createEdge (graphNode * n1, graphNode * n2)
Creates a new edge out of a pair of nodes. O(degree of nodes).
If the edges already exists, no new edge is created and the existing one is returned. Otherwise the newly created edge is returned.
Reimplemented in clusterGraph.
Definition at line 46 of file graph.cpp.
References List::appendHead(), Node::data, edges, graphNode::edges, FOREACHNODE, and List::head().
{
 Node *n;
 FOREACHNODE(n1->edges, n)
  if (((graphEdge *)n->data)->hasNode(n2))
   return (graphEdge *)n->data;
 edges.appendHead(new graphEdge(n1, n2));
 return (graphEdge *)edges.head()->data;
}
void Graph::deleteUnlinkedElements ()
Eliminates isolated nodes and unlinked edges from the lists. O(N). The eliminated elements are deleted too.
Definition at line 114 of file graph.cpp.
References Node::data, edges, List::head(), graphNode::isIsolated(), graphEdge::isUnlinked(), Node::next(), nodes, Node::prev(), List::removeCell(), and List::tail().
{
 Node *n;
 graphNode *gn;
 graphEdge *ge;
 n = nodes.head();
 while (n != NULL)
 {
  gn = (graphNode *)n->data;
  n = n->next();
  if (gn->isIsolated())
  {
   nodes.removeCell((n!=NULL)?(n->prev()):nodes.tail());
   delete(gn);
  }
 }
 n = edges.head();
 while (n != NULL)
 {
  ge = (graphEdge *)n->data;
  n = n->next();
  if (ge->isUnlinked())
  {
   edges.removeCell((n!=NULL)?(n->prev()):edges.tail());
   delete(ge);
  }
 }
}
Member Data Documentation
List Graph::edges
Definition at line 100 of file graph.h.
List Graph::nodes
Nodes and edges of the graph.
Definition at line 100 of file graph.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/graph.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/graph.cpp