OpenCog Framework: dijkstraGraph Class Reference
dijkstraGraph Class Reference
#include <dijkstraGraph.h>
Public Member Functions
dijkstraGraph (int n)
~dijkstraGraph ()
dijkstraNode * addNode (dijkstraNode *n)
dijkstraEdge * createEdge (dijkstraNode *n1, dijkstraNode *n2, double c)
dijkstraNode * popFirstNode ()
dijkstraNode ** getNodes () const
int getNumNodes () const
void runDijkstra (dijkstraNode *s, bool use_distances=false)
double computeDistance (dijkstraNode *source, dijkstraNode *destination)
Private Attributes
int curNodeIndex
int maxNumNodes
dijkstraNode ** nds
dijkstraHeap * ch
Detailed Description
Definition at line 81 of file dijkstraGraph.h.
Constructor & Destructor Documentation
dijkstraGraph::dijkstraGraph (int n) [inline]
Definition at line 89 of file dijkstraGraph.h.
References ch, curNodeIndex, maxNumNodes, and nds.
 {
  nds = new dijkstraNode *[n];
  maxNumNodes = n;
  curNodeIndex = 0;
  ch = new dijkstraHeap(n, nds);
 }
dijkstraGraph::~dijkstraGraph () [inline]
Definition at line 96 of file dijkstraGraph.h.
References ch, and nds.
{delete nds; delete ch;}
Member Function Documentation
dijkstraNode * dijkstraGraph::addNode (dijkstraNode * n)
Definition at line 44 of file dijkstraGraph.cpp.
References List::appendHead(), curNodeIndex, dijkstraNode::index, maxNumNodes, nds, and Graph::nodes.
{
 nodes.appendHead(n);
 if (curNodeIndex >= maxNumNodes) return NULL;
 nds[curNodeIndex] = n;
 n->index = curNodeIndex;
 curNodeIndex++;
 return n;
}
double dijkstraGraph::computeDistance (dijkstraNode * source, dijkstraNode * destination)
Definition at line 99 of file dijkstraGraph.cpp.
References ch, dijkstraEdge::cost, Node::data, dijkstraNode::dist, graphNode::edges, FOREACHNODE, graphNode::mask, Graph::nodes, graphEdge::oppositeNode(), dijkstraHeap::popHead(), dijkstraHeap::push(), and dijkstraHeap::update().
{
 Node *n;
 dijkstraEdge *de;
 dijkstraNode *dn, *dd;
 double d;
 FOREACHNODE(nodes, n) {dn=((dijkstraNode *)n->data); dn->mask=0; dn->dist = DBL_MAX;}
 n0->dist = 0.0;
 ch->push(n0);
 while ((dn=ch->popHead())!=NULL)
 {
  if (dn == n1) {while (ch->popHead()!=NULL); return n1->dist;}
  dn->mask=1;
  FOREACHNODE(dn->edges, n)
  {
   de = ((dijkstraEdge *)n->data);
   dd = (dijkstraNode *)de->oppositeNode(dn);
   if (dd->mask == 0)
   {
    d = dn->dist + de->cost;
    if (d < dd->dist)
    {
     dd->dist = d;
     ch->update(dd);
    }
   }
  }
 }
 return DBL_MAX;
}
dijkstraEdge * dijkstraGraph::createEdge (dijkstraNode * n1, dijkstraNode * n2, double c)
Definition at line 54 of file dijkstraGraph.cpp.
References List::appendHead(), Node::data, Graph::edges, graphNode::edges, and FOREACHNODE.
{
 Node *n;
 FOREACHNODE(n1->edges, n)
  if (((dijkstraEdge *)n->data)->hasNode(n2))
   return (dijkstraEdge *)n->data;
 dijkstraEdge *ne = new dijkstraEdge(n1, n2, cost);
 edges.appendHead(ne);
 return ne;
}
dijkstraNode** dijkstraGraph::getNodes () const [inline]
Definition at line 102 of file dijkstraGraph.h.
References nds.
{return nds;}
int dijkstraGraph::getNumNodes () const [inline]
Definition at line 103 of file dijkstraGraph.h.
References curNodeIndex.
{return curNodeIndex;}
dijkstraNode* dijkstraGraph::popFirstNode () [inline]
Definition at line 101 of file dijkstraGraph.h.
References ch, and dijkstraHeap::popHead().
{return ch->popHead();}
void dijkstraGraph::runDijkstra (dijkstraNode * s, bool use_distances = false)
Definition at line 67 of file dijkstraGraph.cpp.
References ch, dijkstraEdge::cost, Node::data, dijkstraNode::dist, graphNode::edges, FOREACHNODE, graphNode::mask, Graph::nodes, graphEdge::oppositeNode(), dijkstraHeap::popHead(), dijkstraHeap::push(), and dijkstraHeap::update().
{
 Node *n;
 dijkstraEdge *de;
 dijkstraNode *dn, *dd;
 double d;
 FOREACHNODE(nodes, n) {dn=((dijkstraNode *)n->data); dn->mask=0; if (!use_distances) dn->dist = DBL_MAX;}
 n0->dist = 0.0;
 ch->push(n0);
 while ((dn=ch->popHead())!=NULL)
 {
  dn->mask=1;
  FOREACHNODE(dn->edges, n)
  {
   de = ((dijkstraEdge *)n->data);
   dd = (dijkstraNode *)de->oppositeNode(dn);
   if (dd->mask == 0)
   {
    d = dn->dist + de->cost;
    if (d < dd->dist)
    {
     dd->dist = d;
     ch->update(dd);
    }
   }
  }
 }
}
Member Data Documentation
dijkstraHeap* dijkstraGraph::ch [private]
Definition at line 85 of file dijkstraGraph.h.
int dijkstraGraph::curNodeIndex [private]
Definition at line 83 of file dijkstraGraph.h.
int dijkstraGraph::maxNumNodes [private]
Definition at line 83 of file dijkstraGraph.h.
dijkstraNode** dijkstraGraph::nds [private]
Definition at line 84 of file dijkstraGraph.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/dijkstraGraph.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/dijkstraGraph.cpp