OpenCog Framework: abstractHeap Class Reference
abstractHeap Class Reference
Heap base class type.
#include <heap.h>
Public Member Functions
abstractHeap (int n)
Creates a heap which can contain up to 'n' elements.
virtual ~abstractHeap ()=0
Default destructor.
int insert (void *e)
Inserts 'e' into the heap.
int isEmpty () const
Returns TRUE if the heap is empty.
void * getHead () const
Returns the first element of the heap.
void * removeHead ()
Removes and returns the first element after rearranging the heap.
void flush ()
Removes all the elements.
Protected Member Functions
int upheap (int i)
Moves the i'th object up on the heap.
int downheap (int i)
Moves the i'th object down on the heap.
virtual int compare (const void *a, const void *b)=0
Comparison of two heap elements.
Protected Attributes
void ** heap
Heap data is stored here.
int numels
Current number of elements.
int maxels
Maximum number of elements.
int * positions
Optional pointer to an array of positions.
Detailed Description
Heap base class type.
abstractHeap is the base class for implementing heaps. Each implementation (class extension) must define the method compare to be used for sorting the heap. If the objects being sorted are non-negative numbers, a special implementation may use the field positions to record the index of each element within the heap. This feature is useful when there is a need to re-sort an element whose cost changes after its insertion into the heap. The array 'positions' must be allocated by the extended class constructor, and must be able to contain NMAX+1 integer numbers, where NMAX is the maximum value that can be assumed by an object.
Definition at line 48 of file heap.h.
Constructor & Destructor Documentation
abstractHeap::abstractHeap (int n)
Creates a heap which can contain up to 'n' elements.
Definition at line 32 of file heap.cpp.
References heap, maxels, numels, and positions.
{
 heap = new void *[size+1];
 numels = 0;
 maxels = size;
 positions = NULL;
}
abstractHeap::~abstractHeap () [pure virtual]
Default destructor.
Definition at line 40 of file heap.cpp.
References heap.
{
 delete(heap);
}
Member Function Documentation
virtual int abstractHeap::compare (const void * a, const void * b) [protected, pure virtual]
Comparison of two heap elements.
This function must be implemented in the extended class. The return value must be <0 if a<b, >0 if a>b or 0 if a=b.
Implemented in clusterHeap, and dijkstraHeap.
int abstractHeap::downheap (int i) [protected]
Moves the i'th object down on the heap.
Definition at line 67 of file heap.cpp.
References compare(), heap, numels, and positions.
{
 int j;
 void *t = heap[k];
 int fk = (numels%2)?((numels-1)/2):(numels/2);
 if (k > fk) return k;
 j = k+k;
 if (j < numels && compare(heap[j], heap[j+1]) >= 0) j++;
 void *f = heap[j];
 if (compare(t, f) >= 0)
 {
  heap[k] = f;
  heap[j] = t;
  if (positions != NULL)
  {
   positions[(j_voidint)f] = k;
   positions[(j_voidint)t] = j;
  }
  return downheap(j);
 }
 return k;
}
void abstractHeap::flush () [inline]
Removes all the elements.
Definition at line 83 of file heap.h.
References numels.
void* abstractHeap::getHead () const [inline]
Returns the first element of the heap.
Definition at line 81 of file heap.h.
References heap.
int abstractHeap::insert (void * e)
Inserts 'e' into the heap.
Inserts an element 'e' into the heap in the correct position, according to the method compare. If the insertion fails because the heap is full, -1 is returned, otherwise the index position of the newly inserted element is returned.
Definition at line 93 of file heap.cpp.
References heap, maxels, numels, positions, and upheap().
{
 if (numels == maxels) return -1;
 heap[++numels] = t;
 if (positions != NULL) positions[(j_voidint)t] = numels;
 return upheap(numels);
}
int abstractHeap::isEmpty () const [inline]
Returns TRUE if the heap is empty.
Definition at line 80 of file heap.h.
References numels.
void * abstractHeap::removeHead ()
Removes and returns the first element after rearranging the heap.
Definition at line 102 of file heap.cpp.
References downheap(), heap, numels, and positions.
{
 void *t = heap[1];
 if (positions != NULL) positions[(j_voidint)t] = 0;
 heap[1] = heap[numels--];
 if (numels)
 {
  if (positions != NULL) positions[(j_voidint)heap[1]] = 1;
  downheap(1);
 }
 return t;
}
int abstractHeap::upheap (int i) [protected]
Moves the i'th object up on the heap.
Definition at line 45 of file heap.cpp.
References compare(), heap, and positions.
{
 if (k < 2) return k;
 void *t = heap[k];
 int fk = (k%2)?((k-1)/2):(k/2);
 void *f = heap[fk];
 if (compare(t, f) <= 0)
 {
  heap[k] = f;
  heap[fk] = t;
  if (positions != NULL)
  {
   positions[(j_voidint)f] = k;
   positions[(j_voidint)t] = fk;
  }
  return upheap(fk);
 }
 return k;
}
Member Data Documentation
void** abstractHeap::heap [protected]
Heap data is stored here.
Definition at line 51 of file heap.h.
int abstractHeap::maxels [protected]
Maximum number of elements.
Definition at line 53 of file heap.h.
int abstractHeap::numels [protected]
Current number of elements.
Definition at line 52 of file heap.h.
int* abstractHeap::positions [protected]
Optional pointer to an array of positions.
Definition at line 54 of file heap.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/heap.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/heap.cpp