OpenCog Framework: Triangle Class Reference
Triangle Class Reference
Triangle of a Triangulation.
#include <triangle.h>
Public Member Functions
Triangle (Edge *, Edge *, Edge *)
Constructor.
bool isLinked () const
TRUE if properly linked.
void invert ()
Inverts the orientation of the triangle.
Vertex * v1 () const
First vertex.
Vertex * v2 () const
Second vertex.
Vertex * v3 () const
Third vertex.
Triangle * t1 () const
First adjacent triangle. NULL if boundary.
Triangle * t2 () const
Second adjacent triangle. NULL if boundary.
Triangle * t3 () const
Third adjacent triangle. NULL if boundary.
bool hasEdge (const Edge *e) const
TRUE iff 'e' is an edge of the triangle.
bool hasVertex (const Vertex *v) const
TRUE iff 'v' is a vertex of the triangle.
Edge * oppositeEdge (const Vertex *v) const
Triangle's edge opposite to 'v'. NULL if 'v' is not a vertex of the triangle.
Triangle * oppositeTriangle (const Vertex *v) const
Adjacent triangle opposite to 'v'. NULL if 'v' is not a vertex of the triangle.
Vertex * oppositeVertex (const Edge *e) const
Triangle's vertex opposite to 'e'. NULL if 'e' is not an edge of the triangle.
Triangle * rightTriangle (const Edge *e) const
Triangle adjacent to the next edge of 'e'. NULL if 'e' is not an edge of the triangle.
Triangle * leftTriangle (const Edge *e) const
Triangle adjacent to the previous edge of 'e'. NULL if 'e' is not an edge of the triangle.
Edge * nextEdge (const Edge *e) const
Edge next to 'e' in the ordering or the triangle. NULL if 'e' is not an edge of the triangle.
Edge * prevEdge (const Edge *e) const
Edge preceeding 'e' in the ordering or the triangle. NULL if 'e' is not an edge of the triangle.
Vertex * nextVertex (const Vertex *v) const
Vertex next to 'v' in the ordering or the triangle. NULL if 'v' is not a vertex of the triangle.
Vertex * prevVertex (const Vertex *v) const
Vertex preceeding 'v' in the ordering or the triangle. NULL if 'v' is not a vertex of the triangle.
Edge * commonEdge (const Triangle *b) const
If this triangle shares an edge with 'b', then such an edge is returned. NULL otherwise.
bool replaceEdge (const Edge *a, Edge *b)
Replace edge 'a' with edge 'b' in the triangle and return TRUE. If 'a' is not an edge of the triangle return FALSE.
Point getNormal () const
Return a normal vector with direction (v1-v2) cross (v2-v3). If triangle is degenerate return a null vector.
Point getVector () const
Return a vector orthogonal to the plane of the triangle. If triangle is degenerate return a null vector.
bool checkAdjNor (const Triangle *t) const
TRUE if the oriantation is consistent with the one of 't' OR if this and 't' do not share any edge.
double area () const
Area of the triangle (Heron's formula).
double perimeter () const
Perimeter of the triangle.
Point getCenter () const
Return the triangle's barycenter.
Point getCircleCenter () const
Return the center of the triangle's bounding sphere.
bool inSphere (const Point *p) const
TRUE iff 'p' is inside the triangle's bounding sphere.
double getAngle (const Vertex *v) const
Angle at vertex 'v'. Return -1 if 'v' is not a vertex of the triangle.
double getDAngle (const Triangle *t) const
Angle between the normal vector of this and the one of 't'. Return -1 if one or both the triangles are degenerate.
double distanceFromPoint (const Point *p) const
Distance of 'p' from the plane of the triangle. Return -1 if triangle is degenerate.
double squaredDistanceFromPoint (const Point *p) const
Squared distance of 'p' from the plane of the triangle. Return -1 if triangle is degenerate.
double pointTriangleDistance (const Point *p, Point *c=NULL) const
double pointTriangleSquaredDistance (const Point *p) const
Squared distance of 'p' from the closest point of the triangle. Return -1 if triangle is degenerate.
Point project (const Point *p) const
Projection of 'p' on the plane of the triangle. Return INFINITE_POINT if triangle is degenerate.
bool isInside (const Point *p) const
TRUE iff the projection of 'p' on the plane of the triangle is inside the triangle.
bool intersectsEdge (const Edge *e, Point *p, const double=0.0) const
Triangle-edge intersection.
Edge * isCap () const
Cap-like degeneracy check.
Edge * isNeedle () const
Needle-like degeneracy check.
bool isDegenerate () const
Degeneracy check. Return TRUE iff isCap() or isNeedle().
bool overlaps () const
Return TRUE iff one of the adjacent triangles overlaps with this one.
void printTriangle (FILE *f=stdout) const
Print the coordinates of the three vertices to the file handler pointed to by 'f' (stdout by default).
Public Attributes
Edge * e1
Edge * e2
Edge * e3
Edges of the triangle.
void * info
Further information.
unsigned char mask
bit-mask for marking purposes
Detailed Description
Triangle of a Triangulation.
This class represents a triangle of a triangulation. Each Triangle has an orientation (clockwise or counter-clockwise) due to the order in which its edges are stored in the class. When looking at the triangle so that (e1, e2, e3) are sorted counter-clockwise, the normal at the triangle points towards the observer. The field mask is useful for assigning up to 256 different states to the edge.
Definition at line 43 of file triangle.h.
Constructor & Destructor Documentation
Triangle::Triangle (Edge * a, Edge * b, Edge * c)
Constructor.
Definition at line 33 of file triangle.cpp.
References e1, e2, e3, info, and mask.
{
 e1 = a;
 e2 = b;
 e3 = c;
 mask = 0;
 info = NULL;
}
Member Function Documentation
double Triangle::area () const
Area of the triangle (Heron's formula).
Definition at line 90 of file triangle.cpp.
References e1, e2, e3, and Edge::length().
{
 double a = e1->length(), b = e2->length(), c = e3->length();
 if (a==0.0 || b==0.0 || c==0.0) return 0.0;
 double p = (a+b+c)/2.0;
 p = p*(p-a)*(p-b)*(p-c); if (p<0) return 0.0;
 return sqrt(p);
}
bool Triangle::checkAdjNor (const Triangle * t) const
TRUE if the oriantation is consistent with the one of 't' OR if this and 't' do not share any edge.
Definition at line 75 of file triangle.cpp.
References commonEdge(), Edge::commonVertex(), and nextEdge().
{
 Edge *e = commonEdge(t);
 if (e == NULL) return 1;
 Edge *ea = nextEdge(e);
 Edge *eb = t->nextEdge(e);
 if (ea->commonVertex(eb) == ea->commonVertex(e)) return 0;
 return 1;
}
Edge* Triangle::commonEdge (const Triangle * b) const [inline]
If this triangle shares an edge with 'b', then such an edge is returned. NULL otherwise.
Definition at line 112 of file triangle.h.
References e1, e2, and e3.
    {return ((e1 == b->e1 || e1 == b->e2 || e1 == b->e3)?(e1):\
        (((e2 == b->e1 || e2 == b->e2 || e2 == b->e3)?(e2):\
        (((e3 == b->e1 || e3 == b->e2 || e3 == b->e3)?(e3):(NULL))))));}
double Triangle::distanceFromPoint (const Point * p) const
Distance of 'p' from the plane of the triangle. Return -1 if triangle is degenerate.
Definition at line 171 of file triangle.cpp.
References e1, FABS, getNormal(), Point::isNull(), and Edge::v1.
{
 Point n = getNormal();
 if (n.isNull()) return -1.0;
 double d = (n*(*p))-(n*(*(e1->v1)));
 return FABS(d);
}
double Triangle::getAngle (const Vertex * v) const
Angle at vertex 'v'. Return -1 if 'v' is not a vertex of the triangle.
Definition at line 145 of file triangle.cpp.
References Point::getAngle(), v1(), v2(), and v3().
{
 Vertex *va = v1(), *vb = v2(), *vc = v3();
 if (v == va) return v->getAngle(vb, vc);
 if (v == vb) return v->getAngle(va, vc);
 if (v == vc) return v->getAngle(vb, va);
 return -1.0;
}
Point Triangle::getCenter () const
Return the triangle's barycenter.
Definition at line 110 of file triangle.cpp.
References v1(), v2(), and v3().
{
 Point va = *v1(), vb = *v2(), vc = *v3();
 return (va+vb+vc)/3.0;
}
Point Triangle::getCircleCenter () const
Return the center of the triangle's bounding sphere.
Definition at line 119 of file triangle.cpp.
References e1, e2, Edge::getMidPoint(), Point::linearSystem(), v1(), v2(), and v3().
{
 Point va = *v1(), vb = *v2(), vc = *v3();
 Point q1 = vb-va;
 Point q2 = vc-va;
 Point n = q2&q1;
 Point m1 = e2->getMidPoint();
 Point m2 = e1->getMidPoint();
 return Point(n*va,q1*m1,q2*m2).linearSystem(n,q1,q2);
}
double Triangle::getDAngle (const Triangle * t) const
Angle between the normal vector of this and the one of 't'. Return -1 if one or both the triangles are degenerate.
Definition at line 158 of file triangle.cpp.
References Point::getAngle(), getVector(), and Point::isNull().
{
 Point thisNormal = getVector();
 Point otherNormal = t->getVector();
 if (thisNormal.isNull() || otherNormal.isNull()) return -1.0;
 return thisNormal.getAngle(otherNormal);
}
Point Triangle::getNormal () const
Return a normal vector with direction (v1-v2) cross (v2-v3). If triangle is degenerate return a null vector.
Definition at line 45 of file triangle.cpp.
References Point::length(), v1(), v2(), and v3().
{
 Vertex *va = v1(), *vb = v2(), *vc = v3();
 Point vd = (((*va)-(*vb))&((*vb)-(*vc)));
 double l = vd.length();
 if (l == 0) return Point(0,0,0);
 return vd/l;
}
Point Triangle::getVector () const
Return a vector orthogonal to the plane of the triangle. If triangle is degenerate return a null vector.
Definition at line 59 of file triangle.cpp.
References Point::isNull(), v1(), v2(), and v3().
{
 Vertex *va = v1(), *vb = v2(), *vc = v3();
 Point vd1 = (((*va)-(*vb))&((*vb)-(*vc)));
 Point vd2 = (((*vb)-(*vc))&((*vc)-(*va)));
 Point vd3 = (((*vc)-(*va))&((*va)-(*vb)));
 Point vd = vd1+vd2+vd3;
 if (vd.isNull()) return Point(0,0,0);
 return vd;
}
bool Triangle::hasEdge (const Edge * e) const [inline]
TRUE iff 'e' is an edge of the triangle.
Definition at line 72 of file triangle.h.
References e1, e2, and e3.
{return (e==e1 || e==e2 || e==e3);}
bool Triangle::hasVertex (const Vertex * v) const [inline]
TRUE iff 'v' is a vertex of the triangle.
Definition at line 75 of file triangle.h.
References e1, e2, e3, and Edge::hasVertex().
{return (e1->hasVertex(v) || e2->hasVertex(v) || e3->hasVertex(v));}
bool Triangle::inSphere (const Point * p) const
TRUE iff 'p' is inside the triangle's bounding sphere.
Definition at line 134 of file triangle.cpp.
References Point::distance(), e1, getCircleCenter(), and Edge::v1.
{
 Point c = getCircleCenter();
 double rad = c.distance(e1->v1);
 return (p->distance(c) < rad);
}
bool Triangle::intersectsEdge (const Edge * e, Point * out, const double t = 0.0) const
Triangle-edge intersection.
Checks whether the triangle intersects the edge 'e'. If it does, the method returns TRUE and 'p' is initialized with the point of intersection. If there is no intersection or if the edge lies on the plane of the triangle, FALSE is returned. 't' is a threshold distance within which a point is considered to be on the face.
Checks wether the triangle intersects the edge 'e'. If it does, /// the method returns 1 and 'out' is initialized with the point of /// intersection. If there is no intersection or if the edge lies /// on the plane of the triangle, 0 is returned. 't' is a threshold /// distance within which a point is considered to be on the face. ///
Definition at line 306 of file triangle.cpp.
References FABS, getNormal(), Point::normalize(), Point::setValue(), Edge::v1, v1(), Edge::v2, v2(), and v3().
{
 Point p, p1, p2, p3, nor=getNormal();
 p1.setValue(v1()); p2.setValue(v2()); p3.setValue(v3());
 double dv1 = ((*(e->v1))-p1)*nor;
 double dv2 = ((*(e->v2))-p1)*nor;
 double dv3;
 if (FABS(dv1) < t) dv1 = 0;
 if (FABS(dv2) < t) dv2 = 0;
 if (dv1*dv2 > 0) return 0;
 if (dv1 == 0 && dv2 == 0) return 0;
 dv1 = FABS(dv1); dv2 = FABS(dv2);
 if (dv1 == 0) p.setValue(e->v1);
 else if (dv2 == 0) p.setValue(e->v2);
 else p = (((*(e->v2))*dv1)+((*(e->v1))*dv2))/(dv1+dv2);
 Point r1 = (p2-p1)&nor; r1.normalize(); dv1 = (p-p1)*r1;
 Point r2 = (p3-p2)&nor; r2.normalize(); dv2 = (p-p2)*r2;
 Point r3 = (p1-p3)&nor; r3.normalize(); dv3 = (p-p3)*r3;
 if (FABS(dv1) < t) dv1 = 0;
 if (FABS(dv2) < t) dv2 = 0;
 if (FABS(dv3) < t) dv3 = 0;
 if (dv1 > 0 || dv2 > 0 || dv3 > 0) return 0;
 out->setValue(p);
 return 1;
}
void Triangle::invert () [inline]
Inverts the orientation of the triangle.
Definition at line 56 of file triangle.h.
References e2, e3, and p_swap().
{p_swap((void **)(&e2), (void **)(&e3));}
Edge * Triangle::isCap () const
Cap-like degeneracy check.
If the angle at a vertex is flat, return the edge opposite to such vertex. Return NULL otherwise.
Definition at line 341 of file triangle.cpp.
References e1, e2, e3, getAngle(), Edge::length(), M_PI, v1(), v2(), and v3().
{
 if (e1->length()==0 || e2->length()==0 || e3->length()==0) return NULL;
 if (getAngle(v1()) == M_PI) return e3;
 if (getAngle(v2()) == M_PI) return e1;
 if (getAngle(v3()) == M_PI) return e2;
 return 0;
}
bool Triangle::isDegenerate () const
Degeneracy check. Return TRUE iff isCap() or isNeedle().
Definition at line 373 of file triangle.cpp.
References isCap(), and isNeedle().
{
 return (isCap() != NULL || isNeedle() != NULL);
}
bool Triangle::isInside (const Point * p) const
TRUE iff the projection of 'p' on the plane of the triangle is inside the triangle.
Definition at line 277 of file triangle.cpp.
References Point::getAngle(), getNormal(), Point::isNull(), PI2, v1(), v2(), and v3().
{
 Vertex va = *v1(), vb = *v2(), vc = *v3();
 Point v = *p;
 if (v == va || v == vb || v == vc) return 1;
 Point n = getNormal();
 if (n.isNull()) return 0;
 Point pa1 = ((vb-va)&(v-va));
 if (pa1.isNull()) return (((va-v)*(vb-v)) <= 0);
 Point pa2 = ((vc-vb)&(v-vb));
 if (pa2.isNull()) return (((vb-v)*(vc-v)) <= 0);
 Point pa3 = ((va-vc)&(v-vc));
 if (pa3.isNull()) return (((vc-v)*(va-v)) <= 0);
 double a1 = n.getAngle(pa1);
 double a2 = n.getAngle(pa2);
 double a3 = n.getAngle(pa3);
 return ((a1 >= PI2 && a2 >= PI2 && a3 >= PI2) || (a1 <= PI2 && a2 <= PI2 && a3 <= PI2));
}
bool Triangle::isLinked () const [inline]
TRUE if properly linked.
Definition at line 53 of file triangle.h.
References e1.
Edge * Triangle::isNeedle () const
Needle-like degeneracy check.
If an edge of the triangle has zero length, return that edge. If the angle at a vertex is zero, return the edge opposite to such vertex. Return NULL otherwise.
Definition at line 353 of file triangle.cpp.
References e1, e2, e3, getAngle(), Edge::length(), M_PI, v1(), v2(), and v3().
{
 if (e1->length() == 0) return e1;
 if (e2->length() == 0) return e2;
 if (e3->length() == 0) return e3;
 double a1 = getAngle(v1());
 double a2 = getAngle(v2());
 double a3 = getAngle(v3());
 if (a1 == M_PI || a2 == M_PI || a3 == M_PI) return 0;
 if (a1 == 0) return e3;
 if (a2 == 0) return e1;
 if (a3 == 0) return e2;
 return 0;
}
Triangle* Triangle::leftTriangle (const Edge * e) const [inline]
Triangle adjacent to the previous edge of 'e'. NULL if 'e' is not an edge of the triangle.
Definition at line 94 of file triangle.h.
References e1, e2, e3, t1(), t2(), and t3().
  {return (e==e1)?(t3()):((e==e2)?(t1()):((e==e3)?(t2()):(NULL)));}
Edge* Triangle::nextEdge (const Edge * e) const [inline]
Edge next to 'e' in the ordering or the triangle. NULL if 'e' is not an edge of the triangle.
Definition at line 98 of file triangle.h.
References e1, e2, and e3.
{return ((e==e1)?(e2):((e==e2)?(e3):((e==e3)?(e1):(NULL))));}
Vertex* Triangle::nextVertex (const Vertex * v) const [inline]
Vertex next to 'v' in the ordering or the triangle. NULL if 'v' is not a vertex of the triangle.
Definition at line 104 of file triangle.h.
References e1, e2, e3, Edge::hasVertex(), v1(), v2(), and v3().
  {return (!e1->hasVertex(v))?(v3()):((!e2->hasVertex(v))?(v1()):((!e3->hasVertex(v))?(v2()):(NULL)));}
Edge* Triangle::oppositeEdge (const Vertex * v) const [inline]
Triangle's edge opposite to 'v'. NULL if 'v' is not a vertex of the triangle.
Definition at line 78 of file triangle.h.
References e1, e2, e3, and Edge::hasVertex().
  {return ((!e1->hasVertex(v))?(e1):((!e2->hasVertex(v))?(e2):((!e3->hasVertex(v))?(e3):(NULL))));}
Triangle* Triangle::oppositeTriangle (const Vertex * v) const [inline]
Adjacent triangle opposite to 'v'. NULL if 'v' is not a vertex of the triangle.
Definition at line 82 of file triangle.h.
References e1, e2, e3, Edge::hasVertex(), t1(), t2(), and t3().
  {return ((!e1->hasVertex(v))?(t1()):((!e2->hasVertex(v))?(t2()):((!e3->hasVertex(v))?(t3()):(NULL))));}
Vertex* Triangle::oppositeVertex (const Edge * e) const [inline]
Triangle's vertex opposite to 'e'. NULL if 'e' is not an edge of the triangle.
Definition at line 86 of file triangle.h.
References e1, e2, e3, v1(), v2(), and v3().
  {return (e==e1)?(v2()):((e==e2)?(v3()):((e==e3)?(v1()):(NULL)));}
bool Triangle::overlaps () const
Return TRUE iff one of the adjacent triangles overlaps with this one.
Definition at line 381 of file triangle.cpp.
References getDAngle(), M_PI, t1(), t2(), and t3().
{
 Triangle *tt1 = t1();
 Triangle *tt2 = t2();
 Triangle *tt3 = t3();
 if (tt1 && getDAngle(tt1) == M_PI) return 1;
 if (tt2 && getDAngle(tt2) == M_PI) return 1;
 if (tt3 && getDAngle(tt3) == M_PI) return 1;
 return 0;
}
double Triangle::perimeter () const
Perimeter of the triangle.
Definition at line 102 of file triangle.cpp.
References e1, e2, e3, and Edge::length().
{
 return e1->length()+e2->length()+e3->length();
}
double Triangle::pointTriangleDistance (const Point * p, Point * c = NULL) const
Distance of 'p' from the closest point of the triangle. Return -1 if triangle is degenerate. If 'c' is not NULL, its coordinates are set to the ones of the closest point.
Definition at line 197 of file triangle.cpp.
References Point::distance(), e1, e2, getNormal(), Point::isNull(), Point::linearSystem(), Point::projection(), Point::setValue(), Point::squaredLength(), Edge::toUnitVector(), v1(), v2(), and v3().
{
 Point n = getNormal();
 if (n.isNull()) return -1.0;
 Vertex *va = v1(), *vb = v2(), *vc = v3();
 Point p1 = e1->toUnitVector();
 Point p2 = e2->toUnitVector();
 double d1 = (p1*(*p));
 double d2 = (p2*(*p));
 double d3 = (n*(*va));
 Point i = Point(d1,d2,d3).linearSystem(p1,p2,n);
 d1 = ((((*va)-(*vb))&((*vb)-i))*n);
 d2 = ((((*vb)-(*vc))&((*vc)-i))*n);
 d3 = ((((*vc)-(*va))&((*va)-i))*n);
 if (d1 >= 0 && d2 >= 0 && d3 >= 0) {if (cp) cp->setValue(i); return i.distance(p);}
 if (d2 < 0) {va=vb; vb=vc;}
 else if (d3 < 0) {vb=va; va=vc;}
 i = p->projection(va,vb); p1 = i-(*va); p2 = i-(*vb);
 if (p1*p2 <=0) {if (cp) cp->setValue(i); return i.distance(p);}
 d1=p1.squaredLength(); d2=p2.squaredLength();
 if (d1<d2) {if (cp) cp->setValue(va); return p->distance(va);}
 else {if (cp) cp->setValue(vb); return p->distance(vb);}
}
double Triangle::pointTriangleSquaredDistance (const Point * p) const
Squared distance of 'p' from the closest point of the triangle. Return -1 if triangle is degenerate.
Definition at line 231 of file triangle.cpp.
References Point::projection(), Point::squaredDistance(), squaredDistanceFromPoint(), Point::squaredLength(), v1(), v2(), v3(), Point::x, Point::y, and Point::z.
{
 Vertex *va = v1(), *vb = v2(), *vc = v3();
 Point n(((*va)-(*vb))&((*vb)-(*vc)));
 if (n.x == 0 && n.y == 0 && n.z == 0) return -1.0;
 double d1 = ((((*va)-(*vb))&((*vb)-(*p)))*n);
 double d2 = ((((*vb)-(*vc))&((*vc)-(*p)))*n);
 double d3 = ((((*vc)-(*va))&((*va)-(*p)))*n);
 if (d1 >= 0 && d2 >= 0 && d3 >= 0) return squaredDistanceFromPoint(p);
 if (d2 < 0) {va=vb; vb=vc;}
 else if (d3 < 0) {vb=va; va=vc;}
 Point i(p->projection(va,vb));
 Point p1(i-(*va)); Point p2(i-(*vb));
 if (p1*p2 <=0) return i.squaredDistance(p);
 d1=p1.squaredLength(); d2=p2.squaredLength();
 if (d1<d2) return p->squaredDistance(va);
 else return p->squaredDistance(vb);
}
Edge* Triangle::prevEdge (const Edge * e) const [inline]
Edge preceeding 'e' in the ordering or the triangle. NULL if 'e' is not an edge of the triangle.
Definition at line 101 of file triangle.h.
References e1, e2, and e3.
{return ((e==e1)?(e3):((e==e2)?(e1):((e==e3)?(e2):(NULL))));}
Vertex* Triangle::prevVertex (const Vertex * v) const [inline]
Vertex preceeding 'v' in the ordering or the triangle. NULL if 'v' is not a vertex of the triangle.
Definition at line 108 of file triangle.h.
References e1, e2, e3, Edge::hasVertex(), v1(), v2(), and v3().
  {return (!e1->hasVertex(v))?(v1()):((!e2->hasVertex(v))?(v2()):((!e3->hasVertex(v))?(v3()):(NULL)));}
void Triangle::printTriangle (FILE * f = stdout) const
Print the coordinates of the three vertices to the file handler pointed to by 'f' (stdout by default).
Debug.
Definition at line 398 of file triangle.cpp.
References Point::printPoint(), v1(), v2(), and v3().
{
 v1()->printPoint(fp);
 v2()->printPoint(fp);
 v3()->printPoint(fp);
}
Point Triangle::project (const Point * p) const
Projection of 'p' on the plane of the triangle. Return INFINITE_POINT if triangle is degenerate.
Definition at line 259 of file triangle.cpp.
References e1, e2, getNormal(), INFINITE_POINT, Point::isNull(), Point::linearSystem(), Edge::toUnitVector(), and v1().
{
 Point n = getNormal();
 if (n.isNull()) return INFINITE_POINT;
 Point v = *(v1());
 Point p1 = e1->toUnitVector();
 double d1 = (p1*(*p));
 Point p2 = e2->toUnitVector();
 double d2 = (p2*(*p));
 double d3 = (n*v);
 Point i = Point(d1,d2,d3).linearSystem(p1,p2,n);
 return i;
}
bool Triangle::replaceEdge (const Edge * a, Edge * b) [inline]
Replace edge 'a' with edge 'b' in the triangle and return TRUE. If 'a' is not an edge of the triangle return FALSE.
Definition at line 118 of file triangle.h.
References e1, e2, and e3.
  {if (e1==a) e1=b; else if (e2==a) e2=b; else if (e3==a) e3=b; else return 0; return 1;}
Triangle* Triangle::rightTriangle (const Edge * e) const [inline]
Triangle adjacent to the next edge of 'e'. NULL if 'e' is not an edge of the triangle.
Definition at line 90 of file triangle.h.
References e1, e2, e3, t1(), t2(), and t3().
  {return (e==e1)?(t2()):((e==e2)?(t3()):((e==e3)?(t1()):(NULL)));}
double Triangle::squaredDistanceFromPoint (const Point * p) const
Squared distance of 'p' from the plane of the triangle. Return -1 if triangle is degenerate.
Definition at line 183 of file triangle.cpp.
References e1, e2, Edge::toVector(), and Edge::v1.
{
 Point CA = e1->toVector()&e2->toVector();
 double CA2 = CA*CA;
 if (CA2 == 0) return -1.0;
 double d = ((CA*(*p))-(CA*(*(e1->v1))));
 return (d*d)/CA2;
}
Triangle* Triangle::t1 () const [inline]
First adjacent triangle. NULL if boundary.
Definition at line 63 of file triangle.h.
References e1, and Edge::oppositeTriangle().
{return e1->oppositeTriangle(this);}
Triangle* Triangle::t2 () const [inline]
Second adjacent triangle. NULL if boundary.
Definition at line 66 of file triangle.h.
References e2, and Edge::oppositeTriangle().
{return e2->oppositeTriangle(this);}
Triangle* Triangle::t3 () const [inline]
Third adjacent triangle. NULL if boundary.
Definition at line 69 of file triangle.h.
References e3, and Edge::oppositeTriangle().
{return e3->oppositeTriangle(this);}
Vertex* Triangle::v1 () const [inline]
First vertex.
Definition at line 58 of file triangle.h.
References Edge::commonVertex(), e1, and e2.
Vertex* Triangle::v2 () const [inline]
Second vertex.
Definition at line 59 of file triangle.h.
References Edge::commonVertex(), e2, and e3.
Vertex* Triangle::v3 () const [inline]
Third vertex.
Definition at line 60 of file triangle.h.
References Edge::commonVertex(), e1, and e3.
Member Data Documentation
Edge* Triangle::e1
Definition at line 47 of file triangle.h.
Edge * Triangle::e2
Definition at line 47 of file triangle.h.
Edge * Triangle::e3
Edges of the triangle.
Definition at line 47 of file triangle.h.
void* Triangle::info
Further information.
Definition at line 48 of file triangle.h.
unsigned char Triangle::mask
bit-mask for marking purposes
Definition at line 49 of file triangle.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/triangle.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/MESH_STRUCTURE/triangle.cpp