OpenCog Framework: List Class Reference
List Class Reference
Doubly linked list.
#include <list.h>
Public Member Functions
List ()
Creates an empty list.
List (const void *d)
Creates a list containing an element 'd' (singleton)
List (const void **d, int n)
Creates a list out of an array 'd' made of 'n' elements.
List (List &l)
Creates a duplicated list.
List (List *l)
Creates a duplicated list.
~List ()
Destructor.
Node * head () const
Gets the first node, NULL if empty.
O(1).
Node * tail () const
Gets the last node, NULL if empty.
O(1).
int numels () const
Gets the number of elements.
O(1).
void appendHead (const void *d)
Appends a new node storing 'd' to the head.
O(1).
void appendTail (const void *d)
Appends a new node storing 'd' to the tail.
O(1).
int removeNode (const void *d)
Deletes and removes the node containing 'd'. Returns its position, 0 if 'd' is not in the list.
O(numels()).
int removeNode (int i)
Deletes and i'th node (starting from 0). Returns 0 if the list has less than i+1 nodes.
O(numels()).
Node * getNode (int i) const
Returns the node at position 'i' (starting from 0). Returns NULL if the list has less than i+1 nodes.
O(numels()).
void removeCell (Node *n)
Deletes and removes the node 'n' from the list.
O(1).
void appendList (const List *l)
Appends a list 'l' to the head by duplicating nodes in 'l'.
O(l->numels()).
void joinTailList (List *l)
Appends a list 'l' to the tail by linking the first node of 'l' to the last one of this list. 'l' becomes empty.
O(1).
void * popHead ()
Deletes and removes the first node. Returns its data.
O(1).
void * popTail ()
Deletes and removes the last node. Returns its data.
O(1).
void freeCell (Node *n)
Deletes and removes the node 'n' from the list and frees data memory.
O(1).
void freeNode (void *d)
Deletes and removes the node storing 'd' and frees the memory occupied by 'd' itself.
O(numels()).
Node * containsNode (const void *d) const
Returns the node storing 'd'. NULL if not found.
O(numels()).
Node * replaceNode (const void *old_n, const void *new_n)
Replaces old_n with new_n. The Node containing new_n is returned.
O(numels()).
void freeNodes ()
Deletes and removes all the nodes and frees data memory.
O(numels()).
void removeNodes ()
Deletes and removes all the nodes.
O(numels()).
void ** toArray () const
Creates an array out of the list.
O(numels()).
int sort (int(*comp)(const void *, const void *))
Sorts the list using 'comp' as comparison function for two elements.
O(numels()^2).
Protected Attributes
Node * l_head
First node pointer.
Node * l_tail
Last node pointer.
int l_numels
Number of elements in the list.
Detailed Description
Doubly linked list.
Definition at line 65 of file list.h.
Constructor & Destructor Documentation
List::List () [inline]
Creates an empty list.
Definition at line 76 of file list.h.
References l_head, l_numels, and l_tail.
{l_head = l_tail = NULL; l_numels = 0;}
List::List (const void * d) [inline]
Creates a list containing an element 'd' (singleton)
Definition at line 79 of file list.h.
References l_head, l_numels, and l_tail.
{l_head = l_tail = new Node(d); l_numels = 1;}
List::List (const void ** d, int n)
Creates a list out of an array 'd' made of 'n' elements.
Definition at line 56 of file list.cpp.
References appendTail(), l_head, l_numels, and l_tail.
{
 l_head = l_tail = NULL; l_numels = 0;
 for (int i=0; i<n; i++) appendTail(d[i]);
}
List::List (List & l) [inline]
Creates a duplicated list.
Definition at line 85 of file list.h.
References appendList(), l_head, l_numels, and l_tail.
{l_head = l_tail = NULL; l_numels = 0; appendList(&l);}
List::List (List * l) [inline]
Creates a duplicated list.
Definition at line 88 of file list.h.
References appendList(), l_head, l_numels, and l_tail.
{l_head = l_tail = NULL; l_numels = 0; appendList(l);}
List::~List ()
Destructor.
Definition at line 64 of file list.cpp.
References l_head, and removeCell().
{
 while (l_head != NULL) removeCell(l_head);
}
Member Function Documentation
void List::appendHead (const void * d)
Appends a new node storing 'd' to the head.
O(1).
Definition at line 71 of file list.cpp.
References l_head, l_numels, and l_tail.
{
 Node *nn = new Node(NULL, d, l_head);
 l_head = nn;
 if (l_tail == NULL) l_tail = l_head;
 l_numels++;
}
void List::appendList (const List * l)
Appends a list 'l' to the head by duplicating nodes in 'l'.
O(l->numels()).
Definition at line 89 of file list.cpp.
References appendHead(), Node::data, l_tail, and Node::prev().
{
 Node *n = l->l_tail;
 while (n != NULL)
 {
  appendHead(n->data);
  n=n->prev();
 }
}
void List::appendTail (const void * d)
Appends a new node storing 'd' to the tail.
O(1).
Definition at line 79 of file list.cpp.
References l_head, l_numels, and l_tail.
{
 Node *nn = new Node(l_tail, d, NULL);
 l_tail = nn;
 if (l_head == NULL) l_head = l_tail;
 l_numels++;
}
Node * List::containsNode (const void * d) const
Returns the node storing 'd'. NULL if not found.
O(numels()).
Definition at line 206 of file list.cpp.
References Node::data, l_head, and Node::n_next.
{
 Node *tmp = l_head;
 while (tmp != NULL)
  if (tmp->data == d) return tmp;
  else tmp=tmp->n_next;
 return NULL;
}
void List::freeCell (Node * n)
Deletes and removes the node 'n' from the list and frees data memory.
O(1).
Warning. This method uses the free() function to to dispose the memory space used by the data stored in the node. This means that such data should have been allocated through malloc(), calloc() or realloc(), and not through the 'new' operator. On some systems, however, the 'delete' operator simply calls 'free()' right after the execution of the proper object destructor so, if the object does not need to free internally allocated memory, it is safe to dispose the memory trhough free() although the object was allocated by 'new'. This works on Linux Fedora Core 2 distributions.
Definition at line 192 of file list.cpp.
References Node::data, and removeCell().
{
 free(n->data);
 removeCell(n);
}
void List::freeNode (void * d)
Deletes and removes the node storing 'd' and frees the memory occupied by 'd' itself.
O(numels()).
Warning. Read the comment for the method 'freeCell()'
Definition at line 198 of file list.cpp.
References removeNode().
{
 free(d);
 removeNode(d);
}
void List::freeNodes ()
Deletes and removes all the nodes and frees data memory.
O(numels()).
Warning. Read the comment for the method 'freeCell()'
Definition at line 229 of file list.cpp.
References freeCell(), and l_head.
{
 while (l_head != NULL) freeCell(l_head);
}
Node * List::getNode (int i) const
Returns the node at position 'i' (starting from 0). Returns NULL if the list has less than i+1 nodes.
O(numels()).
Definition at line 170 of file list.cpp.
References l_head, and Node::n_next.
{
 Node *tmp = l_head;
 while (tmp!=NULL && i--) tmp=tmp->n_next;
 return tmp;
}
Node* List::head () const [inline]
Gets the first node, NULL if empty.
O(1).
Definition at line 93 of file list.h.
References l_head.
void List::joinTailList (List * l)
Appends a list 'l' to the tail by linking the first node of 'l' to the last one of this list. 'l' becomes empty.
O(1).
Definition at line 102 of file list.cpp.
References l_head, l_numels, l_tail, Node::n_next, and Node::n_prev.
{
 if (l->l_numels == 0) return;
 if (l_tail != NULL)
 {
  l_tail->n_next = l->l_head; l->l_head->n_prev = l_tail; l_tail = l->l_tail;
  l_numels += l->l_numels;
 }
 else
 {
  l_head = l->l_head; l_tail = l->l_tail; l_numels = l->l_numels;
 }
 l->l_head = l->l_tail = NULL; l->l_numels = 0;
}
int List::numels () const [inline]
Gets the number of elements.
O(1).
Definition at line 95 of file list.h.
References l_numels.
void * List::popHead ()
Deletes and removes the first node. Returns its data.
O(1).
Definition at line 119 of file list.cpp.
References Node::data, l_head, and removeCell().
{
 void *data = (l_head != NULL)?(l_head->data):(NULL);
 if (l_head != NULL) removeCell(l_head);
 return data;
}
void * List::popTail ()
Deletes and removes the last node. Returns its data.
O(1).
Definition at line 128 of file list.cpp.
References Node::data, l_tail, and removeCell().
{
 void *data = (l_tail != NULL)?(l_tail->data):(NULL);
 if (l_tail != NULL) removeCell(l_tail);
 return data;
}
void List::removeCell (Node * n)
Deletes and removes the node 'n' from the list.
O(1).
Definition at line 181 of file list.cpp.
References l_head, l_numels, l_tail, Node::n_next, and Node::n_prev.
{
 if (n==l_head) l_head = n->n_next;
 if (n==l_tail) l_tail = n->n_prev;
 delete(n);
 l_numels--;
}
int List::removeNode (const void * d)
Deletes and removes the node containing 'd'. Returns its position, 0 if 'd' is not in the list.
O(numels()).
Definition at line 137 of file list.cpp.
References Node::data, l_head, Node::n_next, and removeCell().
{
 Node *tmp = l_head;
 int i=1;
 while (tmp != NULL)
  if (tmp->data == d)
  {
   removeCell(tmp);
   return i;
  }
  else {tmp=tmp->n_next; i++;}
 return 0;
}
int List::removeNode (int i)
Deletes and i'th node (starting from 0). Returns 0 if the list has less than i+1 nodes.
O(numels()).
Definition at line 156 of file list.cpp.
References l_head, Node::n_next, and removeCell().
{
 Node *tmp = l_head;
 while (tmp!=NULL && i--) tmp=tmp->n_next;
 if (tmp==NULL) return 0;
 removeCell(tmp);
 return 1;
}
void List::removeNodes ()
Deletes and removes all the nodes.
O(numels()).
Definition at line 236 of file list.cpp.
References l_head, and removeCell().
{
 while (l_head != NULL) removeCell(l_head);
}
Node * List::replaceNode (const void * old_n, const void * new_n)
Replaces old_n with new_n. The Node containing new_n is returned.
O(numels()).
Definition at line 219 of file list.cpp.
References appendTail(), containsNode(), Node::data, and l_tail.
{
 Node *tmp = containsNode(od);
 if (tmp != NULL) {tmp->data = (void *)nd; return tmp;}
 appendTail(nd);
 return l_tail;
}
int List::sort (int(*)(const void *, const void *) comp)
Sorts the list using 'comp' as comparison function for two elements.
O(numels()^2).
This method uses the QuickSort algorithm for sorting, thus the complexity is N^2 in the worst case, but it is actually much faster in the average case. If, however, there is the need to have a guaranteed O(NlogN) complexity, it is possible to implement a heap based on the 'abstractHeap' class. See the documentation of the standard 'qsort' library function for details on the prototype of the comparison function 'comp'.
Definition at line 260 of file list.cpp.
References appendHead(), jqsort(), l_numels, removeNodes(), and toArray().
{
 void **array;
 int ne = l_numels-1;
 if (l_numels < 2) return 0;
 if ((array = toArray()) == NULL) return 1;
 jqsort(array, l_numels, comp);
 removeNodes();
 for (; ne >= 0; ne--) appendHead(array[ne]);
 free(array);
 return 0;
}
Node* List::tail () const [inline]
Gets the last node, NULL if empty.
O(1).
Definition at line 94 of file list.h.
References l_tail.
void ** List::toArray () const
Creates an array out of the list.
O(numels()).
Definition at line 244 of file list.cpp.
References Node::data, l_head, l_numels, and Node::n_next.
{
 Node *n = l_head;
 int i;
 void **array;
 if (l_numels == 0) return NULL;
 array = (void **)malloc(sizeof(void *)*l_numels);
 if (array == NULL) return NULL;
 for (i=0; i<l_numels; i++, n=n->n_next) array[i] = n->data;
 return array;
}
Member Data Documentation
Node* List::l_head [protected]
First node pointer.
Definition at line 69 of file list.h.
int List::l_numels [protected]
Number of elements in the list.
Definition at line 71 of file list.h.
Node* List::l_tail [protected]
Last node pointer.
Definition at line 70 of file list.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/list.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/list.cpp