OpenCog Framework: Point Class Reference
Point Class Reference
Geometric point definition.
#include <point.h>
Public Member Functions
Point ()
Creates a new point with coordinates (0,0,0).
Point (const Point *s)
Creates a new point with the same coordinates as 's'. The info field is not copied.
Point (const Point &s)
Creates a new point with the same coordinates as 's'. The info field is not copied.
Point (const coord &a, const coord &b, const coord &c)
Creates a new point with coordinates (a,b,c).
void setValue (const coord &a, const coord &b, const coord &c)
Set the coordinates to (a,b,c).
void setValue (const Point &p)
Set the coordinates as those of 'p'.
void setValue (const Point *p)
Set the coordinates as those of '*p'.
Point operator- (const Point &p) const
Returns the vector difference.
Point operator+ (const Point &p) const
Returns the vector sum.
void operator+= (const Point &p)
Sums another point.
void operator-= (const Point &p)
Subtracts another point.
Point operator& (const Point &p) const
Returns the Cross Product.
double operator* (const Point &p) const
Returns the Dot Product.
Point operator* (const double &d) const
Returns the product with a scalar.
void operator*= (const double &m)
Multiplies by a scalar.
void operator/= (const double &m)
Divides by a scalar.
Point operator/ (const double &d) const
Returns the vector divided by the scalar.
bool operator== (const Point &p) const
TRUE iff coordinates are equal.
bool operator!= (const Point &p) const
FALSE iff coordinates are equal.
Point inverse () const
Returns the inverse vector.
void invert ()
Inverts the vector.
bool isNull () const
TRUE if vector is (0,0,0)
double length () const
Distance from origin.
double squaredLength () const
Squared distance from origin.
void normalize ()
Divides the vector by its length. If isNull() the application exits with an error.
void rotate (const Point &axis, const double &ang)
Rotates the vector around 'axis' by 'ang' radians ccw.
void project (const Point *n)
Projects the vector on the plane with normal 'n' passing through the origin.
bool notAligned (const Point *a, const Point *b) const
TRUE iff 'a', this vector and 'b' are not collinear.
double distance (const Point &b) const
Distance from 'b'.
double distance (const Point *b) const
Distance from '*b'.
double squaredDistance (const Point *b) const
Squared distance from '*b'.
double distanceFromLine (const Point *a, const Point *b) const
Distance from straight line through 'a' and 'b'.
double distanceFromLine (const Point *a, const Point *b, Point *cc) const
Distance from straight line through 'a' and 'b'. *cc is set to the closest line point.
double distanceFromEdge (const Point *a, const Point *b) const
Distance from segment a-b.
double distanceFromEdge (const Point *a, const Point *b, Point *cc) const
Distance from segment a-b. *cc is set to the closest edge point.
double distanceLineLine (const Point *l1_p2, const Point *l2_p1, const Point *l2_p2) const
Distance between the straight lines through (this) - l1_p2 and l2_p1 - l2_p2.
double getAngle (const Point &v) const
double getAngle (const Point &a, const Point &b) const
Angle defined by <a, *this, b> in radians.
double getAngle (const Point *a, const Point *b) const
Angle defined by <*a, *this, *b> in radians.
Point linearSystem (const Point &row1, const Point &row2, const Point &row3)
Returns the solution of the linear system Ax = d, where A is a 3x3 matrix whose rows are row1, row2 and row3, d = this.
int side3D (const Point *p1, const Point *p2, const Point *p3) const
Side test.
int intersectionWithPlane (const Point *p1, const Point *p2, const Point *source, const Point *normal)
Sets the point as the intersection of a segment and a plane.
int intersectionWithPlane (const Point *p1, const Point *p2, const double &a, const double &b, const double &c, const double &d)
Sets the point as the intersection of a segment and a plane.
int closestPoints (const Point *this2, const Point *p1, const Point *p2, Point *cpOnThis, Point *cpOnOther) const
Line-line closest point computation.
Point projection (const Point *a, const Point *b) const
Returns the projection of the point on the straight line though 'a' and 'b'.
void printPoint (FILE *fp=stdout) const
Prints the coordinates of the point to a file handler. stdout is the default.
Public Attributes
coord x
coord y
coord z
Coordinates.
void * info
Further information.
Detailed Description
Geometric point definition.
This class represents a point in the Euclidean 3D space. It can be used to represent 3D vectors originating at (0,0,0) and terminating at the corresponding point. Several methods of this class are intended to manipulate vectors rather than points; for example, a call of the method normalize is an actual normalization if the object is a vector, but it has to be intended as a projection on the unit sphere if the object is intended to be a point. An object of type Point is a triplet (x,y,z) of coordinates endowed with a pointer 'info' to possible additional information. Each coordinate is a number of type 'coord' which, by default, is a standard double. Operations on points include addition, subtraction, cross and dot product, and many others. This class implements several useful operations using vector arithmethic. For example, the simple piece of code "A = B*C;" assignes to A the value of the dot product of B and C. Nearly zero or nearly flat angles are automatically snapped to exactly zero and exactly flat angles if the difference is smaller than the global variable _acos_tolerance. This is the very basic application of our version of the epsilon geometry for robust computation.
Definition at line 55 of file point.h.
Constructor & Destructor Documentation
Point::Point () [inline]
Creates a new point with coordinates (0,0,0).
Definition at line 62 of file point.h.
References info, x, y, and z.
{x = y = z = 0; info = NULL;}
Point::Point (const Point * s) [inline]
Creates a new point with the same coordinates as 's'. The info field is not copied.
Definition at line 65 of file point.h.
References info, x, y, and z.
{x = s->x; y = s->y; z = s->z; info = NULL;}
Point::Point (const Point & s) [inline]
Creates a new point with the same coordinates as 's'. The info field is not copied.
Definition at line 68 of file point.h.
References info, x, y, and z.
{x = s.x; y = s.y; z = s.z; info = NULL;}
Point::Point (const coord & a, const coord & b, const coord & c) [inline]
Creates a new point with coordinates (a,b,c).
Definition at line 71 of file point.h.
References info, x, y, and z.
{x = a; y = b; z = c; info = NULL;}
Member Function Documentation
int Point::closestPoints (const Point * this2, const Point * p1, const Point * p2, Point * cpOnThis, Point * cpOnOther) const
Line-line closest point computation.
Computes the closest points of the line passing through this and this2, and the line passing through p1 and p2. The computed points are used to initialize the coordinates of cpOnThis and cpOnOther. The method returns 0 if the lines are parallel, 1 otherwise.
Definition at line 324 of file point.cpp.
References distanceFromLine(), getAngle(), length(), M_PI, normalize(), and setValue().
{
 Point pos1 = *this; Point dir1 = (*v1)-pos1;
 Point pos2 = *p1;   Point dir2 = (*p2)-pos2;
 double d1l = dir1.length(), d2l = dir2.length();
 if (d1l == 0.0 && d2l == 0.0)
  {ptOnThis->setValue(this); ptOnLine2->setValue(p1); return 1;}
 if (d1l*d2l == 0.0)
 {
  if (d1l <= d2l)
   {ptOnThis->setValue(this); distanceFromLine(p1, p2, ptOnLine2); return 1;}
  if (d2l <= d1l)
   {ptOnLine2->setValue(p1); p1->distanceFromLine(this, v1, ptOnThis); return 1;}
 }
 double ang = dir1.getAngle(dir2);
 if (ang == 0.0 || ang == M_PI) return 0;
 double s, t, A, B, C, D, E, F, denom;
 denom = ((dir1*dir2)/(d1l*d2l));
 denom = denom*denom - 1;
 dir1.normalize();
 dir2.normalize();
 A = E = dir1*dir2;
 B = dir1*dir1;
 C = (dir1*pos1) - (dir1*pos2);
 D = dir2*dir2;
 F = (dir2*pos1) - (dir2*pos2);
 s = ( C * D - A * F ) / denom;
 t = ( C * E - B * F ) / denom;
 *ptOnThis  = pos1 + (dir1*s);
 *ptOnLine2 = pos2 + (dir2*t);
// Uncomment the following to compute the distance between segments
// if (s < 0 || s > ((*v1)-(*this)).length() || t < 0 || t > ((*p2)-(*p1)).length())
//  return 0;          // The points does not belong to the edges
 return 1;
}
double Point::distance (const Point & b) const [inline]
Distance from 'b'.
Definition at line 146 of file point.h.
References length().
{return (((*(this))-(b)).length());}
double Point::distance (const Point * b) const [inline]
Distance from '*b'.
Definition at line 149 of file point.h.
References length().
{return (((*(this))-(*b)).length());}
double Point::distanceFromEdge (const Point * a, const Point * b) const
Distance from segment a-b.
Definition at line 180 of file point.cpp.
References distanceFromLine(), getAngle(), length(), and PI2.
{
 Point AP = (*A)-(*this); double apl = AP.length();
 Point BP = (*B)-(*this); double bpl = BP.length();
 if (apl == 0 || bpl == 0.0) return 0.0;
 Point AB = (*A)-(*B); double abl = AP.length();
 Point BA = (*B)-(*A);
 if (abl*apl == 0.0 || abl*bpl == 0.0) return apl;
 if (AB.getAngle(AP) > PI2) return apl;
 else if (BA.getAngle(BP) > PI2) return bpl;
 return distanceFromLine(A,B);
}
double Point::distanceFromEdge (const Point * a, const Point * b, Point * cc) const
Distance from segment a-b. *cc is set to the closest edge point.
Definition at line 202 of file point.cpp.
References distanceFromLine(), getAngle(), length(), PI2, setValue(), x, y, and z.
{
 Point AP = (*A)-(*this); double apl = AP.length();
 Point BP = (*B)-(*this); double bpl = BP.length();
 if (apl == 0) {cc->setValue(A); return 0.0;}
 if (bpl == 0) {cc->setValue(B); return 0.0;}
 Point AB = (*A)-(*B); double abl = AP.length();
 Point BA = (*B)-(*A);
 if (abl*apl == 0.0 || abl*bpl == 0.0) {cc->setValue(A); return apl;}
 if (AB.getAngle(AP) > PI2) {cc->setValue(A); return apl;}
 else if (BA.getAngle(BP) > PI2) {cc->setValue(B); return bpl;}
 double t = (AB*AB);
 if (t == 0.0) {cc->setValue(A); return apl;}
 else t = (AP*AB)/(-t);
 cc->x = t*AB.x + A->x;
 cc->y = t*AB.y + A->y;
 cc->z = t*AB.z + A->z;
 return distanceFromLine(A,B);
}
double Point::distanceFromLine (const Point * a, const Point * b, Point * cc) const
Distance from straight line through 'a' and 'b'. *cc is set to the closest line point.
Definition at line 139 of file point.cpp.
References distanceFromLine(), JMesh::error(), isNull(), x, y, and z.
{
 Point AB = (*A)-(*B);
 Point AP = (*A)-(*this);
 Point BP = (*B)-(*this);
 if (AP.isNull())
 {
  cc->x = A->x; cc->y = A->y; cc->z = A->z;
  return 0.0;
 }
 else if (BP.isNull())
 {
  cc->x = B->x; cc->y = B->y; cc->z = B->z;
  return 0.0;
 }
 double t = (AB*AB);
 if (t == 0.0) JMesh::error("distanceFromLine : Degenerate line passed !\n");
 else t = (AP*AB)/(-t);
 cc->x = t*AB.x + A->x;
 cc->y = t*AB.y + A->y;
 cc->z = t*AB.z + A->z;
 return distanceFromLine(A,B);
}
double Point::distanceFromLine (const Point * a, const Point * b) const
Distance from straight line through 'a' and 'b'.
Definition at line 124 of file point.cpp.
References JMesh::error(), and length().
{
 Point BA = (*B)-(*A);
 double lba = BA.length();
 if (lba == 0.0) JMesh::error("distanceFromLine : Degenerate line passed !\n");
 return ((((*this)-(*A))&BA).length())/(lba);
}
double Point::distanceLineLine (const Point * l1_p2, const Point * l2_p1, const Point * l2_p2) const
Distance between the straight lines through (this) - l1_p2 and l2_p1 - l2_p2.
Angle between this vector and 'v' in radians.
Definition at line 268 of file point.cpp.
References FABS, and length().
{
 Point uu1 = ((*this)-(*A))&((*A1)-(*B1));
 double nom = ((*A)-(*A1))*(uu1);
 return FABS(nom)/(uu1.length());
}
double Point::getAngle (const Point & v) const
Definition at line 229 of file point.cpp.
References JMesh::acos_tolerance, FABS, length(), M_PI, and JMesh::warning().
{
 double ac, l = (length()*(p.length()));
 if (l == 0.0) {JMesh::warning("getAngle : One or both vectors are null !\n"); return -1.0;}
 ac = ((*this)*p)/l;
 if ((FABS((ac - 1.0))) < JMesh::acos_tolerance) ac = 0.0;
 else if ((FABS((1.0 + ac))) < JMesh::acos_tolerance) ac = M_PI;
 else ac = acos(ac);
 if (errno == EDOM)
 {
  JMesh::warning("Point::getAngle(): Warning. acos domain overflow !\n");
  errno = 0;
  return -1.0;
 }
 return ac;
}
double Point::getAngle (const Point & a, const Point & b) const [inline]
Angle defined by <a, *this, b> in radians.
Definition at line 172 of file point.h.
{return (a-(*this)).getAngle(b-(*this));}
double Point::getAngle (const Point * a, const Point * b) const [inline]
Angle defined by <*a, *this, *b> in radians.
Definition at line 175 of file point.h.
{return ((*a)-(*this)).getAngle((*b)-(*this));}
int Point::intersectionWithPlane (const Point * p1, const Point * p2, const Point * source, const Point * normal)
Sets the point as the intersection of a segment and a plane.
Initializes the coordinates with the intersection of the segment p1-p2 and the plane passing through 'source' with normal 'normal'. If the segment lies entirely on the plane, this method returns 2 and the coordinates are initialized with those of 'p1'. If there is no intersection, the method returns 0 and the coordinates are not modified. Otherwise the method returns 1.
Definition at line 316 of file point.cpp.
References x, y, and z.
{
 return intersectionWithPlane(A, B, nor->x, nor->y, nor->z, -((*nor)*(*s)));
}
int Point::intersectionWithPlane (const Point * A, const Point * B, const double & a, const double & b, const double & c, const double & d)
Sets the point as the intersection of a segment and a plane.
Initializes the coordinates with the intersection of the segment p1-p2 and the plane of equation ax+by+cz+d = 0. If the segment lies entirely on the plane, this method returns 2 and the coordinates are initialized with those of 'p1'. If there is no intersection, the method returns 0 and the coordinates are not modified. Otherwise the method returns 1.
Initializes the point with the intersection between the edge AB and the plane ax+by+cz+d=0. If there is no intersection returns 0. If the edge lies entirely on the plane returns 2.
Definition at line 296 of file point.cpp.
References FABS, Point(), x, y, and z.
{
 Point abc = Point(a,b,c);
 double pa = (abc*(*A))+d;
 double pb = (abc*(*B))+d;
 if (pa == 0) {x = A->x; y = A->y; z = A->z; return (pb==0)?(2):(1);}
 if (pb == 0) {x = B->x; y = B->y; z = B->z; return 1;}
 if (pa*pb > 0) return 0;
 pa = FABS(pa);
 pb = FABS(pb);
 Point o = ((*B)*pa + (*A)*pb)/(pa+pb);
 x = o.x; y = o.y; z = o.z;
 return 1;
}
Point Point::inverse () const [inline]
Returns the inverse vector.
Definition at line 119 of file point.h.
References Point(), x, y, and z.
{return Point(-x,-y,-z);}
void Point::invert () [inline]
Inverts the vector.
Definition at line 122 of file point.h.
References x, y, and z.
{x=-x; y=-y; z=-z;}
bool Point::isNull () const [inline]
TRUE if vector is (0,0,0)
Definition at line 125 of file point.h.
References x, y, and z.
{return (x==0 && y==0 && z==0);}
double Point::length () const [inline]
Distance from origin.
Definition at line 128 of file point.h.
References x, y, and z.
{return sqrt(x*x + y*y + z*z);}
Point Point::linearSystem (const Point & row1, const Point & row2, const Point & row3)
Returns the solution of the linear system Ax = d, where A is a 3x3 matrix whose rows are row1, row2 and row3, d = this.
Definition at line 279 of file point.cpp.
References INFINITE_POINT, Point(), x, y, and z.
{
 Point ret;
 double det_A = a*(b&c);
 if (det_A == 0.0) return INFINITE_POINT;
 ret.x = (Point(x,a.y,a.z))*((Point(y,b.y,b.z))&(Point(z,c.y,c.z)));
 ret.y = (Point(a.x,x,a.z))*((Point(b.x,y,b.z))&(Point(c.x,z,c.z)));
 ret.z = (Point(a.x,a.y,x))*((Point(b.x,b.y,y))&(Point(c.x,c.y,z)));
 return (ret/det_A);
}
void Point::normalize ()
Divides the vector by its length. If isNull() the application exits with an error.
Definition at line 56 of file point.cpp.
References JMesh::error(), length(), x, y, and z.
{
 double l = length();
 if (l == 0) JMesh::error("normalize : Trying to normalize a null vector !\n");
 x/=l;
 y/=l;
 z/=l;
}
bool Point::notAligned (const Point * a, const Point * b) const
TRUE iff 'a', this vector and 'b' are not collinear.
Definition at line 112 of file point.cpp.
References getAngle(), length(), and M_PI.
{
 Point p1 = ((*this)-(*A)), p2 = ((*this)-(*B));
 if (p1.length()*p2.length() == 0.0) return 0;
 double a = p1.getAngle(p2);
 return (a != 0.0 && a != M_PI);
}
bool Point::operator!= (const Point & p) const [inline]
FALSE iff coordinates are equal.
Definition at line 116 of file point.h.
References x, y, and z.
{return (x!=p.x || y!=p.y || z!=p.z);}
Point Point::operator& (const Point & p) const [inline]
Returns the Cross Product.
Definition at line 95 of file point.h.
References Point(), x, y, and z.
{return Point(y*p.z-z*p.y, z*p.x-x*p.z, x*p.y-y*p.x);}
double Point::operator* (const Point & p) const [inline]
Returns the Dot Product.
Definition at line 98 of file point.h.
References x, y, and z.
{return (x*p.x+y*p.y+z*p.z);}
Point Point::operator* (const double & d) const [inline]
Returns the product with a scalar.
Definition at line 101 of file point.h.
References Point(), x, y, and z.
{return Point(x*d,y*d,z*d);}
void Point::operator*= (const double & m) [inline]
Multiplies by a scalar.
Definition at line 104 of file point.h.
References x, y, and z.
{x*=m; y*=m; z*=m;}
Point Point::operator+ (const Point & p) const [inline]
Returns the vector sum.
Definition at line 86 of file point.h.
References Point(), x, y, and z.
{return Point(x+p.x, y+p.y, z+p.z);}
void Point::operator+= (const Point & p) [inline]
Sums another point.
Definition at line 89 of file point.h.
References x, y, and z.
{x+=p.x; y+=p.y; z+=p.z;}
Point Point::operator- (const Point & p) const [inline]
Returns the vector difference.
Definition at line 83 of file point.h.
References Point(), x, y, and z.
{return Point(x-p.x, y-p.y, z-p.z);}
void Point::operator-= (const Point & p) [inline]
Subtracts another point.
Definition at line 92 of file point.h.
References x, y, and z.
{x-=p.x; y-=p.y; z-=p.z;}
Point Point::operator/ (const double & d) const [inline]
Returns the vector divided by the scalar.
Definition at line 110 of file point.h.
References Point(), x, y, and z.
{return Point(x/d,y/d,z/d);}
void Point::operator/= (const double & m) [inline]
Divides by a scalar.
Definition at line 107 of file point.h.
References x, y, and z.
{x/=m; y/=m; z/=m;}
bool Point::operator== (const Point & p) const [inline]
TRUE iff coordinates are equal.
Definition at line 113 of file point.h.
References x, y, and z.
{return (x==p.x && y==p.y && z==p.z);}
void Point::printPoint (FILE * fp = stdout) const [inline]
Prints the coordinates of the point to a file handler. stdout is the default.
Definition at line 219 of file point.h.
References x, y, and z.
{fprintf(fp,"%f %f %f,\n",x,y,z);}      // Debug
void Point::project (const Point * n)
Projects the vector on the plane with normal 'n' passing through the origin.
Definition at line 103 of file point.cpp.
References x, y, and z.
{
 Point pr = (*this)-((*nor)*((*this)*(*nor)));
 x = pr.x; y = pr.y; z = pr.z;
}
Point Point::projection (const Point * a, const Point * b) const
Returns the projection of the point on the straight line though 'a' and 'b'.
Definition at line 168 of file point.cpp.
References JMesh::error().
{
 Point BA = (*B)-(*A);
 double l = BA*BA;
 if (l == 0.0) JMesh::error("projection : Degenerate line passed !\n");
 return ((*A)+(BA*((BA*((*this)-(*A)))/(l))));
}
void Point::rotate (const Point & axis, const double & ang)
Rotates the vector around 'axis' by 'ang' radians ccw.
Definition at line 71 of file point.cpp.
References length(), x, y, and z.
{
 double l, q[4], m[3][3];
 if ((l = a.length())==0.0) return;
 l = sin(ang/2.0)/l;
 q[0] = a.x*l;
 q[1] = a.y*l;
 q[2] = a.z*l;
 q[3] = cos(ang/2.0);
 m[0][0] = 1 - 2.0*(q[1]*q[1] + q[2]*q[2]);
 m[0][1] =     2.0*(q[0]*q[1] + q[2]*q[3]);
 m[0][2] =     2.0*(q[2]*q[0] - q[1]*q[3]);
 m[1][0] =     2.0*(q[0]*q[1] - q[2]*q[3]);
 m[1][1] = 1 - 2.0*(q[2]*q[2] + q[0]*q[0]);
 m[1][2] =     2.0*(q[1]*q[2] + q[0]*q[3]);
 m[2][0] =     2.0*(q[2]*q[0] + q[1]*q[3]);
 m[2][1] =     2.0*(q[1]*q[2] - q[0]*q[3]);
 m[2][2] = 1 - 2.0*(q[1]*q[1] + q[0]*q[0]);
 q[0] = x; q[1] = y; q[2] = z;
 x = m[0][0]*q[0] + m[1][0]*q[1] + m[2][0]*q[2];
 y = m[0][1]*q[0] + m[1][1]*q[1] + m[2][1]*q[2];
 z = m[0][2]*q[0] + m[1][2]*q[1] + m[2][2]*q[2];
}
void Point::setValue (const Point & p) [inline]
Set the coordinates as those of 'p'.
Definition at line 77 of file point.h.
References x, y, and z.
{x = p.x; y = p.y; z = p.z;}
void Point::setValue (const Point * p) [inline]
Set the coordinates as those of '*p'.
Definition at line 80 of file point.h.
References x, y, and z.
{x = p->x; y = p->y; z = p->z;}
void Point::setValue (const coord & a, const coord & b, const coord & c) [inline]
Set the coordinates to (a,b,c).
Definition at line 74 of file point.h.
References x, y, and z.
{x = a; y = b; z = c;}
int Point::side3D (const Point * p1, const Point * p2, const Point * p3) const
Side test.
When looking from the direction pointed to by this vector, this method returns 1 if the points 'p1', 'p2' and 'p3' turn right, -1 if they turn left, 0 if they are aligned. Notice that in this latter case the three point do not need to be linearly dependent.
Definition at line 254 of file point.cpp.
References getAngle(), length(), and M_PI.
{
 Point A = ((*p1)-(*p2)), B = ((*p2)-(*p3));
 double l1 = A.length(), l2 = B.length();
 if (l1*l2 == 0.0) return 0;
 double ang = A.getAngle(B);
 if (ang == 0.0 || ang == M_PI) return 0;
 double db = ((A&B)*(*this));
 return (db > 0)?(1):(-1);
}
double Point::squaredDistance (const Point * b) const [inline]
Squared distance from '*b'.
Definition at line 152 of file point.h.
References squaredLength().
{return (((*(this))-(*b)).squaredLength());}
double Point::squaredLength () const [inline]
Squared distance from origin.
Definition at line 131 of file point.h.
References x, y, and z.
{return (x*x + y*y + z*z);}
Member Data Documentation
void* Point::info
Further information.
Definition at line 59 of file point.h.
coord Point::x
Definition at line 58 of file point.h.
coord Point::y
Definition at line 58 of file point.h.
coord Point::z
Coordinates.
Definition at line 58 of file point.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/point.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/MESH_STRUCTURE/point.cpp