OpenCog Framework: dijkstraHeap Class Reference
dijkstraHeap Class Reference
#include <dijkstraGraph.h>
Public Member Functions
dijkstraHeap (int n, dijkstraNode **nod)
~dijkstraHeap ()
void push (dijkstraNode *n)
dijkstraNode * getHead ()
dijkstraNode * popHead ()
int isEmpty ()
void remove (dijkstraNode *n)
void update (dijkstraNode *n)
int compare (const void *, const void *)
Comparison of two heap elements.
Public Attributes
dijkstraNode ** nodes
Detailed Description
Definition at line 56 of file dijkstraGraph.h.
Constructor & Destructor Documentation
dijkstraHeap::dijkstraHeap (int n, dijkstraNode ** nod) [inline]
Definition at line 61 of file dijkstraGraph.h.
References nodes, and abstractHeap::positions.
                                         : abstractHeap(n)
  {positions = new int[n+1]; nodes = nod; for (int i=0; i<=n; i++) positions[i]=0;}
dijkstraHeap::~dijkstraHeap () [inline]
Definition at line 64 of file dijkstraGraph.h.
References abstractHeap::positions.
{delete(positions);}
Member Function Documentation
int dijkstraHeap::compare (const void * a, const void * b) [virtual]
Comparison of two heap elements.
This function must be implemented in the extended class. The return value must be <0 if a<b, >0 if a>b or 0 if a=b.
Implements abstractHeap.
Definition at line 31 of file dijkstraGraph.cpp.
References dijkstraNode::dist, and nodes.
{
 dijkstraNode *a = nodes[(j_voidint)n1];
 dijkstraNode *b = nodes[(j_voidint)n2];
 double l1 = a->dist;
 double l2 = b->dist;
 if (l1 < l2) return -1;
 if (l1 > l2) return 1;
 return 0;
}
dijkstraNode* dijkstraHeap::getHead () [inline]
Definition at line 67 of file dijkstraGraph.h.
References getHead().
{return (dijkstraNode *)getHead();}
int dijkstraHeap::isEmpty () [inline]
Definition at line 69 of file dijkstraGraph.h.
References abstractHeap::numels.
{return (numels==0);}
dijkstraNode* dijkstraHeap::popHead () [inline]
Definition at line 68 of file dijkstraGraph.h.
References nodes, abstractHeap::numels, and abstractHeap::removeHead().
{return (numels)?(nodes[(j_voidint)removeHead()]):(NULL);}
void dijkstraHeap::push (dijkstraNode * n) [inline]
Definition at line 66 of file dijkstraGraph.h.
References dijkstraNode::index, and abstractHeap::insert().
{insert((void *)(n->index));}
void dijkstraHeap::remove (dijkstraNode * n) [inline]
Definition at line 71 of file dijkstraGraph.h.
References abstractHeap::positions, abstractHeap::removeHead(), and abstractHeap::upheap().
  {n->dist = -1; if (positions[n->index]) {upheap(positions[n->index]); removeHead();}}
void dijkstraHeap::update (dijkstraNode * n) [inline]
Definition at line 74 of file dijkstraGraph.h.
References abstractHeap::downheap(), dijkstraNode::index, abstractHeap::positions, push(), and abstractHeap::upheap().
  {if (!positions[n->index]) push(n); else downheap(upheap(positions[n->index]));}
Member Data Documentation
dijkstraNode** dijkstraHeap::nodes
Definition at line 59 of file dijkstraGraph.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/dijkstraGraph.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/dijkstraGraph.cpp