OpenCog Framework: Matrix3x3 Class Reference
Matrix3x3 Class Reference
Generic 3x3 matrix.
#include <matrix.h>
Public Member Functions
Matrix3x3 ()
Contructs a null matrix.
Matrix3x3 (const double &a11, const double &a12, const double &a13, const double &a21, const double &a22, const double &a23, const double &a31, const double &a32, const double &a33)
Constructs a fully initialized matrix.
Matrix3x3 (const double &v1, const double &v2, const double &v3, const double &w1, const double &w2, const double &w3)
Constructs a 3x3 matrix as the product of Transpose(v1,v2,v3) and (w1,w2,w3).
Matrix3x3 (const double &a, const double &b, const double &c)
Constructs a 3x3 matrix as the product of Transpose(a,b,c) and (a,b,c).
bool isSymmetric () const
Returns TRUE if the matrix is symmetric.
void operator= (const double &d)
Initializes all elements to 'd'.
void operator+= (const Matrix3x3 &)
Sum another matrix.
void operator-= (const Matrix3x3 &)
Subtract another matrix.
void operator*= (const double &)
Multiply by a scalar.
void operator/= (const double &d)
Divide by a scalar.
Matrix3x3 operator+ (const Matrix3x3 &) const
Returns the sum of this and another matrix.
Matrix3x3 operator* (const double &) const
Returns the product of this matrix with a scalar.
Matrix3x3 operator* (const Matrix3x3 &) const
Returns the product of this and another matrix (rows by columns)
Matrix3x3 operator~ () const
Returns the transpose of this matrix.
Matrix3x3 transpose () const
Return the matrix transpose.
double lrMultiply (const double &a, const double &b, const double &c) const
Returns Transpose(a,b,c)*M*(a,b,c)
double lrMultiply (const double &v1, const double &v2, const double &v3, const double &w1, const double &w2, const double &w3) const
Returns the (scalar) result of v*M*w.
Public Attributes
double M [9]
Actual values of the matrix.
Detailed Description
Generic 3x3 matrix.
Elements are stored in a row-dominant order, thus for example, M[4] is the first element of the second row.
Definition at line 46 of file matrix.h.
Constructor & Destructor Documentation
Matrix3x3::Matrix3x3 () [inline]
Contructs a null matrix.
Definition at line 51 of file matrix.h.
References M.
Matrix3x3::Matrix3x3 (const double & a11, const double & a12, const double & a13, const double & a21, const double & a22, const double & a23, const double & a31, const double & a32, const double & a33)
Constructs a fully initialized matrix.
Definition at line 42 of file matrix.cpp.
References M.
{
 M[0] = a11; M[1] = a12; M[2] = a13;
 M[3] = a21; M[4] = a22; M[5] = a23;
 M[6] = a31; M[7] = a32; M[8] = a33;
}
Matrix3x3::Matrix3x3 (const double & v1, const double & v2, const double & v3, const double & w1, const double & w2, const double & w3)
Constructs a 3x3 matrix as the product of Transpose(v1,v2,v3) and (w1,w2,w3).
Definition at line 54 of file matrix.cpp.
References M.
{
 M[0] = v1*w1; M[1] = v1*w2; M[2] = v1*w3;
 M[3] = v2*w1; M[4] = v2*w2; M[5] = v2*w3;
 M[6] = v3*w1; M[7] = v3*w2; M[8] = v3*w3;
}
Matrix3x3::Matrix3x3 (const double & a, const double & b, const double & c)
Constructs a 3x3 matrix as the product of Transpose(a,b,c) and (a,b,c).
Definition at line 65 of file matrix.cpp.
References M.
{
 M[0] = x*x;  M[1] = x*y;  M[2] = x*z;
 M[3] = M[1]; M[4] = y*y;  M[5] = y*z;
 M[6] = M[2]; M[7] = M[5]; M[8] = z*z;
}
Member Function Documentation
bool Matrix3x3::isSymmetric () const [inline]
Returns TRUE if the matrix is symmetric.
Definition at line 66 of file matrix.h.
References M.
{return (M[2]==M[4] && M[3]==M[7] && M[6]==M[8]);}
double Matrix3x3::lrMultiply (const double & a, const double & b, const double & c) const
Returns Transpose(a,b,c)*M*(a,b,c)
Returns the (scalar) result of multiplying the matrix on the left and on the right by the vector (a,b,c).
Definition at line 145 of file matrix.cpp.
References M.
{
 return (x*(x*M[0] + y*M[3] + z*M[6]) + y*(x*M[1] + y*M[4] + z*M[7]) + z*(x*M[2] + y*M[5] + z*M[8]));
}
double Matrix3x3::lrMultiply (const double & v1, const double & v2, const double & v3, const double & w1, const double & w2, const double & w3) const
Returns the (scalar) result of v*M*w.
Definition at line 152 of file matrix.cpp.
References M.
{
 return (w1*(v1*M[0] + v2*M[3] + v3*M[6]) + w2*(v1*M[1] + v2*M[4] + v3*M[7]) + w3*(v1*M[2] + v2*M[5] + v3*M[8]));
}
Matrix3x3 Matrix3x3::operator* (const double & d) const
Returns the product of this matrix with a scalar.
Definition at line 115 of file matrix.cpp.
References M, and Matrix3x3().
{
 return Matrix3x3(M[0]*d, M[1]*d, M[2]*d,
                  M[3]*d, M[4]*d, M[5]*d,
                  M[6]*d, M[7]*d, M[8]*d);
}
Matrix3x3 Matrix3x3::operator* (const Matrix3x3 & q) const
Returns the product of this and another matrix (rows by columns)
Definition at line 125 of file matrix.cpp.
References M, and Matrix3x3().
{
 return Matrix3x3(
          M[0]*q.M[0]+M[1]*q.M[3]+M[2]*q.M[6], M[0]*q.M[1]+M[1]*q.M[4]+M[2]*q.M[7], M[0]*q.M[2]+M[1]*q.M[5]+M[2]*q.M[8],
          M[3]*q.M[0]+M[4]*q.M[3]+M[5]*q.M[6], M[3]*q.M[1]+M[4]*q.M[4]+M[5]*q.M[7], M[3]*q.M[2]+M[4]*q.M[5]+M[5]*q.M[8],
          M[6]*q.M[0]+M[7]*q.M[3]+M[8]*q.M[6], M[6]*q.M[1]+M[7]*q.M[4]+M[8]*q.M[7], M[6]*q.M[2]+M[7]*q.M[5]+M[8]*q.M[8]
         );
}
void Matrix3x3::operator*= (const double & d)
Multiply by a scalar.
Definition at line 95 of file matrix.cpp.
References M.
{
 M[0] *= d; M[1] *= d; M[2] *= d;
 M[3] *= d; M[4] *= d; M[5] *= d;
 M[6] *= d; M[7] *= d; M[8] *= d;
}
Matrix3x3 Matrix3x3::operator+ (const Matrix3x3 & s) const
Returns the sum of this and another matrix.
Definition at line 105 of file matrix.cpp.
References M, and Matrix3x3().
{
 return Matrix3x3(M[0]+s.M[0], M[1]+s.M[1], M[2]+s.M[2],
                  M[3]+s.M[3], M[4]+s.M[4], M[5]+s.M[5],
                  M[6]+s.M[6], M[7]+s.M[7], M[8]+s.M[8]);
}
void Matrix3x3::operator+= (const Matrix3x3 & s)
Sum another matrix.
Definition at line 75 of file matrix.cpp.
References M.
{
 M[0] += s.M[0]; M[1] += s.M[1]; M[2] += s.M[2];
 M[3] += s.M[3]; M[4] += s.M[4]; M[5] += s.M[5];
 M[6] += s.M[6]; M[7] += s.M[7]; M[8] += s.M[8];
}
void Matrix3x3::operator-= (const Matrix3x3 & s)
Subtract another matrix.
Definition at line 85 of file matrix.cpp.
References M.
{
 M[0] -= s.M[0]; M[1] -= s.M[1]; M[2] -= s.M[2];
 M[3] -= s.M[3]; M[4] -= s.M[4]; M[5] -= s.M[5];
 M[6] -= s.M[6]; M[7] -= s.M[7]; M[8] -= s.M[8];
}
void Matrix3x3::operator/= (const double & d) [inline]
Divide by a scalar.
Definition at line 75 of file matrix.h.
References operator*=().
void Matrix3x3::operator= (const double & d) [inline]
Initializes all elements to 'd'.
Definition at line 70 of file matrix.h.
References M.
{M[0]=M[1]=M[2]=M[3]=M[4]=M[5]=M[6]=M[7]=M[8]=d;}
Matrix3x3 Matrix3x3::operator~ () const
Returns the transpose of this matrix.
Definition at line 137 of file matrix.cpp.
References M, and Matrix3x3().
{
 return Matrix3x3(M[0],M[3],M[6],M[1],M[4],M[7],M[2],M[5],M[8]);
}
Matrix3x3 Matrix3x3::transpose () const
Return the matrix transpose.
Definition at line 158 of file matrix.cpp.
References M, and Matrix3x3().
{
 return Matrix3x3(M[0], M[3], M[6],
                  M[1], M[4], M[7],
                  M[2], M[5], M[8]);
}
Member Data Documentation
double Matrix3x3::M[9]
Actual values of the matrix.
Definition at line 49 of file matrix.h.
The documentation for this class was generated from the following files:
/home/wondereamer/object_detection/JMeshLib-1.2/include/matrix.h
/home/wondereamer/object_detection/JMeshLib-1.2/src/PRIMITIVES/matrix.cpp